### ISSUE TITLE
Test + docs: label/image.py

### ISSUE THREAD

**Issue by NMontanaBrown** [DeepRegNet/DeepReg#107]
# Issue description

Test + docs required for:
- Image.py: missing docstrings. Unit tests for inputs outputs.

## Type of Issue

Please delete options that are not relevant.

- [x] Documentation update
- [x] Test request
- [x] Linting request

#### What's the expected result?
Unit tests for image.py functionalities

**Comment by NMontanaBrown** [comment]
@ZheMin-1992 can you assign yourself to this ticket?

**Comment by mathpluscode** [comment]
@NMontanaBrown You mentioned in #127 @s-sd has done an excellent work on tests, maybe we can link the PR/issue or the file to others as an example? (sorry i tried but can't find the specific test you mentioned)

**Comment by YipengHu** [comment]
this is related #162

**Comment by ZheMin-1992** [comment]
> Hi @ZheMin-1992 I think @NMontanaBrown mean this issue #125 from @s-sd ! ;) an excellent example to start with tests.
> Also, @ZheMin-1992, in case of any questions regarding the code/docs, please feel free to ping me on Teams or add issues to raise questions!

@mathpluscode Thanks a lot! Will do if meet with any problems.
