### ISSUE TITLE
CI + docs: pre-commit hook with contradicting changes w/ flake8 and black

### ISSUE THREAD

**Issue by NMontanaBrown** [DeepRegNet/DeepReg#119]
# Issue description

In [this thread](https://github.com/ucl-candi/DeepReg/pull/117#commitcomment-40332851), we get discrepancies between actions for black and flake8 that cause CI to fail. Black 8 causes linting changes that fail flake8. Probably requires modification of the pre-commit hook/CI actions such that there is a preferential linter or the issue, we drop one of two, or provide some instruction to ignore such an error from flake8.

## Type of Issue

Please delete options that are not relevant.

- [x] Bug report
- [x] New feature request

#### For bug report or feature request, steps to reproduce the issue, including (but not limited to):

See link above.

#### What's the expected result?

Pre-commit hook does not contradict itself when applying changes between flake8 and black.

**Comment by mathpluscode** [comment]
I feel for most of the conflicts, there's a workaround way, like the example in the issue.
I also had another conflict yesterday, due to a too long comment.

But I'm not sure how you gonna solve it without specific examples? (The example in the issue, i consider it as a problem of the code, as normally the comma was unnecessary)

**Comment by NMontanaBrown** [comment]
Ok, adding won't fix label for now but still worth thinking about... at a later stage.

**Comment by mathpluscode** [comment]
Have again a too long commit,

![image](https://user-images.githubusercontent.com/4066929/87482587-a573a600-c629-11ea-80e4-d19c01d0470d.png)

So maybe we can maintain a list of possible failures/conflicts in the docs, and for each case, we consider do we have a work around or we have to solve the conflict.

**Comment by mathpluscode** [comment]
Close this issue as we have this conflict section now https://deepreg.readthedocs.io/en/latest/contributing/setup.html#linting-conflicts
