### ISSUE TITLE
Demo - MR-US Prostate (label-reg)

### ISSUE THREAD

**Issue by ucl-candi** [DeepRegNet/DeepReg#12]
MR-to-ultrasound registration
data and previous demo: https://github.com/YipengHu/label-reg

This demo tests:
1 - weakly supervision
2 - conditional segmentation
and possibly
3 - different data formats?

**Comment by YipengHu** [comment]
@mathpluscode if you do not have time for this - let me know.

**Comment by mathpluscode** [comment]
@YipengHu tbh i think i do not have time this month for sure

**Comment by YipengHu** [comment]
> @YipengHu tbh i think i do not have time this month for sure

no problem - i can take this.

**Comment by mathpluscode** [comment]
@YipengHu thx! and plz ask me for the review, so that i can run it
