### ISSUE TITLE
Test + docs: dataset/loader/grouped_loader

### ISSUE THREAD

**Issue by NMontanaBrown** [DeepRegNet/DeepReg#124]
# Issue description 

Expand unit tests for grouped_loader, in pytest style.

- class GroupedDataLoader
    - init, validate_data_files, get_intra_sample_indices, get_inter_sample_indices, resample_index_generator, close

## Type of Issue

Please delete options that are not relevant.

- [x] Documentation update
- [x] Test request
- [x] Linting request

#### What's the expected result?
Unit tests that cover class and methods, asserting that methods return values that are expected for each method.

**Comment by mathpluscode** [comment]
Compared to the paired/unpaired loader #126 #127 , this loader is more complicated.

I suggest to wait until #126 and #127 are resolved and then we can ask the same or a different person to test grouped loader. The corresponding docs have to be verified.

**Comment by YipengHu** [comment]
https://ucl-candi.github.io/DeepReg/#/doc_data_loader

**Comment by agrimwood** [comment]
hi all,
quick question regarding var `sample_indices` . I may be reading the code wrong, could you advise?
It looks like `sample_indices` is dropped from `self` when `sample_image_in_group = False` (line 99 in grouped_loader.py).
Is this correct, or should it be passed to the function `sample_index_generator`?

@NMontanaBrown , @mathpluscode , @YipengHu

**Comment by mathpluscode** [comment]
@agrimwood I think you are right!

Instead of
```
            if intra_group_prob == 0:  # inter group
                sample_indices = self.get_inter_sample_indices()
            else:  # intra group
                sample_indices = self.get_intra_sample_indices()
```

we should write

```
            if intra_group_prob == 0:  # inter group
                self.sample_indices = self.get_inter_sample_indices()
            else:  # intra group
                self.sample_indices = self.get_intra_sample_indices()
```

**Comment by YipengHu** [comment]
@agrimwood  great spot - that's precisely the reason we need a demo for the grouped loader for some sanity check.
