### ISSUE TITLE
Test + docs: dataset/loader/paired_loader

### ISSUE THREAD

**Issue by NMontanaBrown** [DeepRegNet/DeepReg#126]
# Issue description

Unit tests for paired_loader, in pytest style.

- class PairedDataLoader
    - init, validate_data_files, sample_index_generator, close

## Type of Issue

Please delete options that are not relevant.

- [x] Documentation update
- [x] Test request
- [x] Linting request

#### What's the expected result?
Unit tests for class methods, lint and docs.

**Comment by mathpluscode** [comment]
Considering the paired loader is very similar to unpaired loader #127 , i suggest to assign the same people for both.

The code for testing would be high similar so it is easier to add tests for one, and do the same for another.

@NMontanaBrown what do you think.

**Comment by NMontanaBrown** [comment]
This ticket has already been assigned, @agrimwood is working on it!

**Comment by agrimwood** [comment]
Hi @mathpluscode , @NMontanaBrown 

Apologies for stepping on anyone's toes. I selected this task as a learning exercise. It would be easier for one person to test the loaders, but they are also a good place for a relatively inexperienced user like me to start.

**Comment by mathpluscode** [comment]
@agrimwood Hi, thanks so much! After a discussion with @NMontanaBrown we agree that it's better to let more people understand the code instead of chasing for speed only ;)

**Comment by mathpluscode** [comment]
While fixing bugs, I found some more potential improvements to do
- in the test of paired loader, we are not covering both nifti and h5 loader as in unpaired loader and grouped loader
- the close function is not tested

@NMontanaBrown do you think it's important to cover before release?

**Comment by NMontanaBrown** [comment]
Yes to coverage
