### ISSUE TITLE
Test + docs: model/network/ddf.py

### ISSUE THREAD

**Issue by NMontanaBrown** [DeepRegNet/DeepReg#128]
# Issue description

Unit tests for `deepreg/model/network/ddf_dvf.py`, in pytest style.

- func `build_ddf_dvf_model`

## Type of Issue

Please delete options that are not relevant.

- [x] Documentation update
- [x] Test request
- [x] Linting request

#### What's the expected result?
Unit tests for func input outputs, lint and docs.

**Comment by mathpluscode** [comment]
Hi @acasamitjana @RemiDelaunay @NMontanaBrown , following the PR #140, the dvf model is merged with ddf model.

I added tests for `ddf_dvf_forward`, but the tests for `build_ddf_dvf_model` is still needed.
I suggest to build the model and check the models' inputs and outputs' shapes for both DDF and DVF modes.
