### ISSUE TITLE
Demo - CT Abdominal (learn2reg t3)

### ISSUE THREAD

**Issue by ucl-candi** [DeepRegNet/DeepReg#13]
Abdominal Organ CT Registration
data: https://learn2reg.grand-challenge.org/Dataset/
https://drive.google.com/file/d/1aWyS_mQ5n7X2bTk9etHrn5di2-EZEzyO/view

This demo can test:
1 - unpaired inter-subject reg with/without labels
2 - weakly supervised

**Comment by YipengHu** [comment]
@ebonmati do you need any help with this? please read the latest demo requirement in wiki.
