### ISSUE TITLE
Demo - MR-US Brain (learn2reg t1)

### ISSUE THREAD

**Issue by ucl-candi** [DeepRegNet/DeepReg#14]
MR-to-ultrasound registration
data: https://learn2reg.grand-challenge.org/Dataset/
https://archive.sigma2.no/pages/public/datasetDetail.jsf?id=10.11582/2020.00025

This demo tests:
1 - weakly supervision
2 - conditional segmentation
3 - unsupervised intra-subject
and potentially
4 - demonstrating new loss

**Comment by s-sd** [comment]
@YipengHu This dataset is 3.9 GB. Should we do a demo for it? It will take a long time to download within the script

**Comment by YipengHu** [comment]
@s-sd couple of options: only a subset data downloaded for demoing the training for instance - we can discuss this further tomorrow on dev meeting getting wider opinions.
