### ISSUE TITLE
Docs: Add missing docstring

### ISSUE THREAD

**Issue by mathpluscode** [DeepRegNet/DeepReg#152]
# Issue description

I will go through all the code and will add
- inputs/outputs types/shapes
- docstrings
- comments if needed
- change string "xxx".format to f"xxx"

## Type of Issue

- [ ] Documentation update
- [ ] Test request
- [ ] Linting request

**Comment by NMontanaBrown** [comment]
Hi @mathpluscode, can you please outline which files you are planning on working on for these changes? And link to related open tickets that might have a file clash such that other devs are aware of these changes?

**Comment by mathpluscode** [comment]
@NMontanaBrown technically this will be on all the files. But after the discussion of other members, they have raised some more detailed requirements, so I will fix those issues first then come back here. Maybe I can at least split the changes into several modules and merge them little by little ;)

**Comment by NMontanaBrown** [comment]
@mathpluscode Related to this ticket: #198 , can you suggest some docstrings for @ZheMin-1992 to add to the functions? Docs missing there.

**Comment by NMontanaBrown** [comment]
@mathpluscode also related to this ticket #194 , same: can you suggest some docstrings for @QianyeYang to add to functions?

**Comment by mathpluscode** [comment]
sure, will check with them later @NMontanaBrown
