### ISSUE TITLE
Check loss weights

### ISSUE THREAD

**Issue by mathpluscode** [DeepRegNet/DeepReg#155]
# Issue description

- When using DDF/DVF we have the regularization loss, it's better to add a check in parser to make sure the corresponding loss is non negative.
- For image loss and label loss, need to check the weight is non negative.
- When the data is labeled, raise warning when label loss has zero weight

Maybe we want to test this as well? @NMontanaBrown 

## Type of Issue

- [ ] New feature request
- [ ] Documentation update
- [ ] Test request?

**Comment by NMontanaBrown** [comment]
Pre or post r1? @mathpluscode

**Comment by mathpluscode** [comment]
it's a quick fix, pre-r1 @NMontanaBrown

**Comment by YipengHu** [comment]
@mathpluscode  are we still pre-r1 for this?

**Comment by mathpluscode** [comment]
yes yes still! @YipengHu

**Comment by mathpluscode** [comment]
Instead of raising errors, i choose to print warnings as maybe user want to do ablation study with special values like zero weights for losses

**Comment by mathpluscode** [comment]
close as it has been taken care of in #284
