### ISSUE TITLE
deepreg.net update

### ISSUE THREAD

**Issue by YipengHu** [DeepRegNet/DeepReg#161]
# Issue description

We need someone who has the expertise/interest to update the home website.

#### What's the expected result?

- Appropriate place to add the core dev team and contact details;
- Appropriate place and design review of DeepReg logo
- Appropriate place and acknowledgement for funding support

**Comment by zacbaum** [comment]
Probably best to create a "home" page (which isn't the setup/quick start page - this can be linked from the sidebar).

Much of the info we want to add can go on this page, and then we can also add an overview of the project, with value proposition / features, etc. (similar to those of [monai](https://monai.io/), [tf](https://www.tensorflow.org/) as examples). We can (for now anyway) list all contributors/funding as well as dev team/contact info here as well.

@YipengHu / @mathpluscode - if you can let me know some boilerplate text for what could go on the homepage, as well as funding / contributors, and dev team I can add those.

**Comment by YipengHu** [comment]
- the boilerplate text is a must but needs some thinking- maybe an item for thursday? - I will give it some thoughts;
- personally, monai homepage is a bit too busy for me;
- funding for now is just weiss, I will collect this info from others as well - we need to be careful with the wording. WEISS supports the project but does not "own" this ;) it is an open-source project;
- make the contributor list alphabetically? again we can discuss this on thur.

**Comment by mathpluscode** [comment]
@zacbaum there was a home page, you just need to change `homepage: "quick_start.md",` in`docs/index.html` change it to `README.md` (i deleted it, so we need to add this back)

for the contents... i have no idea

for the logs, we can add them in the coverpage, which is defined in `_coverpage.md`

btw, to visualize the changes locally, plz check https://ucl-candi.github.io/DeepReg/#/CONTRIBUTING?id=documentation-pages
, this works for me under linux, if you are using mac, feel free to update the docs!

**Comment by YipengHu** [comment]
fyi @zacbaum i never managed visualise this on local branch on my CB or windows/wsl, add to the doc if you figured it out.

**Comment by zacbaum** [comment]
> fyi @zacbaum i never managed visualise this on local branch on my CB or windows/wsl, add to the doc if you figured it out.

Have been able to with Windows (using cmd and Jekyll) so will do that when I go to make all these updates :)

**Comment by mathpluscode** [comment]
Just to add, the link in main README.md need to be updated
