### ISSUE TITLE
Partly labeled data support

### ISSUE THREAD

**Issue by mathpluscode** [DeepRegNet/DeepReg#162]
# Issue description

It might be possible that only part of the data are labeled, and we still want to use label loss for training.

There are two ways:
1. Ask user to create fake label, an array with the same size of image but all zeros.
2. We tolerate partly labeled data (if none of the data are labeled, we raise warning or error), and in case of unlabeled image, the generator will generate a zero tensor for the user.

In any case, we are proposing to use a zero tensor as fake label, need to check all related calculation in metrics and losses, to make sure that NaN will not appear as we might have division by zero.

Tests should be added to test for
1. unlabeled data, we expect a warning or error
2. partly labeled data, we expect no error

## Type of Issue

- [ ] Documentation update
- [ ] Test request
- [ ] Linting request

#### What's the expected result?

As discussed above.

#### What's the actual result?

For now, if the data is partly labeled, we will raise error. But I don't think we have test covering this.

**Comment by mathpluscode** [comment]
@YipengHu are we still planning to support this before release? and do you have time to do this?

**Comment by YipengHu** [comment]
> @YipengHu are we still planning to support this before release? and do you have time to do this?

Yes

I can certainly help with the doc to have the work-around - but trying to restrict myself from testing

**Comment by mathpluscode** [comment]
ok I will see if I have time to do this then, together with issue #234

**Comment by YipengHu** [comment]
@mathpluscode can you review this? if not immediate plan to add this, close it for now.

**Comment by mathpluscode** [comment]
> @mathpluscode can you review this? if not immediate plan to add this, close it for now.

@YipengHu Actually, this should be an important feature to release, we can consider it in the one after next release, aka 0.1.0b3.

**Comment by YipengHu** [comment]
> > @mathpluscode can you review this? if not immediate plan to add this, close it for now.
> 
> @YipengHu Actually, this should be an important feature to release, we can consider it in the one after next release, aka 0.1.0b3.

i do think it is important but also has workaround already - up to you really.

**Comment by mathpluscode** [comment]
> i

After I deploy the tests on demos (yeah I know I've been talking about this for ages).

**Comment by mathpluscode** [comment]
Reopen as we just updated the docs, but not really handling the issue.

**Comment by YipengHu** [comment]
> Reopen as we just updated the docs, but not really handling the issue.

I think uprating the doc is sufficient. Changing code to accept missing data has a higher risk. ( I think I commented this in the previous commit).....

**Comment by mathpluscode** [comment]
> > Reopen as we just updated the docs, but not really handling the issue.
> 
> I think uprating the doc is sufficient. Changing code to accept missing data has a higher risk. ( I think I commented this in the previous commit).....

Accept missing data makes the code a bit more robust, and we can always prints warning/errors?

**Comment by YipengHu** [comment]
> > > Reopen as we just updated the docs, but not really handling the issue.
> > 
> > 
> > I think uprating the doc is sufficient. Changing code to accept missing data has a higher risk. ( I think I commented this in the previous commit).....
> 
> Accept missing data makes the code a bit more robust, and we can always prints warning/errors?

I was going to add this, but when thinking about it, it only makes the code more prone to misuse - until we have a robust framework to define what can be missing what is safe. i consider the likelihood to have some problem in your data (unintentionally missing) is much larger than user being annoyed because they need to add a few all-zero labels to represent the missing data.
