### ISSUE TITLE
Code Refactoring: Train

### ISSUE THREAD

**Issue by mathpluscode** [DeepRegNet/DeepReg#170]
# Issue description

## Type of Issue

Refactor the train.py to make it easier to understand and add more docs

- [ ] Documentation update
- [ ] Test request
- [ ] Linting request

**Comment by NMontanaBrown** [comment]
Could you add the option to pass callbacks separately into the func? That way users may add their own custom callbacks during train (necessary for vis tool during train too)

**Comment by mathpluscode** [comment]
@NMontanaBrown For this, i think we will need something called register. I will find some more doc on this later.

**Comment by mathpluscode** [comment]
@NMontanaBrown I'm thinking about a register system like this: https://docs.ray.io/en/master/_modules/ray/tune/registry.html
It's not just for callback, it can be used for
- network
- registration method
- callback
- etc

what do you think?
