### ISSUE TITLE
Docs: review Issue and PR templates

### ISSUE THREAD

**Issue by NMontanaBrown** [DeepRegNet/DeepReg#177]
# Issue description
Some aspects of the PR and Issue template are not routinely used. Let's review and consider a better design?
## Type of Issue

Please delete options that are not relevant.

- [x] Documentation update

#### What's the expected result?
PR and Issue templates that dvs are happy to use 😄

**Comment by mathpluscode** [comment]
Only one thing i can remember is to remove the delete in the PR template ;)
