### ISSUE TITLE
CLI registration ultility tools

### ISSUE THREAD

**Issue by YipengHu** [DeepRegNet/DeepReg#178]
# Issue description

Create a set of utility CLI tools facilitating registration in TF

## Type of Issue

Please delete options that are not relevant.

- [ ] New feature request
- [ ] Documentation update
- [ ] Test request

#### What's the expected result?
must:
warp/transform - given reference grid and ddf/affine to warp an image/label volume;

optional:
DDF composing
DDF inverting
Jacobian computing
pair-wise registration - given two images, register using iterative optimisation

**Comment by NMontanaBrown** [comment]
Are these lots of separate CLIs or one massive CLI? @YipengHu @mathpluscode

**Comment by YipengHu** [comment]
> Are these lots of separate CLIs or one massive CLI? @YipengHu @mathpluscode

No preference. But when number of functions increase, we need to be careful with conflicting with others. So, 
Option 1: deepreg train .... deepreg warp....
Option 2: deepreg_train... deepreg_warp...
Thoughts?

**Comment by mathpluscode** [comment]
@YipengHu @NMontanaBrown It will be seperate clis!
Btw we will need to add some visual demos on using these tools.

**Comment by mathpluscode** [comment]
mark this issue as post-r1, will create a new issue for warping image

**Comment by mathpluscode** [comment]
@YipengHu I suggest to close this issue and create new issues for each specific CLI tools if we want.
