### ISSUE TITLE
Tests: Enable to use GPU for pytest.

### ISSUE THREAD

**Issue by mathpluscode** [DeepRegNet/DeepReg#187]
# Issue description

Currently, when doing pytest, we do not use GPU by default even it's available.

So it will be better if we are able to switch to use GPU.

## Type of Issue

- [ ] New feature request
- [ ] Documentation update
- [ ] Test request

**Comment by NMontanaBrown** [comment]
The unit tests are not designed to use GPU, they are not doing graph operations that require GPUs. CPU operations for unit tests should port to GPU as far as I understand...?
GPU would be useful for the not unit tests/SIT - ie the tests that assert that the tools train and would reduce CI from 30 mins down. If it's a speed problem, it's not really a problem - all the unit tests run in about 7 seconds.
As far as I'm aware, TravisCI does not offer GPU support either, so not sure how we would implement this. either.

**Comment by mathpluscode** [comment]
Oh if the unit tests are not designed to use GPU. Then fine. But we still need to set the pytest such that, either we do not use GPU at all (in case the machine has GPU) or we use GPU.

In other words, depending on how we run pytest, like `pytest test/`, `pytest test/unit`, `pytest test/unit/xxx.py`, we need to ensure we import the tensorflow and set the global env var in the same way.

**Comment by NMontanaBrown** [comment]
Ok here is how to pass custom args to tests with pytest:

https://docs.pytest.org/en/5.4.3/example/simple.html?highlight=command%20line#pass-different-values-to-a-test-function-depending-on-command-line-options

So this will require some test refactoring and modifying instructions on how to call pytest.
Items:
- [ ] Create CL mods for pytest like in link
- [ ] Modify tests
- [ ] Improve docs such that "how to" on GPU testing accessible to team, users, contributors.

**Comment by YipengHu** [comment]
@mathpluscode @NMontanaBrown - shall mark this post-r1?

**Comment by mathpluscode** [comment]
Close this issue as with #443, the pytest w/o GPU will both work. However, the test with GPU is not covered as we do not have CI deployed on GPU.
