### ISSUE TITLE
Bug: test_sample_index_generator, test failed

### ISSUE THREAD

**Issue by mathpluscode** [DeepRegNet/DeepReg#189]
# Issue description

In master branch the CI failed:

https://travis-ci.org/github/DeepRegNet/DeepReg/jobs/709651339

It also appeared in https://github.com/DeepRegNet/DeepReg/pull/168

@acasamitjana 

## Type of Issue

- [ ] Bug report
- [ ] Test request

#### For bug report or feature request, steps to reproduce the issue, including (but not limited to):

1. travis ci

#### What's the expected result?

The test should pass.

#### What's the actual result?

It failed in `test_sample_index_generator`.

Actually, maybe we should test, using different seed, the indices are different, instead of saying, two continuous epochs have different indices?

**Comment by acasamitjana** [comment]
I agree to change the test (it's more specific hence better). 
But I don't get why the CI failed. Should we still test seed=None as it's the value passed in get_data_loader?

**Comment by mathpluscode** [comment]
@acasamitjana, I don't know why exactly the CI failed, but as we are giving seed=None, so it is not deterministic (which is not ideal for testing), so it's hard to understand why.

For testing, we don't have to pass None, as the objective of that specific test is to verify that

"different seeds generate different order".

And could you please review the corresponding PR?

https://github.com/DeepRegNet/DeepReg/pull/190
