### ISSUE TITLE
Mutual information loss

### ISSUE THREAD

**Issue by ucl-candi** [DeepRegNet/DeepReg#20]
Adding (normalised) mutual information as an image dissimilarity loss

**Comment by mathpluscode** [comment]
@YipengHu @QianyeYang do we want to do this before release r1?

**Comment by YipengHu** [comment]
yes - i think this is already in the doc and Qianye has been halfway there i beleive.

**Comment by YipengHu** [comment]
@QianyeYang do you need any help with this?

**Comment by mathpluscode** [comment]
has been solved in https://github.com/DeepRegNet/DeepReg/pull/272
