### ISSUE TITLE
Typo errors in documentation

### ISSUE THREAD

**Issue by ebonmati** [DeepRegNet/DeepReg#205]
# Issue description
preppare (tutorial_demo) --> prepare
Currently, DeepReg currently (doc_data_loader) --> DeepReg currently

## Type of Issue
Typo error

Please delete options that are not relevant.

- [ ] Bug report
- [ ] New feature request
- [X] Documentation update
- [ ] Test request
- [ ] Linting request

#### For bug report or feature request, steps to reproduce the issue, including (but not limited to):

1. OS
2. Environment to reproduce
3. What commands run / sample script used:

**Comment by YipengHu** [comment]
@ebonmati Thanks! I have created a new label proofread, so we can group some of these typing errors together and maybe address them in batches ;)
