### ISSUE TITLE
Missing link to doc page

### ISSUE THREAD

**Issue by mathpluscode** [DeepRegNet/DeepReg#211]
# Issue description

In the readme of the DeepReg, there is no link directing user to the page of docs.

As all the docs are in the page, it is important to provide an obvious link to it.

## Type of Issue

- [ ] Bug report

**Comment by NMontanaBrown** [comment]
Can issue #210 be fixed with this too?

**Comment by mathpluscode** [comment]
ok, i can fix it during the weekend @NMontanaBrown

**Comment by YipengHu** [comment]
I'm bundling this in #225
