### ISSUE TITLE
Loss parameters

### ISSUE THREAD

**Issue by acasamitjana** [DeepRegNet/DeepReg#215]
# Issue description

## Type of Issue
There are several losses that may use some parameters: e.g., type or size of kernel in LNCC. Allow the config file to parse these parameters  and use them in the loss function

Please delete options that are not relevant.

- [ ] Bug report
- [X] New feature request
- [ ] Documentation update
- [ ] Test request
- [ ] Linting request

#### Additional details / screenshot
Best is to leave those parameters as optional so the standard user do not want to change it

**Comment by mathpluscode** [comment]
@acasamitjana with the PR #220 I allowed extra params to be passed in via `kwargs`. I hope this could facilitate your work for this issue.

**Comment by acasamitjana** [comment]
### LNCC loss

- Kernel size: add keyword to config file 
- Kernel type: add keyword to config file and implement different kernels:
    - Constant: tf.ones()
    - Linear: conv(tf.ones(), tf.ones())
    - Gauss: formula with sigma=kernel_size/3.

**Comment by acasamitjana** [comment]
Trying to run the unit testing I found an "Aborted (core dumped)" error. I'm not sure why is it caused. 
If I commented out either the LNCC or the GMI then it works. I'll look closely on that, but please let me know if anyone finds the bug. You can check the corresponding branch (215-loss-parameters)

**Comment by mathpluscode** [comment]
> Trying to run the unit testing I found an "Aborted (core dumped)" error. I'm not sure why is it caused.
> If I commented out either the LNCC or the GMI then it works. I'll look closely on that, but please let me know if anyone finds the bug. You can check the corresponding branch (215-loss-parameters)

Hi @acasamitjana can you share a log history or something we can reproduce the bug ;) I'm happy to help.

**Comment by acasamitjana** [comment]
Hi @mathpluscode, I'm sure it was some local problems with GPU since I was running other code. Now it smoothly runs all tests, the previous ones and the ones I've added. I believe that regarding documentation, an update on the docstring would be enough. I'll submit a PR
