### ISSUE TITLE
Generate warning to check path if the path in config is not specified in an acceptable format

### ISSUE THREAD

**Issue by s-sd** [DeepRegNet/DeepReg#216]
# Issue description

When the paths are not correctly specified, tensorflow gives an error "UnboundLocalError: local variable 'logs' referenced before assignment". This is not very informative, so maybe we can generate a warning or error if the paths in the config file are not either full paths or are not reachable.

## Type of Issue

- [x] Documentation update

#### What's the expected result?

Raise a warning when the paths are not specified in the correct format

**Comment by s-sd** [comment]
Minimum steps to reproduce:
1) change dataset -> dir -> train in paired_nifti.yaml from "data/test/nifti/paired/train" to "/data/test/nifti/paired/train". 
2) run the output test: test_paired_labeled_ddf

**Comment by mathpluscode** [comment]
This is related to https://github.com/tensorflow/tensorflow/issues/38064#issuecomment-654717847,

so my guess is the data path is wrong, then the dataset is empty, will debug further
