### ISSUE TITLE
Change from DeepReg version to commit id in README of ct_lung demos

### ISSUE THREAD

**Issue by s-sd** [DeepRegNet/DeepReg#217]
# Issue description

## Type of Issue

- [x] Documentation update

#### What's the expected result?

README contains commit id instead of DeepReg version

**Comment by mathpluscode** [comment]
Btw for this demo, i've corrected your config via PR https://github.com/DeepRegNet/DeepReg/pull/213

Please have a second look to make sure my changes are ok.
