### ISSUE TITLE
Add prerequisites in demos

### ISSUE THREAD

**Issue by ebonmati** [DeepRegNet/DeepReg#223]
# Issue description

It would be nice to have a prerequisites section at the beginning of the README for each demo with some sort of standard message saying that DeepReg is required to run the demo. 

## Type of Issue

Please delete options that are not relevant.

- [ ] Bug report
- [X] New feature request
- [X] Documentation update
- [ ] Test request
- [ ] Linting request

#### For bug report or feature request, steps to reproduce the issue, including (but not limited to):

1. OS
2. Environment to reproduce
3. What commands run / sample script used:

**Comment by YipengHu** [comment]
Hey @ebonmati can you suggest one please?

**Comment by ebonmati** [comment]
Will do! @YipengHu

**Comment by YipengHu** [comment]
i'm closing this as it has now been added to the demo requirement. #252
