### ISSUE TITLE
Wrong message when labels and images names do not match

### ISSUE THREAD

**Issue by ebonmati** [DeepRegNet/DeepReg#228]
# Issue description

If the names of the images and the labels do not match (e.g., image0001.nii.gz and label0001.nii.gz) the following Tensorflow error is raised:

"WARNING:tensorflow:Your input ran out of data; interrupting training. Make sure that your dataset or generator can generate at least `steps_per_epoch * epochs` batches (in this case, 2 batches)."

This is very confusing as one would think that the problem is with the quantity of images instead of the file names.

Could a better error message be shown to point to the documentation?

## Type of Issue

Please delete options that are not relevant.

- [ ] Bug report
- [X] New feature request
- [ ] Documentation update
- [ ] Test request
- [ ] Linting request

#### For bug report or feature request, steps to reproduce the issue, including (but not limited to):

1. OS
2. Environment to reproduce
3. What commands run / sample script used:

#### What's the expected result?

Could a better error message be shown to point to the documentation?

#### What's the actual result?

"WARNING:tensorflow:Your input ran out of data; interrupting training. Make sure that your dataset or generator can generate at least `steps_per_epoch * epochs` batches (in this case, 2 batches)."

**Comment by YipengHu** [comment]
@ebonmati @ebonmati  are you addressing this? please assign yourself to this ticket

**Comment by mathpluscode** [comment]
@YipengHu later i can handle this

**Comment by mathpluscode** [comment]
I believe this bug no longer exists.

After modifying the file name of the working example on paired labeled nifti data, the following error occurs:

```
E           ValueError: two lists are not identical
E           list1 has unique elements [('data/test/nifti/paired/train', 'case000000')]
E           list2 has unique elements [('data/test/nifti/paired/train', 'case000000wrong')]
```

Howwever, maybe it would be better to tell it's moving / fixed images having problems

**Comment by mathpluscode** [comment]
```
E           ValueError: moving images and labels in paired loader are not identical
E           difference are [(('data/test/nifti/paired/train', 'case000000'), ('data/test/nifti/paired/train', 'case000000wrong'))]
```

This error message should be more meaningful now
