### ISSUE TITLE
UnboundLocalError: local variable 'logs' referenced before assignment

### ISSUE THREAD

**Issue by ebonmati** [DeepRegNet/DeepReg#229]
# Issue description

When ticked #228 happens, the following error is also triggered:
"UnboundLocalError: local variable 'logs' referenced before assignment"

This error may also be triggered if the generator runs out of data before the end of the epoch.

## Type of Issue

Please delete options that are not relevant.

- [X] Bug report
- [ ] New feature request
- [ ] Documentation update
- [ ] Test request
- [ ] Linting request

#### For bug report or feature request, steps to reproduce the issue, including (but not limited to):

1. OS
Ubuntu
2. Environment to reproduce
3. What commands run / sample script used:

#### What's the expected result?

No error with the logs

#### What's the actual result?

"UnboundLocalError: local variable 'logs' referenced before assignment"

**Comment by mathpluscode** [comment]
This issue is duplicated to #216, and it should be solved by PR #227 
@ebonmati if you confirm, plz close this issue thx ;)
