### ISSUE TITLE
Nifti data as .nii (instead of .nii.gz) is not accepted

### ISSUE THREAD

**Issue by ebonmati** [DeepRegNet/DeepReg#230]
# Issue description

Nifti input data as .nii is not accepted, it only accepts .nii.gz.

## Type of Issue

Please delete options that are not relevant.

- [X] Bug report
- [x] New feature request
- [x] Documentation update
- [x] Test request
- [ ] Linting request

#### For bug report or feature request, steps to reproduce the issue, including (but not limited to):

1. OS
Ubuntu
2. Environment to reproduce
3. What commands run / sample script used:

#### What's the expected result?

Accept .nii data as input

**Comment by mathpluscode** [comment]
This issue will need to extend `nifti_loader.py`, we now have the following code

```
arr = np.asarray(nib.load(filepath).dataobj, dtype=np.float32)
```

So we will need a helper function to load the data depending on the suffix of the path.
```
if file_path.endswith("nii"):
    # load nii
elif file_path.endswith("nii.gz"):
    # load nii.gz
else:
    # raise error and provide the full path for debugging
```

The test is also required to test all cases including failures, so you might need at least one `.nii` file in the repo

**Comment by YipengHu** [comment]
> nib.load

it should be tested fairly easily, but i thought ni.load() reads both?
see: https://nipy.org/nibabel/reference/nibabel.html

**Comment by s-sd** [comment]
@YipengHu @mathpluscode I suspect the problem is in lines 17-19 of the nifti_loader.py:

```
        self.file_paths = get_sorted_filenames_in_dir(
            dir_path=os.path.join(dir_path, name), suffix="nii.gz"
        )
```
Only files with suffix "nii.gz" are being added to self.file_paths

**Comment by YipengHu** [comment]
> @YipengHu @mathpluscode I suspect the problem is in lines 17-19 of the `nifti_loader.py`:
> 
> ```
>         self.file_paths = get_sorted_filenames_in_dir(
>             dir_path=os.path.join(dir_path, name), suffix="nii.gz"
>         )
> ```
> 
> Only files with suffix "nii.gz" are being added to self.file_paths

I might be it. Will test this out later. But if you are up for it, fix this I will review.

**Comment by s-sd** [comment]
@YipengHu, I'll try to make the change and if it works I'll create a pull request

**Comment by mathpluscode** [comment]
revert is as mentioned in #240

**Comment by YipengHu** [comment]
@mathpluscode are you assigning yourself to this, or you want @s-sd to add test et al?

**Comment by mathpluscode** [comment]
no after the discussion with @s-sd he will focus on the demo first, i will do this
