### ISSUE TITLE
Typo error in message regarding the number of labels 

### ISSUE THREAD

**Issue by ebonmati** [DeepRegNet/DeepReg#234]
# Issue description

The following message has a typo error (see bold): 

"ValueError: Sample [1, 18]'s moving image and fixed image have different numbers of **labels.moving**: 13, fixed: 12"

It is located in lines 368-369 in commit 525bcd3.

## Type of Issue

Please delete options that are not relevant.

- [X] Bug report
- [ ] New feature request
- [ ] Documentation update
- [ ] Test request
- [ ] Linting request

#### For bug report or feature request, steps to reproduce the issue, including (but not limited to):

1. OS
2. Environment to reproduce
3. What commands run / sample script used:

**Comment by mathpluscode** [comment]
Besides the typo, we should use the minimum labels by default to make the code more robust, and raise an warning.

**Comment by mathpluscode** [comment]
@YipengHu if moving image gave 5 labels, and fixed image gave 4 labels, what should we do? ERROR  or Warning and use the minimum of two ?

**Comment by YipengHu** [comment]
> @YipengHu if moving image gave 5 labels, and fixed image gave 4 labels, what should we do? ERROR or Warning and use the minimum of two ?

Error. Too many options for any reasonable default.

**Comment by YipengHu** [comment]
> @YipengHu if moving image gave 5 labels, and fixed image gave 4 labels, what should we do? ERROR or Warning and use the minimum of two ?

missed you second question - why minimum two, one is perfectly fine for labels.

**Comment by mathpluscode** [comment]
> > @YipengHu if moving image gave 5 labels, and fixed image gave 4 labels, what should we do? ERROR or Warning and use the minimum of two ?
> 
> missed you second question - why minimum two, one is perfectly fine for labels.

I was saying if moving image gave 5 labels, fixed image gave 4, then we took the first 4 labels.

Fine, as we decided for the error option, will solve this typo error in another PR together
