### ISSUE TITLE
Access to DeepReg Model Zoo

### ISSUE THREAD

**Issue by YipengHu** [DeepRegNet/DeepReg#236]
# Issue description

Give access to all the demo makers to https://github.com/DeepRegNet/deepreg-model-zoo

## Type of Issue

The model zoo is a place to store trained networks, i.e. ckpt files, for all the demos. If possible, use a single file (or multiple archived files) so downloading would be efficient without affecting other models/data on the repo.

It is also possible to be used for (re-)host data.

@NMontanaBrown @mathpluscode @acasamitjana @ebonmati @QianyeYang @s-sd 

Please tag those whom are missed in the list.

**Comment by mathpluscode** [comment]
Are we sure that we can upload large files?

**Comment by YipengHu** [comment]
> Are we sure that we can upload large files?

Actually data probably not a good idea - an item for thurs - you can split the achieved files

**Comment by DeepRegNet** [comment]
I have done this so close this issue now.

**Comment by YipengHu** [comment]
done this closing now.
