### ISSUE TITLE
Demo - MR Brain (learn2reg t4)

### ISSUE THREAD

**Issue by YipengHu** [DeepRegNet/DeepReg#24]
Inter-subject neural image registration
data: https://drive.google.com/drive/folders/1Plum9c41tHPmA84-L0K0RrIztictFuNg

This demo tests:
1 - unsupervised inter-subject
2 - weakly supervised inter-subject
3 - unsupervised inter-subject with weak supervision

**Comment by YipengHu** [comment]
@acasamitjana This might be a good time for our first demo!
The unpaired loader is ready (I'm sure there will be changes/updates), but hopefully, all will be easier to adapt later on.
See some doc on data loader and sampling here:
https://github.com/ucl-candi/DeepReg/issues/37
https://github.com/ucl-candi/DeepReg/blob/56-doc-data-sampling/tutorials/sampling.md

**Comment by acasamitjana** [comment]
I have an preliminary demo with 2 images that is working. I now need to train it using the full dataset. I have used the train.py and predict.py as base example. 

Now, I have several doubts/comments:

1.- Is anyone using DVF model? I noticed differences in the coding style and some bug compared to DDF model. I can adapt it to the same style and make a PR.
2.- I'm not sure it is good to allow resizing of the input and output images in the network to the fixed_image shape. You could change the resolution making it harder to register. Instead, it may be addressed by preprocessing (e.g: rigid registration with resampling at the fixed_image shape).
3.- The images from the dataset are padded with the "border" option to make it the same size. It can be good to compute the similarity metric only within the "true" image. What do you think? In this case, we should allow to load masks as well.
4.- I haven't seen any specific issue for nearest interpolation. Is someone implementing that?

**Comment by YipengHu** [comment]
@acasamitjana 
Good points!
1 - please do. We have not had an application for using dvf yet, it would be great to have your demo as an example for it! Better to make a separate issue for it;
2 - This is a much bigger topic. We had thought about to change the entire thing to accept anisotropic images, but it may be best to revisit after first release. The data loaders, deformation regularisation etc all need to adapt. In terms of rigid registration, did you mean as part of the learning algorithms or a standalone pairwise registration? 
    - If former, it is easy to add a new network, such as CompositeNet in https://github.com/YipengHu/label-reg/blob/master/labelreg/networks.py. Feel free to add an issue for this too;
    - if latter, making this "default" would not be ideal perhaps outside of neuralimaging, and we also discussed to postpone all potential pre-processing methods after first release in July. Let's get some feedback and revisit again?
3 - It is a good idea. However, i have personally never seen this is an issue as the contribution to the gradient would be so small. Is it true? If not, the simplest for now is to allow a "boarder mask" option for all. Let us know you experience. 
4 - Who is using nearest interpolation? If there is a user case, it is easy to implement. We however have an issue discussing higher order interpolation #26 - any thoughts on that?

**Comment by acasamitjana** [comment]
1.- OK, I'll do it.
2.- I like the idea of CompositeNet, I don't need it for now but we can include it afterwards -- let's talk it later on. 
3.- You are right about the small influence of the gradient if the background is more or less homogeneous. I can actually mask the images offline and use them as inputs. (Thanks I didn't think about it earlier!)
4.- Ok, I will implemented as I wanted to use labels in the training.

**Comment by YipengHu** [comment]
@acasamitjana do you need any help with this? please read the latest demo requirement in wiki.

**Comment by acasamitjana** [comment]
@YipengHu I need to upload my pretrained model into deepreg-zoo. Can you make me contributor?

**Comment by YipengHu** [comment]
> @YipengHu I need to upload my pretrained model into deepreg-zoo. Can you make me contributor?

I have. Did you not get the invite? Try again later.
