### ISSUE TITLE
Simplify and define content for README.md

### ISSUE THREAD

**Issue by zacbaum** [DeepRegNet/DeepReg#246]
# Issue description

Currently, the website and README.md are, effectively, copies of one another. This is difficult to maintain, and likely the website should be the main source of information. We will reduce the content on the README, so likely will just have the status indicators, and some of the core text (contribs, etc. will be removed).

Eventually, this should have one or two images, a brief description, a link to deepreg.net, and a citation/link to the associated paper.

## Type of Issue

- [x] Documentation update

**Comment by zacbaum** [comment]
@YipengHu @mathpluscode @NMontanaBrown - Let me know if you have any comments or suggestions on what's there in this branch - check it out [here](https://github.com/DeepRegNet/DeepReg/blob/246-readme-simplification/README.md).

**Comment by YipengHu** [comment]
TensorFlow...

**Comment by mathpluscode** [comment]
LGTM ;)
