### ISSUE TITLE
Bug when using multiple test folders

### ISSUE THREAD

**Issue by YipengHu** [DeepRegNet/DeepReg#251]
# Issue description

Incorrect error when using multiple folder data in testing with paired dataset loader.

## Type of Issue

Please delete options that are not relevant.

- [ ] Bug report
- [ ] Test request

#### For bug report or feature request, steps to reproduce the issue, including (but not limited to):

1. OS
2. Environment to reproduce
3. What commands run / sample script used:

on branch 12, run the demo, when using the predict (see readme)

Traceback (most recent call last):
  File "/home/yipenghu/miniconda3/envs/deepreg/bin/predict", line 33, in <module>
    sys.exit(load_entry_point('deepreg', 'console_scripts', 'predict')())
  File "/home/yipenghu/git/DeepReg/deepreg/predict.py", line 352, in main
    args.config_path,
  File "/home/yipenghu/git/DeepReg/deepreg/predict.py", line 264, in predict
    save_dir=log_dir + "/test",
  File "/home/yipenghu/git/DeepReg/deepreg/predict.py", line 136, in predict_on_dataset
    "Sample is repeated, maybe the dataset has been repeated."
ValueError: Sample is repeated, maybe the dataset has been repeated.

**Comment by mathpluscode** [comment]
so the reason is that:

we only check for each folder, the id of images (indexes) are unique, but we didn't check across multiple folders, therefore, we need to add one more index for all data loaders to indicate the folder.

**Comment by YipengHu** [comment]
> so the reason is that:
> 
> we only check for each folder, the id of images (indexes) are unique, but we didn't check across multiple folders, therefore, we need to add one more index for all data loaders to indicate the folder.

is it better to just accumulate one single index?

**Comment by mathpluscode** [comment]
> > so the reason is that:
> > we only check for each folder, the id of images (indexes) are unique, but we didn't check across multiple folders, therefore, we need to add one more index for all data loaders to indicate the folder.
> 
> is it better to just accumulate one single index? if no particular reason, i guess either is fine.

What do you mean accumulate, for instance, with grouped data, the ID of a pair is
- moving group index
- moving image index
- fixed group index
- fixed image index
- label index

it will be hard to increase the number on one of them

**Comment by mathpluscode** [comment]
ooops, this bug might be a bit more complicated,

if the training dataset has multiple folders, then for grouped data or unpaired data, we should mix between folders,
but for now one dataset is created per folder, and then concatenated together

need to think a bit more about this
