### ISSUE TITLE
Improve the predict output file options

### ISSUE THREAD

**Issue by YipengHu** [DeepRegNet/DeepReg#255]
# Issue description

Currently, `predict/deepreg_predict` saves input images/labels for different label pairs, with both png and nifti file formats. This leads to sizable written files.

1 - Add options that can turn off the following for space-saving/speed:
- Save input images/labels (useful for debugging or research);
- Save png files
- Save nifti files (is this useful to be able to turn off?)

2 - Avoid saving the same input files multiple times.

## Type of Issue

- [ ] New feature request
- [ ] Documentation update
- [ ] Test request

**Comment by mathpluscode** [comment]
so ideally, the output should be like following (this has been discussed before lol)

- one folder per image pair (not related to label)
  - input images
  - one subfolder per label
    - input label
    - outputs

then for the following items we can choose to save or not
- input images/labels, default false
- png, default false
- nifti, default true

**Comment by mathpluscode** [comment]
also, issue #251 should be fixed first

**Comment by NMontanaBrown** [comment]
Also, I was reviewing this for the edu challenge and at this [line](https://github.com/DeepRegNet/DeepReg/blob/048cfb04502969ce12cdaacb8123d58a8df65951/deepreg/predict.py#L88) we call:
``` python
# predict
 # (batch, f_dim1, f_dim2, f_dim3)
        pred_fixed_label = outputs_dict.get("pred_fixed_label", None)
        pred_fixed_image = (
            layer_util.resample(vol=moving_image, loc=fixed_grid_ref + ddf)
            if ddf is not None
            else None
        )
```

Which I found quite confusing: the warped image is called pred_fixed_image, which I associated to the fixed image. I would suggest renaming this and the save file for clarity to warped_moving_image, or something along the lines?

@YipengHu @mathpluscode @s-sd

**Comment by YipengHu** [comment]
> Also, I was reviewing this for the edu challenge and at this [line](https://github.com/DeepRegNet/DeepReg/blob/048cfb04502969ce12cdaacb8123d58a8df65951/deepreg/predict.py#L88) we call:
> ``` python
> # predict
>  # (batch, f_dim1, f_dim2, f_dim3)
>         pred_fixed_label = outputs_dict.get("pred_fixed_label", None)
>         pred_fixed_image = (
>             layer_util.resample(vol=moving_image, loc=fixed_grid_ref + ddf)
>             if ddf is not None
>             else None
>         )
> ```
> 
> Which I found quite confusing: the warped image is called pred_fixed_image, which I associated to the fixed image. I would suggest renaming this and the save file for clarity to warped_moving_image, or something along the lines?
> 
> @YipengHu @mathpluscode @s-sd 

We discussed this change earlier. It means predicted image in fixed image space. @mathpluscode had a point in other non-spatial transform supported methods, such as conditional seg. Warp may be confusing... I did not contest too much. But now if it is confusing to others. I suggest to change it back to warped_moving_image/label too.

**Comment by mathpluscode** [comment]
@NMontanaBrown @YipengHu  why pred_fixed_image is confusing?

With predicted DDF, we warp the moving image to be a "fixed image", so this warped image is a prediction of the fixed image? 
and when we construct losses, we are building loss between fixed_image and pred_fixed_image.

In the future, we might use GAN to produce the prediction for image / label, and even with the conditional network, the "warped fixed label" is no longer warped but a direct output of the network. So I do not recommend to change the name, tho we can improve the documentation.

**Comment by YipengHu** [comment]
> @NMontanaBrown @YipengHu why pred_fixed_image is confusing?
> 
> With predicted DDF, we warp the moving image to be a "fixed image", so this warped image is a prediction of the fixed image?
> and when we construct losses, we are building loss between fixed_image and pred_fixed_image.
> 
> In the future, we might use GAN to produce the prediction for image / label, and even with the conditional network, the "warped fixed label" is no longer warped but a direct output of the network. So I do not recommend to change the name, tho we can improve the documentation.

I'm not helping here - but to be fair i've seen both before.
