### ISSUE TITLE
Update contributing to provide examples of testing

### ISSUE THREAD

**Issue by mathpluscode** [DeepRegNet/DeepReg#259]
# Issue description

We need to update the contributing to provide more guidelines for adding tests, so that we can uniform the code style.
For each point, better to link to some existing test in the current code base to provide more detailed examples.

## test style

we are using pytest, not unittest, as they are quite different, it's important to underline this

## test inputs/outputs
- for funtions with tensorflow tensors, need to check input/output shapes of the tensors, including `len(x.shape)` or compare shape between tensors
- for normal functions, it's good to test input types, but might not be mandatory, depending on the existing assertions inside the function

## test errors

for `raise ValueError`, we need to check the error message using 
```python
with pytest.raises(ValueError) as err_info:
    # some code to trigger the error
assert "desired error message" in str(err_info.value)
```

here the `assert` check is not inside of `with`

for `assert`, if there is an error message, like `assert N==1, "N must be 1"` we need to check the error message using 
```python
with pytest.raises(AssertionError) as err_info:
    # some code to trigger the error
assert "N must be 1" in str(err_info.value)
```

for `assert`, if there is no error message, we still have to define the error type, same for 'NotImplementedError`
```python
with pytest.raises(AssertionError):
    # some code to trigger the error
```

each error should be tested separately, putting assert checks inside `with` is dangerous as the code will break with the first error
```python
with pytest.raises(AssertionError):
    # some code to trigger the error 1
    # some code to trigger the error 2, if error 1 is triggered, error 2 will never be triggered
```

we should prevent using `with pytest.raises(Exception):` as this catches all errors

@NMontanaBrown @YipengHu 

## Type of Issue

- [ ] Documentation update

**Comment by NMontanaBrown** [comment]
Adding: for layers, more maths (vs io) operations, need to check that they do the correct thing!

**Comment by mathpluscode** [comment]
what do you mean "check error raised prior to checking the message"? @NMontanaBrown

**Comment by NMontanaBrown** [comment]
So upon re-reading this guide I think you mentioned it: 

```python
with pytest.raises(AssertionError):
    # some code to trigger the error
```

But ideally before message check do:
```python
with pytest.raises(AssertionError):
    # some code to trigger the error
```
then
```python
with pytest.raises(AssertionError):
    assert "N must be 1" in str(err_info.value)
```

**Comment by mathpluscode** [comment]
oh @NMontanaBrown 

if you do like

```
with pytest.raises(AssertionError) as err_info:
    # some code to trigger the error

assert "N must be 1" in str(err_info.value)
```

so only AssertionError will be capture, if it raise different error, the test will fail
then once you got the corrected error, you can check the error message

in my previous demo above, I put wrong indents so the `assert` was inside `with`, it should be outside actually
