### ISSUE TITLE
Porting the niftyreg 3d resampler

### ISSUE THREAD

**Issue by YipengHu** [DeepRegNet/DeepReg#26]
Discuss the feasibility and pros/cons for using the higher-order and potentially faster and memory-saving resampler:
https://github.com/NifTK/NiftyNet/tree/dev/niftynet/contrib/niftyreg_image_resampling

Please comment below.

**Comment by mathpluscode** [comment]
@YipengHu do we pursue this issue? It seems to involve cuda coding and do we have anyone capable of maintaining this? As tf2.4 is going to use CUDA11.

**Comment by YipengHu** [comment]
closing it now.
