### ISSUE TITLE
Visually dissimilar outputs from warp and predict

### ISSUE THREAD

**Issue by s-sd** [DeepRegNet/DeepReg#262]
## Description

Warp produces a visually dissimilar output to the pngs that are saved. Not sure if this is due to saving it as png bt might be worth looking into. After looking into it, the differences in pixel values are as large as 0.007 for some of the highest differences between the images. 

## Type of Issue

- [x] Bug report

#### For bug report or feature request, steps to reproduce the issue, including (but not limited to):

Was encountered in a copy of the edu challenge notebook (this is not the original edu challenge notebook). Which can be accessed using the link below. The screenshot is also attached. 

#### Additional details / screenshot

The notebook to reproduce is:
https://colab.research.google.com/drive/1Yn8_rsA80Tyk1i3f85r79fhuiJQYslek?usp=sharing
Note: to reproduce, please run the setup blocks and the first six blocks of "Medical Image registration using an adapted DeepReg Demo"

![Screenshot from 2020-08-06 12-16-04](https://user-images.githubusercontent.com/48014558/89528179-88726300-d7e2-11ea-907f-94ce8c2342a6.png)

The following are plotted:
pred_fixed_image (warp)         moving_image (nii.gz)
pred_fixed_image (pred png)   moving_image (png)

**Comment by s-sd** [comment]
@NMontanaBrown @mathpluscode, I encountered this when exploring the warp and predict. Not sure if the small differences are due to saving as png

**Comment by mathpluscode** [comment]
@s-sd the saving function is in https://github.com/DeepRegNet/DeepReg/blob/048cfb04502969ce12cdaacb8123d58a8df65951/deepreg/util.py#L88

I would say it's just because of the png saving? when you say the difference is 0.007, is it in a scale between [0, 1]?

**Comment by s-sd** [comment]
@mathpluscode, yes the scale is [0, 1]. I think it might be due to saving as a png so I'll close this issue then. Thank you for taking a look!
