### ISSUE TITLE
Demo: MICCAI Edu Challenge link broken on README.md

### ISSUE THREAD

**Issue by NMontanaBrown** [DeepRegNet/DeepReg#266]
# Issue description

The links on the README point to the wrong file (as I renamed the file for the typo). Does the colab version point to someone's gdrive in particular? @YipengHu 

## Type of Issue

Please delete options that are not relevant.

- [x] Bug report
- [x] Documentation update

**Comment by mathpluscode** [comment]
Just clicked and it's broken for me as well

**Comment by YipengHu** [comment]
> Just clicked and it's broken for me as well

Will fix tonight. No it does not link to any account specifically. You will be asked to login if the user is not.

**Comment by NMontanaBrown** [comment]
@YipengHu @mathpluscode fixed, making a PR, then send, and submit!

**Comment by YipengHu** [comment]
> @YipengHu @mathpluscode fixed, making a PR, then send, and submit!

Nice - i had to compare letter by letter with my finger to find the typo ;)
