### ISSUE TITLE
Improve docs on local_normalized_cross_correlation

### ISSUE THREAD

**Issue by mathpluscode** [DeepRegNet/DeepReg#273]
# Issue description

The current code is not very well written :(
Need to add more comments on shapes, maths.

## Type of Issue
- [ ] Documentation update
- [ ] Test request

**Comment by mathpluscode** [comment]
The loss we are using here is actually local squared zero-normalized cross correlation, if you check the definition of ZNCC in wiki https://en.wikipedia.org/wiki/Cross-correlation

I believe the code is adapted from an implementation from @QianyeYang which was from voxelmorph,
https://github.com/voxelmorph/voxelmorph/blob/legacy/src/losses.py#L28

so is this "squared" ok? btw maybe we should put the link in comment? @YipengHu what do you think

**Comment by YipengHu** [comment]
> The loss we are using here is actually local squared zero-normalized cross correlation, if you check the definition of ZNCC in wiki https://en.wikipedia.org/wiki/Cross-correlation
> 
> I believe the code is adapted from an implementation from @QianyeYang which was from voxelmorph,
> https://github.com/voxelmorph/voxelmorph/blob/legacy/src/losses.py#L28
> 
> so is this "squared" ok? btw maybe we should put the link in comment? @YipengHu what do you think

I think you are right, although not sure this will make a big difference other than numerical/config ones, e.g. weighting. As similar to Dice, you can have both versions with options to use square or not. There may be an argument that one encourages more sparsity (like in L1-norm) and one may be converges faster - but with Adam and other normalisation in between, it is hard to tell for sure...
