### ISSUE TITLE
Test + docs: classical registration toy examples for integration testing purposes

### ISSUE THREAD

**Issue by tvercaut** [DeepRegNet/DeepReg#28]
Such a feature can be a nice simple integration test to ensure for example that the gradients are useable.

A basic toy example could involve translating an image and registering it with itself.

If useful, this quick and dirty notebook could be a source of inspiration:
https://colab.research.google.com/drive/1OmU-jTvWmRRVerc23nsyNz_p8jU3S7wX?usp=sharing

**Comment by YipengHu** [comment]
@tvercaut see: https://github.com/ucl-candi/DeepReg/blob/28-classical-registration/test/sit_classical_registration.py
It looks like working fine. ;)

**Comment by YipengHu** [comment]
@zacbaum can you help with converting the two examples to sit please? let me know if you want them to be merged first, though the branch has just been rebased - so should be no big diff.

**Comment by YipengHu** [comment]
> @zacbaum can you help with converting the two examples to sit please? let me know if you want them to be merged first, though the branch has just been rebased - so should be no big diff.

I've PR anyway ;) please review/approve and you can start a new branch for it.

**Comment by YipengHu** [comment]
@zacbaum @NMontanaBrown if adding SITs is too much for R1, I can convert this to a "special demo". What do you think?

**Comment by NMontanaBrown** [comment]
@YipengHu Let me review the test and get back to you

**Comment by YipengHu** [comment]
> @YipengHu Let me review the test and get back to you

these two are just examples, there are a few others you can add to cover other functions/modules, such as affine registration, registration on labels/features.

**Comment by NMontanaBrown** [comment]
@YipengHu This is cool, but the test works by looking at the plotted output? I think this is easily modifiable. We can incorporate this after unit tests, I will add to timeline if that makes sense?

**Comment by YipengHu** [comment]
Good idea. We have to streamline, if not required by joss, not required for R1. 
And it is a cool idea for sit!

**Comment by YipengHu** [comment]
@NMontanaBrown @zacbaum what's our plan for this? if not before R1, please add post-r1 label.

**Comment by NMontanaBrown** [comment]
Still on track to refactor for R1 @YipengHu !

**Comment by YipengHu** [comment]
@zacbaum @NMontanaBrown 
see #193 we will move some of the code for purpose of one or two demos. we will discuss it again how to make this sit again
- potentially post-r1

**Comment by YipengHu** [comment]
closing this as they have been moved to demos.
