### ISSUE TITLE
Reading predict-generated nifti images

### ISSUE THREAD

**Issue by YipengHu** [DeepRegNet/DeepReg#280]
# Issue description
The nifti images seem producing errors when loaded in medical image viewers.

## Type of Issue
- [ ] Bug report

#### For bug report or feature request, steps to reproduce the issue, including (but not limited to):

1. OS
WSL2

2. Environment to reproduce
#15 

3. What commands run / sample script used:
deepreg_predict in demo readme

#### What's the expected result?
Images should be readable for common viewer software, for now, supporting the following:
https://www.slicer.org/
http://www.itksnap.org/
http://ric.uthscsa.edu/mango/

**Comment by YipengHu** [comment]
@s-sd what did you use to view the nifti images?

**Comment by s-sd** [comment]
@YipengHu I have been using the PNG files instead of the nifti files
