### ISSUE TITLE
Test: test test_utils

### ISSUE THREAD

**Issue by NMontanaBrown** [DeepRegNet/DeepReg#290]
# Issue description

Increase coverage by testing util functions.

## Type of Issue

Please delete options that are not relevant.

- [x] Test request

**Comment by mathpluscode** [comment]
any updates ;) @agrimwood  @NMontanaBrown ?

**Comment by NMontanaBrown** [comment]
We discussed in the meeting moving the function into the test scripts as it's a bit of a recursive issue: we use the functions from DeepReg as part of test utils. The expense is repeating the code in the scripts, for raising the coverage to 100%. But in itself, is a copy-paste job. @mathpluscode @agrimwood
