### ISSUE TITLE
Release: PyPi

### ISSUE THREAD

**Issue by NMontanaBrown** [DeepRegNet/DeepReg#291]
# Issue description

Release package to PyPi.

## Type of Issue

Please delete options that are not relevant.

- [x] New feature request

**Comment by zacbaum** [comment]
A good medium post for high-level details: https://medium.com/@joel.barmettler/how-to-upload-your-python-package-to-pypi-65edc5fe9c56

**Comment by zacbaum** [comment]
@NMontanaBrown @YipengHu @mathpluscode 

A few things will be needed for this (beyond some minor changes in the codebase);

DESCRIPTION
- What text do we want here?

AUTHOR 
- Left as just @mathpluscode, or do we use JOSS author list? Do we use DeepRegNet?

AUTHOR EMAIL
- Use deepregnet@gmail.com?

KEYWORDS
- Which would we like? JOSS paper uses: medical image registration, image fusion, deep learning, neural networks

CLASSIFIERS
- Development Status :: 4 - Beta
- Environment :: Console
- Environment :: GPU
- Environment :: MacOS X
- Environment :: Win32 (MS Windows) **(Not yet?)**
- Intended Audience :: Developers
- Intended Audience :: Education
- Intended Audience :: Science/Research
- License :: OSI Approved :: Apache Software License
- Natural Language :: English
- Operating System :: MacOS :: MacOS X
- Operating System :: Microsoft :: Windows :: Windows 10 **(Not yet?)**
- Operating System :: Unix
- Programming Language :: Python :: 3 **(Do we want to explicitly list any others?)**
- Topic :: Scientific/Engineering :: Artificial Intelligence
- Topic :: Scientific/Engineering :: Medical Science Apps.
- Topic :: Software Development

**Comment by YipengHu** [comment]
- DeepReg is a freely available, community-supported open-source toolkit for research and education in medical image registration using deep learning.
- DeepReg Development Team and Community
- deepregnet@gmail.com 
- use joss keywords
- Other: i would include Windows 64 or AMD64? - the key roadblock is gpu driver etc, nothing to do with deepreg

**Comment by zacbaum** [comment]
Do we want to include all of:
- `data`
- `demos`
- `docs`
- `test`

In the pypi build? Or just core `deepreg` files to be able to run the code?

**Comment by mathpluscode** [comment]
> @NMontanaBrown @YipengHu @mathpluscode
> 
> A few things will be needed for this (beyond some minor changes in the codebase);
> 
> DESCRIPTION
> 
> * What text do we want here?
> 
> AUTHOR
> 
> * Left as just @mathpluscode, or do we use JOSS author list? Do we use DeepRegNet?
> 
> AUTHOR EMAIL
> 
> * Use [deepregnet@gmail.com](mailto:deepregnet@gmail.com)?
> 
> KEYWORDS
> 
> * Which would we like? JOSS paper uses: medical image registration, image fusion, deep learning, neural networks
> 
> CLASSIFIERS
> 
> * Development Status :: 4 - Beta
> * Environment :: Console
> * Environment :: GPU
> * Environment :: MacOS X
> * Environment :: Win32 (MS Windows) **(Not yet?)**
> * Intended Audience :: Developers
> * Intended Audience :: Education
> * Intended Audience :: Science/Research
> * License :: OSI Approved :: Apache Software License
> * Natural Language :: English
> * Operating System :: MacOS :: MacOS X
> * Operating System :: Microsoft :: Windows :: Windows 10 **(Not yet?)**
> * Operating System :: Unix
> * Programming Language :: Python :: 3 **(Do we want to explicitly list any others?)**
> * Topic :: Scientific/Engineering :: Artificial Intelligence
> * Topic :: Scientific/Engineering :: Medical Science Apps.
> * Topic :: Software Development

For the author, I think it's not ok to put only my name, as it's team effort now.
If we are lazy we can put like `DeepReg Dev Team`, otherwise we put the JOSS author list? Both options seem to be ok ;)

**Comment by zacbaum** [comment]
> Do we want to include all of:
> 
> * `data`
> * `demos`
> * `docs`
> * `test`
> 
> In the pypi build? Or just core `deepreg` files to be able to run the code?

@YipengHu @mathpluscode @NMontanaBrown - which of these would be req'd? Do we need anything beyond just the codebase in the package?

**Comment by YipengHu** [comment]
> > Do we want to include all of:
> > 
> > * `data`
> > * `demos`
> > * `docs`
> > * `test`
> > 
> > In the pypi build? Or just core `deepreg` files to be able to run the code?
> 
> @YipengHu @mathpluscode @NMontanaBrown - which of these would be req'd? Do we need anything beyond just the codebase in the package?

Correct me if i'm wrong here:
- We still need clone the code for some experimental use, including some of the demos;
- We really just use the three CLI deepreg_* after pip install (as a good replacement for local pip install);
- There is no easy way to view docs included in pypi.

So there is really no reason to include those other than the core files that runs the code - with an exception of the front readme which should also be used in pypi homepage, serving as an entry point.
