### ISSUE TITLE
Demo review and styling

### ISSUE THREAD

**Issue by YipengHu** [DeepRegNet/DeepReg#297]
# Issue description

Reviewing demos, especially those merged before changes in https://github.com/DeepRegNet/DeepReg/blob/master/docs/doc_demo_requirement.md

## Type of Issue

- [ ] Bug report
- [ ] Documentation update

#### What's the expected result?

tag DeepReg with all running demos

**Comment by YipengHu** [comment]
@s-sd I think one of the reasons why the model you were using - therefore difficult to train - is that you are using one of the test yaml files, deepreg/config/test/ddf.yaml
which was intentionally very small network for testing purpose, with initial number of channel being just 1!
I'd recommend copy these together with the yaml file you are using for `dataset` and change the parameters to a sensible range and re-train it. If you can update the model saved in model-zoo then.
Copying @NMontanaBrown @ebonmati for information.

**Comment by YipengHu** [comment]
> @s-sd I think one of the reasons why the model you were using - therefore difficult to train - is that you are using one of the test yaml files, deepreg/config/test/ddf.yaml
> which was intentionally very small network for testing purpose, with initial number of channel being just 1!
> I'd recommend copy these together with the yaml file you are using for `dataset` and change the parameters to a sensible range and re-train it. If you can update the model saved in model-zoo then.
> Copying @NMontanaBrown @ebonmati for information.

@acasamitjana i noticed you have your own network set up, but it is also quite small, do you think that's big enough?

**Comment by s-sd** [comment]
@YipengHu, thank you! I think that must be the reason, I will update the model-zoo when the larger networks are done

**Comment by YipengHu** [comment]
@acasamitjana @ebonmati Strongly recommend: 1) not downloading from google drive directly - there are accessibility issues - you can host (pre-processed or not) data on any github account (or cmiclab / weisslab); Both your demo_data.py files had issues on the cluster and one of my desktops (both Ubuntu)... not sure why really as it worked fine on my laptop with Debian...
Not very very strongly, 2) not using os.system for wget. This depends on the OS and would not work with MacOS and windows directly (though we don;t intend to support either...). tf.keras.utils.get_files may be an option here.
