### ISSUE TITLE
Use separate config file for network for demos

### ISSUE THREAD

**Issue by s-sd** [DeepRegNet/DeepReg#299]
# Issue description

The paired_ct_lung, unpaired_ct_lung and paired_mrus_brain demo use config files given for the test and use a small network. Use separate files for each of these demos and use arger network sizes.

## Type of Issue

- [x] New feature request

#### What's the expected result?

The demos mentioned above use larger networks and separate config files

**Comment by YipengHu** [comment]
@acasamitjana @ebonmati  Strongly recommend: 1) not downloading from google drive directly - there are accessibility issues - you can host (pre-processed or not) data on any github account (or cmiclab / weisslab); Both your demo_data.py files had issues on the cluster and one of my desktops (both Ubuntu)... not sure why really as it worked fine on my laptop with Debian...
Not very very strongly, 2) not using os.system for wget. This depends on the OS and would not work with MacOS and windows directly (though we don;t intend to support either...).  tf.keras.utils.get_files may be an option here.
