### ISSUE TITLE
structure check on YAML configuration file

### ISSUE THREAD

**Issue by mathpluscode** [DeepRegNet/DeepReg#301]
# Issue description

We are using yaml file for configuration.
However, this file has a relatively complicated structure, therefore it is important to validate that the input config file has
satisfies an expected structure.

For now, we are validating it manually using if/else and value error. Or the code will raise KeyError directly. We should find a package and define the desired structure instead.

## Type of Issue

- [ ] New feature request
- [ ] Documentation update
- [ ] Test request
- [ ] Linting request

**Comment by mathpluscode** [comment]
@NMontanaBrown @YipengHu If you know any package can do this ;)

**Comment by YipengHu** [comment]
> @NMontanaBrown @YipengHu If you know any package can do this ;)

not sure - if it is a problem of indentation for instance, the "wrong" file can still be valid. This actually is related to #54

**Comment by mathpluscode** [comment]
According to https://stackoverflow.com/questions/53376099/python-dataclass-from-a-nested-dict, the following code works

```python

from dataclasses import dataclass, asdict, fields


def dataclass_from_dict(klass, d):
    try:
        fieldtypes = {f.name: f.type for f in fields(klass)}
        return klass(**{f: dataclass_from_dict(fieldtypes[f], d[f]) for f in d})
    except:
        return d  # Not a dataclass field


@dataclass
class Point:
    x: float
    y: float


@dataclass
class Line:
    a: Point
    b: Point


line = Line(Point(1, 2), Point(3, 4))
assert line == dataclass_from_dict(Line, asdict(line))

```

So we can declare the structure of configuration as `dataclass` which enables a check on config files.

We can also change the arguments of functions to make the code cleaner. Even though tf functions tend to have LOTS OF arguments as an input instead of a class.

**Comment by YipengHu** [comment]
Please update Eugenio's affiliation: 
CMIC, UCL
Martinos Center for Biomedical Imaging, Massachusetts General Hospital and Harvard Medical School
Computer Science and AI Lab (CSAIL), Massachusetts Institute of Technology

**Comment by YipengHu** [comment]
@mathpluscode can you review this and see if this is still needed?

**Comment by mathpluscode** [comment]
> @mathpluscode can you review this and see if this is still needed?

I'd suggest close it for now and add tag wontfix @YipengHu. For better config handling, we could consider the third party package hydra from Facebook but I need to check that package first.

**Comment by NMontanaBrown** [comment]
Bit late, but wouldn't this be avoided if we had the command line tool that generates the config file, see ticket #54
