### ISSUE TITLE
Organize the layer structure in the models

### ISSUE THREAD

**Issue by mathpluscode** [DeepRegNet/DeepReg#305]
# Issue description

While debugging the U-net i found it impossible to print out the model structure using `tf.keras.utils.plot_model` and the output using `model.summary()` is not very meaningful neither.

There might be many reasons, like
- we didn't use the `tf.name_scope`
- others that I don't know :(

So it's important to improve the code so that at least we can print out the model structure, also the graph in tensorboard should be meaningful as well.

## Type of Issue

- [ ] Bug report
- [ ] New feature request
- [ ] Documentation update
- [ ] Test request

**Comment by YipengHu** [comment]
@mathpluscode please review this ticket and give estimate of time required or maybe come up with a specific plan for this?

**Comment by mathpluscode** [comment]
> @mathpluscode please review this ticket and give estimate of time required or maybe come up with a specific plan for this?

This gonna be for November or December 2020. It requires the finish of demo tests first.

**Comment by YipengHu** [comment]
is there a way to tag some ticket, so it becomes "alive" when another one closes? ;)

**Comment by mathpluscode** [comment]
> is there a way to tag some ticket, so it becomes "alive" when another one closes? ;)

No idea, but maybe we should define different priorities and sue the github features wisely, like `project` `milestone`...

**Comment by mathpluscode** [comment]
This will be linked to model refactoring.

Actually, instead of refactoring the existing model, I'd consider writing new models, like V1, V2, then depreciate old ones.

**Comment by mathpluscode** [comment]
I will close this as it's part of #557.
