### ISSUE TITLE
deepreg.net revamp

### ISSUE THREAD

**Issue by YipengHu** [DeepRegNet/DeepReg#324]
# Issue description

The current use of deepreg.net, redirecting the readthedocs.io, is problematic:
- the sub-pages URL do not show properly;
- the link back to github does not work. 

However, to build the entire documentation under deepreg.net is also not trivial.

Propose: 
A landing page (or a product page) using https://deepregnet.github.io/DeepReg/, redirected by deepreg.net, on which, very brief introduction, features and graphic display (a few images from DeepReg Demos) will be used together with links to Github and RTD.

Please leave your comments below, also assign yourself if some light front-end engineering attracts you.

**Comment by YipengHu** [comment]
@i'm sending you some pictures for the landing page.
![images01](https://user-images.githubusercontent.com/2588157/91103053-773ea880-e662-11ea-9de4-337aea338edb.png)
![images02](https://user-images.githubusercontent.com/2588157/91103055-786fd580-e662-11ea-9162-69921ce99693.png)
![images03](https://user-images.githubusercontent.com/2588157/91103057-79086c00-e662-11ea-87a2-ccc926ce3630.png)
![vis](https://user-images.githubusercontent.com/2588157/91103099-8e7d9600-e662-11ea-9900-dd9cd0703a9e.png)

**Comment by YipengHu** [comment]
cardiac mr:
![image](https://user-images.githubusercontent.com/2588157/91103496-8a05ad00-e663-11ea-9f7f-623835b823b0.png)
![image](https://user-images.githubusercontent.com/2588157/91103518-938f1500-e663-11ea-8af1-414d508f9ac9.png)

**Comment by YipengHu** [comment]
Head and neck:
![image](https://user-images.githubusercontent.com/2588157/91106897-d2c16400-e66b-11ea-8f8c-5792ddfc3632.png)

**Comment by s-sd** [comment]
@YipengHu @zacbaum, Intra-subject lung ct registration
![Screenshot from 2020-08-25 07-51-18](https://user-images.githubusercontent.com/48014558/91141850-f1dde700-e6a7-11ea-9317-0c20d1f383cd.png)

**Comment by YipengHu** [comment]
@s-sd this looks good but better to rotate 90 degree to use normal radiologist view.

**Comment by s-sd** [comment]
@YipengHu @zacbaum, the rotated version of the inter-subject ct lung registration:

![Screenshot from 2020-08-27 13-56-21](https://user-images.githubusercontent.com/48014558/91444911-4da59d00-e86d-11ea-8f20-f92013b48aab.png)

**Comment by YipengHu** [comment]
@s-sd sorry being picky, but usually they put spines on the bottom and the heart on the top ;)

**Comment by s-sd** [comment]
@YipengHu, sorry, corrected it now:

![Screenshot from 2020-08-27 15-29-16](https://user-images.githubusercontent.com/48014558/91455714-594b9080-e87a-11ea-8ad6-434fb6cd4de8.png)

**Comment by zacbaum** [comment]
Initial page available served [here](https://deepregnet.github.io).

Let me know your thoughts or if there's anything else to add. I've made it simple (as requested 😉) - but it still links to the repo, the docs, and has a bit of text and some logos/images to look at.

**Comment by mathpluscode** [comment]
> Initial page available served [here](https://deepregnet.github.io).
> 
> Let me know your thoughts or if there's anything else to add. I've made it simple (as requested ) - but it still links to the repo, the docs, and has a bit of text and some logos/images to look at.

WOW that's quick

Some comments:

- Black ? I personally find this color not very confortable... black & blue is a bit strange to me
- the arrow looks not very nice
- why italic font for the description
- documentation and github button not aligned, style is a bit strange
- why put another logo with diff color on those medical images?

Sorry they might be some strong opinions, the speed of getting this page done is amazing.
I'm just a bit perfectionist on websites. Apologies.

**Comment by YipengHu** [comment]
> > Initial page available served [here](https://deepregnet.github.io).
> > Let me know your thoughts or if there's anything else to add. I've made it simple (as requested ) - but it still links to the repo, the docs, and has a bit of text and some logos/images to look at.
> 
> WOW that's quick
> 
> Some comments:
> 
> * Black ? I personally find this color not very confortable... black & blue is a bit strange to me
> * the arrow looks not very nice
> * why italic font for the description
> * documentation and github button not aligned, style is a bit strange
> * why put another logo with diff color on those medical images?
> 
> Sorry they might be some strong opinions, the speed of getting this page done is amazing.
> I'm just a bit perfectionist on websites. Apologies.
> 
> Btw just wondering how you built this page? Is there any ready-to-use package/template on the internet?

sorry - i'm doing some "experiments" - comments tomorrow please... first-timer-css here...

**Comment by zacbaum** [comment]
> > Initial page available served [here](https://deepregnet.github.io).
> > Let me know your thoughts or if there's anything else to add. I've made it simple (as requested ) - but it still links to the repo, the docs, and has a bit of text and some logos/images to look at.
> 
> WOW that's quick
> 
> Some comments:
> 
> * Black ? I personally find this color not very confortable... black & blue is a bit strange to me
> * the arrow looks not very nice
> * why italic font for the description
> * documentation and github button not aligned, style is a bit strange
> * why put another logo with diff color on those medical images?
> 
> Sorry they might be some strong opinions, the speed of getting this page done is amazing.
> I'm just a bit perfectionist on websites. Apologies.
> 
> Btw just wondering how you built this page? Is there any ready-to-use package/template on the internet?

@YipengHu has made some changes 😉 - this is based on a prebuilt Jekyll template (see repo from which it was forked for samples there as well - may be good for inspiration @YipengHu if you want to keep playing around).

**Comment by mathpluscode** [comment]
# why we wanted deepreg.net

so, the original reason that @YipengHu want deepreg.net was something wrong with readthedocs:

if you go to http://deepreg.net/, and click the github link on top right, there will be errors.

# so how can we use custom domain for docs

actually, the docs should be `docs.deepreg.net` not `deepreg.net`, and I've tried the steps in rtd docs, and it works for my own domain `docs.mcts.xyz`, if you try this, you will go to deepreg docs.

Then this means that we still need a landing page for `deepreg.net`

# should we spend time on the template

Personally, we should not spend too much time on the landing page unless it's someone's hobby and we can make sure it's properly maintained (means more efforts).

I've checked some other template (I forked one and did some commits trying to adapt it, but eventually I deleted that repo :( ), it still required a big effort on customizing things and making things beautiful.

So I think the default templates might be enough for the moment https://pages.github.com/themes/, such that we only write markdown files and do not need to worry about the styles. even https://monai.io/ doesn't have a too complicated website

So I'd suggest choosing one template from these default ones. They are not amazing, but it requires minimal effort on front-end.

What do you think @zacbaum @NMontanaBrown @YipengHu 

Sorry for my comments earlier, I do appreciate all the efforts we have made. I just want to show the best of deepreg to others ;) I believe all the time we spent is worthy, helping us to understand github page, dns records etc. ...

**Comment by DeepRegNet** [comment]
@mathpluscode all good points - i'm marking this post-r1 and revisit later

**Comment by YipengHu** [comment]
as discussed, @zacbaum I think we are go ahead with this?

**Comment by zacbaum** [comment]
@YipengHu let's all discuss (very) high-level content for the page at today's meeting. We will use the Cayman template as discussed but I would like input from everyone as to what should be on this page so that we don't run into issues as occurred last time with content/style.

**Comment by mathpluscode** [comment]
> @YipengHu let's all discuss (very) high-level content for the page at today's meeting. We will use the Cayman template as discussed but I would like input from everyone as to what should be on this page so that we don't run into issues as occurred last time with content/style.

@zacbaum Can we have a draft/list of contents before the discussion so that you can propose something and we quickly discuss and provide more opinions? It can be faster than starting a discussion from an empty list. ^_^

**Comment by zacbaum** [comment]
@mathpluscode - as in ticket description 😉 

> A landing page (or a product page) using https://deepregnet.github.io/DeepReg/, redirected by deepreg.net, on which, very brief introduction, features and graphic display (a few images from DeepReg Demos) will be used together with links to Github and RTD.

Text can be lifted/repurposed from `README.md` - images as above - links consistent/similar to those on `README.md` as well.

**Comment by s-sd** [comment]
@zacbaum, I have made some visualisations (gifs) using the vis tool. There are various visualisation from four demos. The link to access them is:

https://liveuclac-my.sharepoint.com/:u:/g/personal/zcemsus_ucl_ac_uk/EeNqjdkvYphFkvdNfnkKyx8BbFGGcUMQ7SWIvJeEpYh2Ig?e=trzAd8

The files are grouped into folders according to the demo name. The files with names ending with `_slice_N.gif` are the ones which show warping using the DDF. The two files `ct_lung/visualisation.gif` and `vis2.gif` are tiled gifs over the slices with the rows correspnding to [`moving_image`, `fixed_image`] and [`moving_image`, `fixed_image`, `pred_fixed_image`] respectively and the two columns corresponding to image and label. All other file names are just the name of the original file with the `.gif` extension.

**Comment by zacbaum** [comment]
Please go and have a look: https://deepregnet.github.io/

Do **not** make changes to the site, please raise concerns or leave comments here and I will address them.

**Comment by YipengHu** [comment]
Why the first page only occupies the like 2/3 of my screen? is it by-design or just me?

**Comment by zacbaum** [comment]
> Why the first page only occupies the like 2/3 of my screen? is it by-design or just me?

Do you mean the header? (Green/Blue bit) I can make the logo, etc smaller if we would like.

**Comment by YipengHu** [comment]
> > Why the first page only occupies the like 2/3 of my screen? is it by-design or just me?
> 
> Do you mean the header? (Green/Blue bit) I can make the logo, etc smaller if we would like.

yeah - may be making it smaller will do - could be just me...

**Comment by mathpluscode** [comment]
👏 Nice. But the logo might need to be smaller lol

![image](https://user-images.githubusercontent.com/4066929/97306012-bf8e6880-1855-11eb-91f1-a0b8e7fbd97e.png)

**Comment by zacbaum** [comment]
> 👏 Nice.
> 
> "This page created and maintained by DeepReg.Net." is not in the middle at the bottom

Does that by default 😉
Will center it.

> Agree the logo might need to be smaller lol

👍🏼 

> Also do we need twice the logo? I would vote for text only :) It's less risky I'd say.

I've included it twice as technically they're logos for different things (one for DeepReg.Net and the other for DeepReg).

I'll remove the first? Or... Which do we prefer?

**Comment by YipengHu** [comment]
i'm slightly for keeping both logos (not very strongly). maybe make one (the .net) very very small? @zacbaum wait a day or two, everyone will have their opinions. if nothing outstanding (i mean really outstanding), you should make the call.

**Comment by mathpluscode** [comment]
> > 👏 Nice.
> 
> > 
> 
> > "This page created and maintained by DeepReg.Net." is not in the middle at the bottom
> 
> 
> 
> Does that by default 😉
> 
> Will center it.
> 
> 
> 
> > Agree the logo might need to be smaller lol
> 
> 
> 
> 👍🏼 
> 
> 
> 
> > Also do we need twice the logo? I would vote for text only :) It's less risky I'd say.
> 
> 
> 
> I've included it twice as technically they're logos for different things (one for DeepReg.Net and the other for DeepReg).
> 
> 
> 
> I'll remove the first? Or... Which do we prefer?

Emmm I'd say a logo without .net at top? Logo in the middle is strange. Let's see other's opinions 😼

**Comment by zacbaum** [comment]
For now I'll make both logos a bit smaller, and center text at the bottom. Then we can ask for comments at next dev meeting.

**Comment by mathpluscode** [comment]
> For now I'll make both logos a bit smaller, and center text at the bottom. Then we can ask for comments at next dev meeting.

check with phones specially plz lol i think nowadays many traffic are via phones instead of laptops

**Comment by NMontanaBrown** [comment]
Looks nice 👍

**Comment by mathpluscode** [comment]
I'm closing this as deepreg.net is now pointing to the landing page and it's alive now ;)
