### ISSUE TITLE
Improve contributing pages

### ISSUE THREAD

**Issue by mathpluscode** [DeepRegNet/DeepReg#325]
# Issue description

1. Instead of providing a bullet list like in https://deepreg.readthedocs.io/en/latest/contributing/demo.html#readme-md,
we can provide an example md file so that people only need to copy and fill things.

2. add a landing page to give a brief structure on the contributing section.

3. btw remove duplicated logo files

4. integrate the disclaimer better

5. remove all warnings when compiling sphinx

## Type of Issue

- [ ] Documentation update

**Comment by agrimwood** [comment]
Some minor grammatical corrections inbound
