### ISSUE TITLE
Automate test on demos

### ISSUE THREAD

**Issue by mathpluscode** [DeepRegNet/DeepReg#344]
# Issue description

As we are having multiple demos and they are not covered by tests, it would be important for our release/deployment later to make sure that the new version of DeepReg still supports all demos. So that demo no longer needs to specify the last checked commit.

For each demo, we need to at least perform the following steps automatically.
- download and preprocess data
- launch training for 1 epoch
- perform prediction

# TODO

Here are some more to optimize in a later stage
- for demo `paired_ct_lung` and `paired_mrus_brain`
  - Downloaded files for pretrained model contains multiple ckpts, we can simplify to only the last one.
  - Need to refactor data preprocessing script.
  - Question: why using `main_path = os.getcwd()` to change current dir?
- `paired_mrus_brain` the full data download URL not longer works
- `paired_ct_lung` and `unpaired_ct_lung` have some commented code related to ge
- `paired_ct_lung`, `paired_mrus_brain` and `unpaired_ct_lung` demos have many duplicated code.
- Add a CLI tool to automate the process of adding a demo.

**Comment by YipengHu** [comment]
Concern: this is going to be slow. you cannot really accelerate downloading and some pre-processing.

**Comment by mathpluscode** [comment]
> Concern: this is going to be slow. you cannot really accelerate downloading and some pre-processing.

Yes this can be slow, and normally we dont do release everyday neither

**Comment by NMontanaBrown** [comment]
Most of the demos now have demo_train, demo_predict, demo_data scripts, what is stopping us from just checking these run as expected? And check that the output visualisation is the same as the previous "demo checkpoint"? @mathpluscode @YipengHu Just an extra step in CI with deployment as @mathpluscode says, just with releases.

**Comment by mathpluscode** [comment]
@NMontanaBrown it just needs time i believe ;)
for the joss, we think demo is not that important as we still have 1-2 weeks to do it before the first public release

**Comment by mathpluscode** [comment]
@YipengHu You mentioned earlier that you would like to bring some changes, could you detail them a bit?
As the tests for demos will probably need some small refactoring and we might be able to deal with some issues.

**Comment by YipengHu** [comment]
> @YipengHu You mentioned earlier that you would like to bring some changes, could you detail them a bit?
> As the tests for demos will probably need some small refactoring and we might be able to deal with some issues.

The main thing i was thinking about is #397. I think the others are minor, such as, again, consistent formatting and narratives. re #397, i think the solution might be to ask user first cd to a "working directory", then we have additional script download the demo folder content. This is also related to #398 if we need a neat re-factoring.

**Comment by mathpluscode** [comment]
> > @YipengHu You mentioned earlier that you would like to bring some changes, could you detail them a bit?
> > As the tests for demos will probably need some small refactoring and we might be able to deal with some issues.
> 
> The main thing i was thinking about is #397. I think the others are minor, such as, again, consistent formatting and narratives. re #397, i think the solution might be to ask user first cd to a "working directory", then we have additional script download the demo folder content. This is also related to #398 if we need a neat re-factoring.

ok, in this case, I will do the demo tests first

**Comment by mathpluscode** [comment]
> Most of the demos now have demo_train, demo_predict, demo_data scripts, what is stopping us from just checking these run as expected? And check that the output visualisation is the same as the previous "demo checkpoint"? @mathpluscode @YipengHu Just an extra step in CI with deployment as @mathpluscode says, just with releases.

Btw, after checking some demo scripts, we have the following functionalities in demo scripts.

### Data

For the data script, the functionalities are:

- Download and preprocess the full dataset.
- Download a small preprocessed dataset.
- Download a pre-trained model.

The problem here is in some demo part of the code is commented out.

I'd prefer to uniform the script a bit, at least defining three functions and provide an option to skip downloading full dataset if it's optional. (not all demos have a preprocessed dataset)

### Train

For the training script, the functionality is:

- Launch the training using provided configs.

Some demos prints a message to ask the user to use CLI tool, some demos call the API.

We can provide the API for all demos, and also display a message to tell the user the alternative using CLI tool.

### Predict

For the prediction script, the functionality is:

- Launch the prediction using the given config, assuming the model has been downloaded.
- Display some files manually, like in the demo unpaired_mr_brain.

So I'm wondering do we need extra code in demos for the visualization. 
Personally I think there's no need and we can print messages to guide the user to the prediction outputs.

### Suggestion

So actually there are not many things to change, the train/predict scripts are easy to be uniformed and easy for testing as well.

For the data script, Just need to make commented code optional and test all options for integration test.

What do you think, @YipengHu @NMontanaBrown

**Comment by mathpluscode** [comment]
I will continue this issue soon. The reason is that I'd like to simplify the NN models and layers later and change of models would make the saved checkpoint outdated. Therefore an automated check & checkpoint generation is required ^^

**Comment by mathpluscode** [comment]
With #452 and #451, testing demos again is very important now. For the first step, we could ask for the following requirements:

1. data pre-processing script can be executed correctly.
2. training script can be executed correctly with limited epochs.
3. prediction script can be executed correctly with the checkpoint generated from the training script.

Regarding the saved models, we leave this for later, but the requirements would be

1. Launching the script manually with an appropriate configuration.
2. Test the saved checkpoint to verify the desirable results.
3. Upload the saved checkpoint.
