### ISSUE TITLE
Enable multiple issue templates

### ISSUE THREAD

**Issue by mathpluscode** [DeepRegNet/DeepReg#346]
# Issue description

Try adding a new issue in this package https://github.com/gogs/gogs/issues

![image](https://user-images.githubusercontent.com/4066929/91365252-9111f400-e7f8-11ea-88d8-fee22afea762.png)

this will lead you to a page with multiple issue templates.

We can do the same ;)

## Type of Issue

- [ ] New feature request

**Comment by NMontanaBrown** [comment]
Closing #177 as this seems more relevant, maybe can do the review of templates here?

**Comment by mathpluscode** [comment]
> Closing #177 as this seems more relevant, maybe can do the review of templates here?

sure, we can do multiple PRs regarding this issue ;)
