### ISSUE TITLE
Update contributing docs

### ISSUE THREAD

**Issue by mathpluscode** [DeepRegNet/DeepReg#357]
# Issue description

We need to refactor the whole contributing docs to keep the essential requirements and making onboarding easier.

## Type of Issue

- [ ] Documentation update

**Comment by YipengHu** [comment]
@mathpluscode can you review this? or ask someone to help?

**Comment by mathpluscode** [comment]
> @mathpluscode can you review this? or ask someone to help?

Sure. But this is not of high priority for now. I will handle this when I finished testing all demos, which will require updates of docs anyway.

**Comment by mathpluscode** [comment]
I've extended this issue to be refactoring the whole contributing guidelines.
