### ISSUE TITLE
Change commit policy to conventional commit

### ISSUE THREAD

**Issue by mathpluscode** [DeepRegNet/DeepReg#367]
## Subject of the feature

https://www.conventionalcommits.org/en/v1.0.0/

When checking github actions, I found this commit standard, its features are mainly
- **Automatically generating CHANGELOGs.**
- Automatically determining a semantic version bump (based on the types of commits landed).
- Communicating the nature of changes to teammates, the public, and other stakeholders.
- Triggering build and publish processes.
- Making it easier for people to contribute to your projects, by allowing them to explore a more structured commit history.

and with the help of https://github.com/talos-systems/conform

this rule can be checked and enforced, in the form of github action or pre-commit

@NMontanaBrown what do you think

**Comment by NMontanaBrown** [comment]
@mathpluscode I quite like this, I think it will make the commit history easier to read, and most importantly:

> **Do all my contributors need to use the Conventional Commits specification?**
> No! If you use a squash based workflow on Git lead maintainers can clean up the commit messages as they’re merged—adding no workload to casual committers. A common workflow for this is to have your git system automatically squash commits from a pull request and present a form for the lead maintainer to enter the proper git commit message for the merge.

Which means it doesn't need to be super complicated provided we do squash + merge with people designated to cover merges follow conventional commit style.

**Comment by mathpluscode** [comment]
> @mathpluscode I quite like this, I think it will make the commit history easier to read, and most importantly:
> 
> > **Do all my contributors need to use the Conventional Commits specification?**
> > No! If you use a squash based workflow on Git lead maintainers can clean up the commit messages as they’re merged—adding no workload to casual committers. A common workflow for this is to have your git system automatically squash commits from a pull request and present a form for the lead maintainer to enter the proper git commit message for the merge.
> 
> Which means it doesn't need to be super complicated provided we do squash + merge with people designated to cover merges follow conventional commit style.

Cool, let's bring this to the team then

**Comment by mathpluscode** [comment]
Close as it's included in #407
