### ISSUE TITLE
Simplify type check in tests

### ISSUE THREAD

**Issue by mathpluscode** [DeepRegNet/DeepReg#376]
## Subject of the issue

In the following tests:
- test_backbone
- test_network_util
- test_paired_loader

We have some type check like following

```python
isinstance(item, type(tf.keras.Input(1)))
```

We can pass the class directly like following

```python
isinstance(item,tf.keras.Input)
```

This can make code a bit simpler, although sometimes it might not be always the case like following, because `tf.keras.activations.relu` is not a python class (as the first char is "r" of "relu" not in upper case)

```python
assert isinstance(activation._act, type(tf.keras.activations.relu))
```

**Comment by acasamitjana** [comment]
Actually,  `tf.keras.Input` is not a class but a method that instantiates a keras tensor with all its attributes, but it applies in all other cases of layers, models, etc..

I also updated:
 - test_layer.py
