### ISSUE TITLE
Identify all code not covered by unit-test or non-independent

### ISSUE THREAD

**Issue by mathpluscode** [DeepRegNet/DeepReg#379]
## Subject of the code / test

We are almost 100% test coverage, need to identify all pieces of code not covered by tests with the help of codecov.
Also, we need to identify the test codes that need to be refactored, namely those tests placed sequentially inside one function and those can be simplified using parameterize.

**Comment by YipengHu** [comment]
@NMontanaBrown can you review this and maybe an estimate of time required?

**Comment by NMontanaBrown** [comment]
I am back from the dead, I will be reviewing this week, raising issues, and reporting at meeting on Thursday 😄

**Comment by mathpluscode** [comment]
@NMontanaBrown We now only have 11 lines not covered, we can choose to cover then or ignore them. Ignoring some is acceptable for me.

cc @YipengHu @zacbaum ^^

**Comment by YipengHu** [comment]
> @NMontanaBrown We now only have 11 lines not covered, we can choose to cover then or ignore them. Ignoring some is acceptable for me.
> 
> cc @YipengHu @zacbaum ^^

no comment

**Comment by mathpluscode** [comment]
^^ I'd like to just push to 100% coverage

**Comment by zacbaum** [comment]
I'm fine with ignoring some which aren't possible to cover by ourselves (e.g. which rely on testing from external libraries - I've seen some calls to Keras `Model.` be flagged as not covered) - just a matter of seeing which remain after that.
