### ISSUE TITLE
Tutorial - add new loss

### ISSUE THREAD

**Issue by YipengHu** [DeepRegNet/DeepReg#38]
The detailed steps how to add a new loss
add add_loss.md in /tutorials
add link to the wiki Tutorial Index

**Comment by mathpluscode** [comment]
for custom functionalities, i suggest to label them as post-r1

**Comment by YipengHu** [comment]
this should be a simple tutorial to write and completely independent to code. I marked it as post-r1, but if we have time, we should add this.
