### ISSUE TITLE
Tutorial - add new network

### ISSUE THREAD

**Issue by YipengHu** [DeepRegNet/DeepReg#39]
The detailed steps how to add a new (backbone) network
add add_network.md in /tutorials
add link to the wiki Tutorial Index

**Comment by mathpluscode** [comment]
for custom functionalities, i suggest to label them as post-r1

**Comment by YipengHu** [comment]
this is a doc, which does not to be comprehensive. i think this is useful for user have an opportunity to contributing things

**Comment by YipengHu** [comment]
@mathpluscode would you have time for this? if not, please assign this to me.

**Comment by mathpluscode** [comment]
this is not of priority for me for the moment, and it's part of doc also. i suggest to wait a bit? but ofc you can do it if you have time @YipengHu

**Comment by YipengHu** [comment]
@RemiDelaunay Do you think you have some time to write a short tutorial on how to add a new network? Juts use the affine you did for example? maybe similar to this one: https://github.com/DeepRegNet/DeepReg/blob/master/docs/tutorial_add_loss.md

**Comment by RemiDelaunay** [comment]
@YipengHu Yes I can write a draft using the affine network as an example and you can tell me what you think.
