### ISSUE TITLE
The API shown in readthedocs does not take into account new lines

### ISSUE THREAD

**Issue by ebonmati** [DeepRegNet/DeepReg#394]
## Subject of the documentation

What are you trying to do and which part of the code is hard to understand or incorrect
or missing? Please provide a link to the readthedocs page and code if available.

The documentation shown in readthedocs/API does not take into account the 'enter' character.
As example, in  https://deepreg.readthedocs.io/en/latest/api/loader.html we can find:

Loads paired data using given file loader **H**andles both labeled and unlabeled cases **T**he function sample_index_generator needs to be defined for the **G**eneratorDataLoader class

And in the code this reads as:

Loads paired data using given file loader
Handles both labeled and unlabeled cases
The function sample_index_generator needs to be defined for the
GeneratorDataLoader class

Note that the newline is not taken into account so we have all the sentences in one single sentence, with some capital letters and no stop before.

If the documentation request is approved, would you be willing to submit a PR? _(Help
can be provided if you need assistance submitting a PR)_

Yes

**Comment by mathpluscode** [comment]
We need two enters to break the line. For me it's more about the missing of period. I didn't break the lines on purpose.

**Comment by YipengHu** [comment]
@agrimwood can you review this and an estimate of time required for this?

**Comment by agrimwood** [comment]
I can update code by end of next week. Any advice on the best way to check my changes are working? (i.e. is there a way to create a readthedocs from my branch, or another method to assess changes?)

**Comment by mathpluscode** [comment]
> I can update code by end of next week. Any advice on the best way to check my changes are working? (i.e. is there a way to create a readthedocs from my branch, or another method to assess changes?)

Will invite you to RTD, you could have a separate version of the docs dedicated to your branch.

**Comment by agrimwood** [comment]
Hi @mathpluscode, I've created a PR and assigned it to other reviewers (keeping your workloqad down!)
