### ISSUE TITLE
Tutorial - add new data loader

### ISSUE THREAD

**Issue by YipengHu** [DeepRegNet/DeepReg#40]
The detailed steps how to add a new data loader
add add_loader.md in /tutorials
add link to the wiki Tutorial Index

**Comment by mathpluscode** [comment]
for custom functionalities, i suggest to label them as post-r1

**Comment by YipengHu** [comment]
Agree on this one.

**Comment by mathpluscode** [comment]
I put this issue on hold, as we will need to update the way of supporting custom data loaders, as mentioned in #517.

**Comment by YipengHu** [comment]
related to #517
