### ISSUE TITLE
Remove integration tests

### ISSUE THREAD

**Issue by mathpluscode** [DeepRegNet/DeepReg#402]
## Subject of the issue

We used to use integration tests (the tests under folder output).
Now with all the unit tests we have, it should be safe to remove them. This can save us a lot of time.

What do you think @NMontanaBrown @YipengHu

**Comment by YipengHu** [comment]
fine with me, getting demos connected to the code is a priority to me.

**Comment by NMontanaBrown** [comment]
Should we do this after automation of demo tests? @YipengHu @mathpluscode

**Comment by mathpluscode** [comment]
> Should we do this after automation of demo tests? @YipengHu @mathpluscode

Yes! Sure, I will start dealing with the demos this week!
