### ISSUE TITLE
Quick Start link to "install DeepReg" is broken

### ISSUE THREAD

**Issue by zacbaum** [DeepRegNet/DeepReg#404]
## Subject of the documentation

Currently, from the [quick start page](https://deepreg.readthedocs.io/en/latest/getting_started/quick_start.html), clicking on the install DeepReg link directs to a 404 page.

If the documentation request is approved, would you be willing to submit a PR? _(Help
can be provided if you need assistance submitting a PR)_

Yes

**Comment by YipengHu** [comment]
@zacbaum can you do a hotfix for this please?

**Comment by zacbaum** [comment]
> @zacbaum can you do a hotfix for this please?

Will fix tomorrow and PR to main 👍
