### ISSUE TITLE
Docs + contrib: commit guidelines + auto change-log

### ISSUE THREAD

**Issue by NMontanaBrown** [DeepRegNet/DeepReg#407]
## Subject of the issue

During dev meeting it was raised that changelog can be generated from commits, but this may require stricter commit guidelines or some git hook. However, this complicates contribution and may not be the best way forward to encourage external involvement to the repo. Manual change-logging is not the way forward either..? Discuss.

**Comment by zacbaum** [comment]
Changelogs may also be generated from issues or PRs (closed since last release) - though this would require stricter (read: more meaningful) issue names and PR names.

**Comment by mathpluscode** [comment]
:( I've spent a few hours trying to automate the commit message change. This seems to be hard. (It's doable, tho I didn't find a working script. Shocked.)

If we can not apply the linting to the commit message automatically, it's hard to ask people to stick to a complicated rule.

**Comment by YipengHu** [comment]
how often do we need a changelog, every minor version? this is related to #408

**Comment by mathpluscode** [comment]
> how often do we need a changelog, every minor version? this is related to #408

@YipengHu I think ideally each PR to dev should resume its changes.
So that it would be easier for preparing logs to main.

Another option is that we can still require the commit message to follow a certain style, but only when we do PR.

**Comment by NMontanaBrown** [comment]
> :( I've spent a few hours trying to automate the commit message change. This seems to be hard. (It's doable, tho I didn't find a working script. Shocked.)
> 
> If we can not apply the linting to the commit message automatically, it's hard to ask people to stick to a complicated rule.
> 
> EDIT: however this repo seems to be popular, altho I do not know if it's complicated to install the `npm` (something i do not really understand) https://github.com/commitizen/cz-cli
@YipengHu @mathpluscode 
I wouldn't expect people to install more packages to control commits on top of the one we already use. I think pulling changelogs from PR may be lots easier - if less automated - but will require a bit more scrutiny when reviewing the PR such that it follows a format given format. However, it may be the most contrib friendly, so would vote for this.

**Comment by mathpluscode** [comment]
In the end, I didn't find a simple solution to solve this problem. Therefore following the existing rules seems to be enough. I suggest closing this issue.

**Comment by mathpluscode** [comment]
Close this issue as it's not obvious to have a better commit policy and we've created a separate issue #462 for the change log.
