### ISSUE TITLE
Test on a cluster with a job scheduler

### ISSUE THREAD

**Issue by YipengHu** [DeepRegNet/DeepReg#413]
## Subject of the documentation

Test deepreg, quick start and demo on cs/cmic cluster and write a brief report with a working example.

If the documentation request is approved, would you be willing to submit a PR? _(Help
can be provided if you need assistance submitting a PR)_

Yes / No

**Comment by YipengHu** [comment]
@sbb-gh - sorry, i forgot there is an issue already - you can add your work under this one.

**Comment by sbb-gh** [comment]
Done a pull request, any feedback is much appreciated

**Comment by mathpluscode** [comment]
The docs https://github.com/DeepRegNet/DeepReg/blob/main/docs/source/tutorial/run_cluster.md is not shown on RTD yet. Still need to update https://github.com/DeepRegNet/DeepReg/blob/main/docs/source/index.rst.

**Comment by mathpluscode** [comment]
it's online now.

https://deepreg.readthedocs.io/en/latest/tutorial/run_cluster.html
