### ISSUE TITLE
Testing on real MR-US pairs

### ISSUE THREAD

**Issue by mfazampour** [DeepRegNet/DeepReg#414]
## TRUS-MR deformable registration with real images

I want to test the weakly supervised registration code on real MR-US pairs of prostate. I can see that the trained network is working for the blurred images you made publicly available but is there a chance to have access to original model? 
I tried to resample and align my images according to the sample images, but the registration result is not good. I assume there should be another trained model for the original images.

**Comment by YipengHu** [comment]
Hi @mfazampour , thanks for raising this issue. Unfortunately, we are not in a position to share the original clinical data - that is why we used those "fake" images for the demo. As a consequence, sharing trained model with original data may be risking its credibility of the model. I'm sure you appreciate that, in these interventional/surgical applications, data (especially TRUS) variability is non-trivial and will adversely affect generalisation. How did you acquire your 3D TRUS, for example? I would first suggest you to train your own model with your data. If you are keen to access our trained model for research purpose and happy to establish a collaboration with us, please get in touch again.

**Comment by mfazampour** [comment]
Hi @YipengHu. Thank you for the response. I will close this issue and get in contact with you through email to see how we can collaborate.
