### ISSUE TITLE
Update unit-test guidelines to require independent testing

### ISSUE THREAD

**Issue by mathpluscode** [DeepRegNet/DeepReg#416]
## Subject of the documentation

Now we have some tests where we test different cases sequentially inside one single function.
This is not ideal as sometimes previous tests might have an unexpected impact on the following tests.

Imagine we test a function named `func` we can build tests as follows:

```python
class TestFunc:
    def test_case1(self):
        ...

    def test_case2(self):
        ...
```

so that case1 and case2 are isolated.

In case we are just changing the values of the arguments, we can use [Parametrizing tests](https://docs.pytest.org/en/stable/example/parametrize.html) to remove redundant code.

We do not have to refactor all existing code, but we should update the guidelines so that new tests or modified tests should be refactored.

If the documentation request is approved, would you be willing to submit a PR? _(Help
can be provided if you need assistance submitting a PR)_

Yes

**Comment by mathpluscode** [comment]
@NMontanaBrown what do you think? It'd be nice if it's not me who update the unit-test docs as the existing one are written by me ;)

**Comment by NMontanaBrown** [comment]
@mathpluscode I can work on DeepReg tickets after 28th Sept, MRes dissertation submission. Happy to work on it after then!

**Comment by mathpluscode** [comment]
The change in #439 is a demo of the "parameterize" that I suggested. @NMontanaBrown

**Comment by NMontanaBrown** [comment]
I'm a bit lost on this. Do we really need to parametrize tests? It feels that that would be an unecessary time sink where we could develop other things.

**Comment by mathpluscode** [comment]
> I'm a bit lost on this. Do we really need to parametrize tests? It feels that that would be an unecessary time sink where we could develop other things.

I'd say it's necessary and helpful, but again, we do not need to create issues to change all of them at once. We can change it gradually: every time we modify something, we will need to modify the related test, and then it's an opportunity to refactor the tests.

As we are adapting the code, so the time spent won't be that much. The benefits would be
- identify possible hidden bugs
- reduce redundant code and therefore improve code quality

**Comment by mathpluscode** [comment]
@s-sd I've updated the issue content, does it make more sense now?

**Comment by mathpluscode** [comment]
I gonna update the documentation regarding three issues together. #450 #471 #416
There will be no py code change, only markdown files.

**Comment by mathpluscode** [comment]
@NMontanaBrown Apologies here, as I've been correcting the test styles in multiple PRs and it's better to provide an up-to-date test example and therefore I updated the text as well. Our deal was me updating the test code and you update the text. But turns out most of the existing text on the testing are no longer valid. ;) so please have a look and feel free to add more comment/commits.
