### ISSUE TITLE
MICCAI 2020: Finalist Video + Reviewers Comments

### ISSUE THREAD

**Issue by NMontanaBrown** [DeepRegNet/DeepReg#417]
## Subject of the issue

We made the finals. We need some cool animations for the video that will be showcased at MICCAI. Anyone have pre-made animations or willing to give a hand in generating them from demos?

@YipengHu @mathpluscode @zacbaum @acasamitjana @s-sd @ebonmati ?

**Comment by YipengHu** [comment]
Is it easier to share your latex for people to edit on or leaving comments here?

**Comment by NMontanaBrown** [comment]
> Is it easier to share your latex for people to edit on or leaving comments here?

What do you mean latex - for the video, or for the challenge? The comments were addressing the jupyter notebook (I assume, since that's what was submitted), so we'd have to format that entry, not the arxiv submission? Although I can also share the arxiv submission if necessary (we all know how chaotic editing the jupyter notebook was last time...).

**Comment by NMontanaBrown** [comment]
This is what I've made so far.
[MICCAI_EDUCH_2020_311184817_720x720_F30.mp4.zip](https://github.com/DeepRegNet/DeepReg/files/5238436/MICCAI_EDUCH_2020_311184817_720x720_F30.mp4.zip)

**Comment by YipengHu** [comment]
> > Is it easier to share your latex for people to edit on or leaving comments here?
> 
> What do you mean latex - for the video, or for the challenge? The comments were addressing the jupyter notebook (I assume, since that's what was submitted), so we'd have to format that entry, not the arxiv submission? Although I can also share the arxiv submission if necessary (we all know how chaotic editing the jupyter notebook was last time...).

true - comments then 👍

**Comment by NMontanaBrown** [comment]
Comments, for completeness: 

REVIEWER 1
____________________

OVERALL SCORE
Weak Accept

PLEASE RATE THE ACCURACY OF CONTENT
4

PLEASE RATE THE COMPREHENSIVENESS OF CONTENT
5

PLEASE RATE THE APPROPRIATE LEVEL (ACCESSIBLE TO NEW MASTERS AND PHD STUDENTS?)
4

PLEASE RATE THE RELEVANCE TO THE MICCAI COMMUNITY
4

PLEASE RATE THE CLARITY OF CONTENT
3

PLEASE RATE THE IMPACT FOR THE STUDENT COMMUNITY
4

PLEASE RATE THE IMPACT FOR THE RESEARCH COMMUNITY
3

HOW LIKELY WOULD YOU BE TO RECOMMEND THIS EDUCATIONAL MATERIAL TO A STUDENT WHO WAS INTERESTED IN THE TOPIC?
3

PLEASE LIST ANY FEEDBACK FOR THE AUTHORS, INCLUDING STRENGTHS, WEAKNESSES, OR SUGGESTIONS 
It is very comprehensive and details a lot of the steps well. But at the same time it is very loaded with different information that sometimes seem unnecessary. Which causes the explanations to become very long and loaded with tons of informations. I think some information i.e. API references can be cut out and included as reference somewhere else. 

REVIEWER 2
____________________

OVERALL SCORE
Strong Accept

PLEASE RATE THE ACCURACY OF CONTENT
4

PLEASE RATE THE COMPREHENSIVENESS OF CONTENT
4

PLEASE RATE THE APPROPRIATE LEVEL (ACCESSIBLE TO NEW MASTERS AND PHD STUDENTS?)
5

PLEASE RATE THE RELEVANCE TO THE MICCAI COMMUNITY
5

PLEASE RATE THE CLARITY OF CONTENT
4

PLEASE RATE THE IMPACT FOR THE STUDENT COMMUNITY
4

PLEASE RATE THE IMPACT FOR THE RESEARCH COMMUNITY
4

HOW LIKELY WOULD YOU BE TO RECOMMEND THIS EDUCATIONAL MATERIAL TO A STUDENT WHO WAS INTERESTED IN THE TOPIC?
4

PLEASE LIST ANY FEEDBACK FOR THE AUTHORS, INCLUDING STRENGTHS, WEAKNESSES, OR SUGGESTIONS 
This presentation, in the form of a tutorial, is very well-documented and easy to use. It should potentially be useful to new Masters and PhD students. There's just one thing I would like to suggest. I think, along with this Tutorial, an accompanying short video presentation would be very beneficial to the students. Although the Tutorial is presenting most of the information, a short presentation (of max 10 minutes) might give the students a brief overview as well as the motivations behind the work.

REVIEWER 3
____________________

OVERALL SCORE
Weak Accept

PLEASE RATE THE ACCURACY OF CONTENT
5

PLEASE RATE THE COMPREHENSIVENESS OF CONTENT
5

PLEASE RATE THE APPROPRIATE LEVEL (ACCESSIBLE TO NEW MASTERS AND PHD STUDENTS?)
5

PLEASE RATE THE RELEVANCE TO THE MICCAI COMMUNITY
4

PLEASE RATE THE CLARITY OF CONTENT
5

PLEASE RATE THE IMPACT FOR THE STUDENT COMMUNITY
2

PLEASE RATE THE IMPACT FOR THE RESEARCH COMMUNITY
2

HOW LIKELY WOULD YOU BE TO RECOMMEND THIS EDUCATIONAL MATERIAL TO A STUDENT WHO WAS INTERESTED IN THE TOPIC?
4

PLEASE LIST ANY FEEDBACK FOR THE AUTHORS, INCLUDING STRENGTHS, WEAKNESSES, OR SUGGESTIONS 
The authors provided a detailed, easy-to-follow tutorial to solve medical image registration problems with DeepReg, which provides a new image registration method using Deep Learning. While image registration is a common problem ran into by researchers in the field, image registration has been an active area of research for decades, especially for medical image analysis. A major limitation to the method is that, using a Deep Learning based approach means the method requires a big enough training data where paired images are provided - this lowered the utility of the algorithm on image registration problems that are not easily solvable manually or in a handcrafted fashion. One advantage provided by this example is that, there are customizable handles where the user is allowed to specify the registration fashion to be applied - e.g. dense displacement field, static velocity field, affine transformation. A question is, has the authors considered optimizing the algorithm for large medical image data such as whole slide images? As image registration for large images is a common obstacle to run into in digital pathology.

**Comment by YipengHu** [comment]
- i think we can address the Reviewer 3's comments by editing the third point in the section "Why use Deep Learning for Medical Image Registration", to something like:
"Deep learning models can be more computationally intensive to train than classical methods, and require a sizable training data set" 
 (there isn't any inference with classical methods)

The comments from the other two are not trivial, i would leave them for now.
