### ISSUE TITLE
Adding JOSS Badge to README.md

### ISSUE THREAD

**Issue by zacbaum** [DeepRegNet/DeepReg#427]
## Subject of the feature

Now that the review has officially begun (TBC within 6 or so weeks) we can add a badge to the repo which illustrates that submission (and hopefully acceptance) has occurred for those that are interested.

If the feature request is approved, would you be willing to submit a PR? _(Help can be
provided if you need assistance submitting a PR)_

Yes

E.g.

[![status](https://joss.theoj.org/papers/7e6de472bc82a70d7618e23f618960b3/status.svg)](https://joss.theoj.org/papers/7e6de472bc82a70d7618e23f618960b3)

**Comment by mathpluscode** [comment]
Ok for me ;) we can do it either in main or dev.

**Comment by YipengHu** [comment]
@zacbaum yeah go head please.
