### ISSUE TITLE
Warning related to period

### ISSUE THREAD

**Issue by mathpluscode** [DeepRegNet/DeepReg#428]
## Subject of the issue

TensorFlow is depreciating the argument `period` in checkpoint callback, which defines how many epochs we save the checkpoint.

The desired argument is `save_freq` which defines the frequency in terms of mini-batch. We could continue using `period` in our config, however, when calling the callback, we should calculate the period length using number of mini-batches.

The reason behind might be that when the dataset is large, it might be too long to save a checkpoint even once an epoch.

## Steps to reproduce

Launch any training.

## Expected behaviour

No warning related to `period`.

## Actual behaviour

There are warnings.

**Comment by YipengHu** [comment]
this one gets my vote. @mathpluscode go ahead

**Comment by mathpluscode** [comment]
https://github.com/DeepRegNet/DeepReg/blob/main/deepreg/callback.py#L47

Actually, we no longer use the tf checkpoint callback directly, thus this issue is no longer valid.
