### ISSUE TITLE
[JOSS Review] Referencing TensorFlow

### ISSUE THREAD

**Issue by ethanwharris** [DeepRegNet/DeepReg#430]
_Part of the review for the DeepReg paper on JOSS (openjournals/joss-reviews/issues/2705)._

Since DeepReg is built on TensorFlow, it would be valuable to state this in the paper and provide a reference to the [TensorFlow white paper](https://www.tensorflow.org/about/bib).

**Comment by mathpluscode** [comment]
@ethanwharris We've updated the paper regarding this issue. Once #434 is resolved, we will update the pdf in the JOSS issue. Thanks again for kind suggestions.
