### ISSUE TITLE
DDF get normalized before being saved in predict

### ISSUE THREAD

**Issue by mathpluscode** [DeepRegNet/DeepReg#436]
## Subject of the issue

When saving DDF/DVF in png/nifti formats, values got normalized first. 
[Code](https://github.com/DeepRegNet/DeepReg/blob/main/deepreg/predict.py#L170)
However, we would need the saved nifti output for `deepreg_warp`. 

The correct way is, not changing the values at all when being saved in nifti formats, and normalize the values for png if required in the argument.

## Your environment

- DeepReg version (commit hash or tag)

  d53a8d663acd765a67a47af3b8a3bdcfb958a4fd

## Expected behaviour

Saved values in nifti for DDF/DVF should be exactly the output of model

## Actual behaviour

DDF/DVF got normalized before being saved.

**Comment by mathpluscode** [comment]
@QianyeYang @YipengHu Could you confirm if the description is correct?

**Comment by YipengHu** [comment]
"we could leave vmin and vmax to None and the values will be normalized automatically." - not clear, otherwise looks good to me.

**Comment by mathpluscode** [comment]
> "we could leave vmin and vmax to None and the values will be normalized automatically." - not clear, otherwise looks good to me.

This corresponds to https://github.com/DeepRegNet/DeepReg/blob/main/deepreg/util.py#L122 and the documentation is here https://matplotlib.org/3.1.1/api/_as_gen/matplotlib.pyplot.imsave.html

**Comment by QianyeYang** [comment]
Another small bug here: https://github.com/DeepRegNet/DeepReg/blob/d53a8d663acd765a67a47af3b8a3bdcfb958a4fd/deepreg/warp.py#L59

The first dimension of the warped_image in deepreg/warp.py needs to be removed. Now it's a 4d matrix with shape (1, x, y, z)

**Comment by YipengHu** [comment]
> Another small bug here:
> 
> https://github.com/DeepRegNet/DeepReg/blob/d53a8d663acd765a67a47af3b8a3bdcfb958a4fd/deepreg/warp.py#L59
> 
> The first dimension of the warped_image in deepreg/warp.py needs to be removed. Now it's a 4d matrix with shape (1, x, y, z)

@mathpluscode  can you confirm and perhaps bundle the fix in this issue? - if you do, add this in the issue.

**Comment by YipengHu** [comment]
> > "we could leave vmin and vmax to None and the values will be normalized automatically." - not clear, otherwise looks good to me.
> 
> This corresponds to https://github.com/DeepRegNet/DeepReg/blob/main/deepreg/util.py#L122 and the documentation is here https://matplotlib.org/3.1.1/api/_as_gen/matplotlib.pyplot.imsave.html

Specify what the problem was and what the change is - i thought png cannot save negative values?

**Comment by mathpluscode** [comment]
> > > "we could leave vmin and vmax to None and the values will be normalized automatically." - not clear, otherwise looks good to me.
> > 
> > 
> > This corresponds to https://github.com/DeepRegNet/DeepReg/blob/main/deepreg/util.py#L122 and the documentation is here https://matplotlib.org/3.1.1/api/_as_gen/matplotlib.pyplot.imsave.html
> 
> Specify what the problem was and what the change is - i thought png cannot save negative values?

I've updated the description.

**Comment by mathpluscode** [comment]
@QianyeYang also mentioned

> Btw I have another question, not sure if it's a bug. In the code of deepreg/warp.py Line 59: https://github.com/DeepRegNet/DeepReg/blob/d53a8d663acd765a67a47af3b8a3bdcfb958a4fd/deepreg/warp.py#L59
> 
> The warped_image seems like a 4d matrix, like (1, x, y, z), perhaps the first dimension should be removed?

Which is confirmed as a small bug. Will be fixed together in this issue.
