### ISSUE TITLE
Tutorial for tf profiling

### ISSUE THREAD

**Issue by mathpluscode** [DeepRegNet/DeepReg#459]
## Subject of the documentation

Following the discussion with @sbb-gh, we would like to measure the performance of the existing data loader first 
before doing refactoring/improvement mentioned in #302.

Given previous experiences, the recommended way will be using docker for profiling.
- Docker usage with DeepReg: https://deepreg.readthedocs.io/en/latest/getting_started/install.html#use-docker
- TF profiler: https://www.tensorflow.org/guide/profiler

**Comment by YipengHu** [comment]
@sbb-gh @zacbaum either of you would like to have a look at this? otherwise, I will be closing this next week.
