### ISSUE TITLE
Support training restorage

### ISSUE THREAD

**Issue by mathpluscode** [DeepRegNet/DeepReg#469]
## Subject of the feature

Currently, we are using `model.load_weights` to start the supervised training from non-random weights.
However, if the intention is to resume a stopped run, this will not be perfect as the status of optimizer is not saved in the checkpoint.

The following piece of code can be helpful:
https://github.com/tensorflow/tensorflow/issues/27861#issuecomment-487455939

**Comment by YipengHu** [comment]
what the status of optimizer is useful for resuming?

**Comment by mathpluscode** [comment]
> what the status of optimizer is useful for resuming?

If you do not have the optimizer status, beta, gamma in Adam for example. After reloading the checkpoint, the first gradient update might give a big harmful update which leads to inferior performance.

With optimizer status, you can continue the training as you never stopped it. This piece of code has been tested in other projects, so it's verified already.

**Comment by kate-sann5100** [comment]
The current code uses `<tf.keras.callbacks.ModelCheckpoint>`

**Comment by kate-sann5100** [comment]
Bug with the following failure massage happens when I trained the model on cpu with `deepreg_train --gpu "" --config_path config/unpaired_labeled_ddf.yaml --log_dir` and tried to restore the model with `deepreg_train --gpu "" --config_path config/unpaired_labeled_ddf.yaml --log_dir test --ckpt_path logs/test/save/weights-epoch2.ckpt
`:
`ValueError: Trying to create optimizer slot variable under the scope for tf.distribute.Strategy (<tensorflow.python.distribute.distribute_lib._DefaultDistributionStrategy object at 0x7f93cd2341d0>), which is different from the scope used for the original variable (MirroredVariable:{
  0: <tf.Variable 'local/conv3d_block_8/conv3d_24/conv3d_25/kernel:0' shape=(3, 3, 3, 8, 16) dtype=float32, numpy=
array([[[[[ 5.99554256e-02, -8.05827230e-02, -8.06126893e-02, ...,
           -8.35248306e-02,  6.26967177e-02, -9.56147015e-02],
          [ 9.40468088e-02, -8.64521638e-02,  4.50890586e-02, ...,
           -2.84899101e-02,  7.87315294e-02, -6.87964484e-02],
          [ 5.60011640e-02, -3.45280878e-02, -8.03433731e-02, ...,
            3.07512805e-02,  3.08232084e-02, -3.24381888e-03],
          ...,
          [ 8.36498216e-02, -2.91123018e-02, -4.29024547e-02, ...,
           -2.73975730e-03,  1.07695609e-02, -7.43340999e-02],
          [ 7.66005293e-02,  8.31798390e-02,  6.03686795e-02, ...,
            7.47330412e-02, -4.30560745e-02,  4.45109680e-02],
          [ 3.74492034e-02,  3.90337482e-02,  8.74646828e-02, ...,
           -1.77103207e-02, -2.82334685e-02,  3.29040363e-02]],

         [[-2.68306881e-02, -1.24666393e-02, -5.40468432e-02, ...,
            9.17956904e-02, -2.51463428e-02, -1.90024301e-02],
          [ 9.05782729e-03,  2.88167670e-02,  5.38337752e-02, ...,
           -5.91438301e-02,  7.02720210e-02,  4.30254862e-02],
          [-4.01913486e-02,  1.28472000e-02,  5.59527799e-02, ...,
           -2.86417454e-03,  7.77504221e-02, -5.70860617e-02],
          ...,
          [-9.32958350e-02,  8.50640014e-02, -4.61969487e-02, ...,
            7.94670805e-02, -7.19964206e-02, -8.44038725e-02],
          [-4.98019159e-03, -2.24459544e-02, -2.02582628e-02, ...,
           -4.63261344e-02, -8.55450705e-02, -3.55760939e-02],
          [ 9.34151933e-02, -2.15407088e-02,  2.88044587e-02, ...,
            6.50863126e-02, -9.22358483e-02, -7.11130202e-02]],

         [[ 2.06779391e-02,  6.73264489e-02,  3.19725946e-02, ...,
            4.32833806e-02, -6.46718517e-02,  7.41289333e-02],
          [-3.47259603e-02,  7.82126114e-02,  3.37081924e-02, ...,
           -4.22528572e-02, -8.86238366e-03,  2.67376378e-02],
          [-1.42709911e-02,  7.57381842e-02, -5.09782322e-02, ...,
            5.18682674e-02, -5.63417152e-02, -6.55169562e-02],
          ...,
          [-3.65337767e-02,  4.39948365e-02,  2.31150463e-02, ...,
           -2.87914574e-02, -4.48301435e-05, -4.79234345e-02],
          [-4.85566780e-02,  2.64009833e-02,  9.54407379e-02, ...,
            2.27445140e-02, -4.11780067e-02,  3.23294625e-02],
          [-6.88229203e-02, -8.97542760e-02, -1.26907378e-02, ...,
            5.72510585e-02, -4.82454710e-02, -3.76682281e-02]]],


        [[[-4.43437509e-02, -3.46949659e-02, -4.75644656e-02, ...,
            5.50945327e-02,  9.55135450e-02,  1.87577754e-02],
          [-7.00717866e-02,  8.14823061e-03,  9.43320617e-02, ...,
           -1.58783942e-02, -3.32453847e-02,  1.54744089e-02],
          [ 8.23999271e-02, -8.79738778e-02, -5.67130521e-02, ...,
            9.46347639e-02, -8.16255957e-02,  7.05959573e-02],
          ...,
          [ 5.96773699e-02,  7.11790249e-02, -4.68207598e-02, ...,
           -3.59257944e-02, -5.56116812e-02, -7.80505911e-02],
          [ 5.91514930e-02,  7.66456947e-02,  4.28854600e-02, ...,
           -2.84844488e-02, -7.37315565e-02, -6.10326082e-02],
          [ 3.31710353e-02,  9.42812040e-02,  4.27353457e-02, ...,
           -5.96016571e-02,  1.03403628e-03,  1.38291121e-02]],

         [[-6.73160106e-02,  5.10919616e-02, -4.23391871e-02, ...,
           -6.88428357e-02, -9.17625129e-02, -1.17870569e-02],
          [-5.31788133e-02, -4.98472452e-02, -5.18539026e-02, ...,
            1.35458261e-02,  1.65191367e-02,  6.79249540e-02],
          [-7.56209791e-02,  9.94138420e-03, -8.25781152e-02, ...,
           -5.71759269e-02,  5.79565838e-02, -8.98789465e-02],
          ...,
          [-8.59420747e-02,  5.21598831e-02,  7.16560408e-02, ...,
            2.96347961e-02,  3.37667689e-02,  3.84867266e-02],
          [ 8.83447751e-02, -6.42616451e-02, -1.38467327e-02, ...,
            2.72539183e-02, -8.18924531e-02, -1.57723054e-02],
          [-8.77310112e-02, -5.56803010e-02,  3.89620662e-04, ...,
            6.77909330e-02, -7.91016221e-03, -9.86187160e-03]],

         [[ 8.14001635e-02,  7.91162178e-02,  1.87337548e-02, ...,
            3.14045027e-02, -3.56334932e-02,  7.67309591e-02],
          [-9.14871395e-02,  6.72105029e-02, -4.68559973e-02, ...,
           -4.02171127e-02,  6.69647679e-02, -6.79852515e-02],
          [-2.50821710e-02,  1.07402205e-02,  8.13884959e-02, ...,
           -6.48464113e-02, -9.27457958e-03,  2.54140273e-02],
          ...,
          [ 3.16640660e-02,  1.89255029e-02,  1.40305609e-02, ...,
            3.52492705e-02,  1.32741928e-02, -9.13566053e-02],
          [ 9.34628025e-02,  3.32265273e-02, -2.45599449e-03, ...,
            8.59429762e-02,  8.94061998e-02,  6.40578344e-02],
          [-5.84043004e-02, -7.31757283e-03,  9.25494209e-02, ...,
           -3.66513319e-02, -6.37767017e-02,  8.09238926e-02]]],


        [[[-2.03599632e-02,  2.21153572e-02, -8.53273720e-02, ...,
           -4.35113981e-02,  9.10988227e-02,  4.82727215e-02],
          [-5.52377775e-02, -4.54942845e-02, -5.97494952e-02, ...,
            9.55016688e-02,  4.34809998e-02,  4.99256328e-02],
          [ 1.95643678e-02, -9.50597152e-02,  5.19118682e-02, ...,
            7.70149902e-02, -4.40241508e-02, -5.79554886e-02],
          ...,
          [ 1.79119781e-02,  7.64494762e-02, -7.39280358e-02, ...,
           -5.36861271e-02, -1.91170648e-02,  5.83836958e-02],
          [ 8.52766559e-02, -8.45540017e-02, -3.07092145e-02, ...,
            4.66183648e-02, -8.31455141e-02, -4.57941592e-02],
          [ 7.49649182e-02,  5.50341681e-02, -6.44064844e-02, ...,
            7.25303218e-02, -4.03027758e-02,  7.86458328e-02]],

         [[ 5.73735461e-02, -7.89670199e-02,  3.76374274e-03, ...,
            5.55703789e-03,  9.12354663e-02, -2.20393091e-02],
          [-5.80949336e-03, -4.33199964e-02, -5.96763119e-02, ...,
           -8.95538330e-02, -5.33876084e-02, -2.28273869e-03],
          [ 2.63003632e-02, -6.68263435e-03, -2.66183168e-02, ...,
           -8.68633389e-03,  1.35018229e-02,  4.92174551e-02],
          ...,
          [ 3.13036814e-02, -5.83873019e-02, -3.66001017e-02, ...,
           -9.55642089e-02, -8.16504657e-03,  3.46591696e-02],
          [-7.39275739e-02,  4.95393053e-02, -3.55570056e-02, ...,
            2.06668377e-02, -1.11812130e-02, -8.80280882e-02],
          [ 5.43784276e-02, -5.37783094e-02, -6.05794154e-02, ...,
            2.67997384e-05, -5.94812818e-02,  4.48938683e-02]],

         [[-3.95893082e-02, -8.22719783e-02,  3.94225940e-02, ...,
           -5.48042655e-02, -4.32506204e-03,  4.04026881e-02],
          [ 2.14517862e-02, -2.25618333e-02,  7.01356754e-02, ...,
            1.03273392e-02, -7.79636428e-02,  2.37109438e-02],
          [-5.31443805e-02, -6.27309680e-02,  9.26575437e-02, ...,
            2.28359401e-02,  4.33767810e-02, -4.27792221e-03],
          ...,
          [ 3.98134217e-02, -8.48962069e-02,  4.49867025e-02, ...,
            7.46012554e-02,  8.16411003e-02,  6.23403862e-02],
          [-9.18080509e-02,  7.72045627e-02, -3.12479511e-02, ...,
            8.31109285e-03, -3.22776288e-02, -9.54882428e-02],
          [ 9.06394646e-02,  2.20518559e-02,  7.97911361e-02, ...,
            9.32952389e-02, -4.37807590e-02,  5.25631085e-02]]]],



       [[[[-6.98601007e-02, -3.51527259e-02,  3.63593325e-02, ...,
            5.53765073e-02,  3.08719277e-03,  8.03203806e-02],
          [-7.10837692e-02,  1.82107016e-02,  8.07777122e-02, ...,
            1.56139657e-02,  7.84031078e-02,  1.28292590e-02],
          [ 4.31694910e-02, -2.98046619e-02, -8.11686143e-02, ...,
            5.90937212e-02,  7.51127228e-02,  3.31356749e-02],
          ...,
          [-7.06078857e-02,  7.49104992e-02, -6.90931082e-02, ...,
           -7.55324513e-02, -1.28890201e-02,  9.06050131e-02],
          [ 6.76476955e-03, -5.81073165e-02,  4.26403955e-02, ...,
            3.57965603e-02,  8.62154290e-02,  3.58197764e-02],
          [-4.04191613e-02, -1.07766762e-02, -2.89077014e-02, ...,
           -8.93705487e-02,  3.89032587e-02,  7.66419396e-02]],

         [[-7.90414959e-03,  1.97659507e-02, -6.47252128e-02, ...,
           -1.35338753e-02, -3.17349881e-02, -4.51680981e-02],
          [-4.86006103e-02,  4.74490225e-03,  6.39355108e-02, ...,
           -4.14719433e-03, -2.37381756e-02,  3.34303156e-02],
          [-5.51639721e-02,  9.32496563e-02,  5.90390489e-02, ...,
           -3.80062982e-02,  2.70785764e-02,  1.41517892e-02],
          ...,
          [-9.10905674e-02, -1.23218447e-03, -1.55052617e-02, ...,
           -4.39580753e-02,  1.16308033e-03,  3.87383327e-02],
          [ 5.86575493e-02, -8.22279528e-02, -2.50407904e-02, ...,
           -8.64221156e-02, -3.93107943e-02, -3.83029133e-02],
          [ 1.07545629e-02, -7.06791282e-02, -7.30223358e-02, ...,
            6.42410293e-02, -8.68923962e-04, -3.77645604e-02]],

         [[ 3.96626517e-02,  2.36146525e-02,  8.59408155e-02, ...,
           -1.46636665e-02, -9.53559205e-02,  2.46071666e-02],
          [-3.85076553e-03, -6.42482936e-02, -5.71714975e-02, ...,
           -4.27610651e-02, -7.69527778e-02, -2.79189572e-02],
          [ 8.57121572e-02,  6.63654432e-02,  2.54893899e-02, ...,
           -7.92590082e-02,  8.43387842e-03, -3.77468765e-03],
          ...,
          [-8.03263932e-02, -3.75257581e-02,  3.63849327e-02, ...,
            7.84426257e-02,  7.27072582e-02,  4.68620136e-02],
          [ 3.96847203e-02,  4.11660597e-02, -6.85710236e-02, ...,
           -8.19181949e-02,  8.03975835e-02,  4.42595854e-02],
          [ 8.28297362e-02,  5.39876521e-03,  2.73344889e-02, ...,
           -6.53615743e-02,  6.72568008e-02, -3.35875154e-03]]],


        [[[-4.97275144e-02,  5.77642992e-02, -3.89958732e-02, ...,
           -5.91082945e-02, -4.85814363e-03, -4.96967956e-02],
          [ 3.67599353e-02, -5.60896508e-02, -3.29532921e-02, ...,
           -3.65756005e-02,  1.72894076e-02, -8.70001987e-02],
          [ 6.99340478e-02, -8.50808620e-02,  5.83982393e-02, ...,
           -2.85222381e-02,  7.13799968e-02,  2.30182707e-03],
          ...,
          [-7.83668160e-02,  9.33996588e-03, -6.38763160e-02, ...,
           -2.21299380e-03, -9.48428214e-02,  8.46695825e-02],
          [-5.58884069e-02,  1.97587758e-02, -2.57818773e-02, ...,
           -5.69275096e-02,  2.72726119e-02, -1.55044645e-02],
          [ 3.77097502e-02, -5.23165688e-02,  7.45550320e-02, ...,
            2.84151658e-02, -5.00122681e-02, -9.34847146e-02]],

         [[-8.58622193e-02, -7.40950257e-02, -7.99849331e-02, ...,
            1.37379840e-02, -1.62752122e-02,  1.87598392e-02],
          [ 6.02471083e-03,  4.94965538e-02, -9.00398567e-02, ...,
           -9.50623304e-02, -2.70068347e-02,  1.89445242e-02],
          [-9.39933583e-02,  7.44076148e-02,  7.64153823e-02, ...,
           -8.16769600e-02,  4.54448238e-02, -5.76769747e-02],
          ...,
          [ 9.52079371e-02, -3.01291496e-02, -7.23885223e-02, ...,
            6.31993786e-02, -1.17363557e-02, -6.14694506e-03],
          [ 1.79371908e-02, -3.73034179e-03,  6.63935468e-02, ...,
            6.67281225e-02, -3.37994061e-02,  2.11685523e-02],
          [-1.23246089e-02,  8.83974060e-02, -1.58840790e-02, ...,
            8.55895802e-02, -3.96994501e-03, -6.64214864e-02]],

         [[ 1.46069303e-02,  5.13016433e-03, -7.30310306e-02, ...,
           -5.27032539e-02,  9.01157483e-02,  5.54038808e-02],
          [ 8.03548619e-02,  4.53197956e-03, -2.30949298e-02, ...,
           -7.32711852e-02,  8.23177397e-04,  3.36373076e-02],
          [ 7.75833800e-02, -8.11326504e-03,  7.41138309e-03, ...,
           -1.63042620e-02,  3.86967734e-02,  5.49090430e-02],
          ...,
          [-8.59862641e-02,  2.27877349e-02,  2.02634707e-02, ...,
           -1.62220150e-02,  1.79314315e-02, -5.69679365e-02],
          [ 6.92582950e-02,  2.46600658e-02, -6.15680963e-03, ...,
            2.45493054e-02, -8.20446461e-02, -6.32338375e-02],
          [ 9.20740440e-02, -1.27434731e-03,  6.48558885e-03, ...,
           -5.74511811e-02,  5.23796305e-02, -4.89186980e-02]]],


        [[[ 2.84552425e-02,  4.58448157e-02,  1.05832964e-02, ...,
            4.33349535e-02, -5.01511246e-03, -3.29662785e-02],
          [ 3.59639451e-02, -7.39948153e-02,  2.85032392e-02, ...,
            7.59571865e-02,  9.06831697e-02, -3.64452899e-02],
          [-8.74774829e-02,  2.90223137e-02, -6.57667518e-02, ...,
           -6.42397627e-02, -6.17320128e-02, -2.55058408e-02],
          ...,
          [ 6.99935779e-02, -1.92110389e-02,  7.70461485e-02, ...,
           -7.51710907e-02, -2.16339678e-02,  6.22306541e-02],
          [ 2.74872109e-02, -6.23101480e-02,  1.29878595e-02, ...,
            2.14123502e-02,  9.05558467e-04, -1.13760978e-02],
          [-2.97464803e-02, -9.22948346e-02,  5.86325452e-02, ...,
           -6.47064745e-02, -4.85510342e-02, -3.69091518e-02]],

         [[ 6.53883815e-03,  7.03498200e-02,  6.92136586e-03, ...,
            8.43433961e-02, -3.93910892e-02, -6.28693998e-02],
          [-2.43039876e-02, -2.89006829e-02, -2.61679664e-02, ...,
            7.71307424e-02, -8.40329751e-02,  5.89278117e-02],
          [-3.60147879e-02,  8.82274285e-02,  1.46142989e-02, ...,
           -2.69645303e-02, -2.92761475e-02,  5.40353358e-03],
          ...,
          [ 2.76916921e-02,  5.75016066e-02, -1.22589022e-02, ...,
            5.76705560e-02, -4.24252860e-02,  2.37787813e-02],
          [ 6.01365492e-02,  8.81538764e-02,  8.00685510e-02, ...,
            9.55807939e-02,  7.10272714e-02, -2.21390352e-02],
          [ 9.46132168e-02,  4.47723940e-02, -8.19054618e-02, ...,
           -3.74001078e-02,  6.78473040e-02,  1.65259689e-02]],

         [[ 4.94978204e-02,  7.34148398e-02, -7.38314688e-02, ...,
           -7.32328519e-02, -1.58637092e-02,  4.87107262e-02],
          [-2.48474553e-02, -6.10304512e-02,  8.94310251e-02, ...,
           -4.92428690e-02, -8.37749690e-02,  6.80565760e-02],
          [ 2.85958499e-03,  3.71778682e-02, -8.07041377e-02, ...,
           -7.64527842e-02,  1.18870139e-02, -6.62669241e-02],
          ...,
          [ 6.45999238e-02, -9.63233411e-04,  6.38278574e-03, ...,
            7.52995238e-02, -2.84673795e-02,  5.04545867e-03],
          [ 1.95291042e-02,  7.31254146e-02,  1.68001726e-02, ...,
           -3.39109525e-02, -9.07351822e-02, -1.78710297e-02],
          [-2.72167996e-02, -1.29153803e-02,  1.47494674e-02, ...,
            2.25199014e-03, -7.59901404e-02,  2.49530151e-02]]]],



       [[[[ 5.16385958e-02, -8.67857412e-02,  2.11125687e-02, ...,
           -4.97391894e-02, -7.52738938e-02, -9.53958184e-03],
          [-6.81161582e-02, -4.91051488e-02, -4.60247248e-02, ...,
           -5.56783974e-02, -1.63052231e-03,  8.99438187e-02],
          [-3.54850143e-02, -8.47042501e-02, -8.18057805e-02, ...,
            5.72256371e-02, -3.76075469e-02, -1.85815394e-02],
          ...,
          [ 8.02469477e-02,  8.54943171e-02, -7.40839690e-02, ...,
           -2.33027339e-03,  8.88881609e-02, -2.10104585e-02],
          [-4.29088324e-02, -2.08855644e-02, -3.44552472e-02, ...,
           -1.82525292e-02,  6.42590299e-02, -2.31600404e-02],
          [-8.46817419e-02, -8.70669410e-02,  6.43765703e-02, ...,
            3.15177515e-02,  3.20190191e-03, -4.28470038e-02]],

         [[-4.04141806e-02,  2.65842900e-02,  8.45675394e-02, ...,
           -1.24906600e-02, -4.75565046e-02,  1.48778036e-02],
          [ 4.59100306e-03,  8.72592553e-02,  5.45400456e-02, ...,
           -5.80230989e-02, -2.45992243e-02,  8.86797085e-02],
          [ 8.38004127e-02,  8.60024318e-02, -1.91330835e-02, ...,
            8.94307271e-02, -8.21496099e-02, -2.23223418e-02],
          ...,
          [-6.04185015e-02,  1.34268925e-02, -7.56004453e-02, ...,
           -6.20635711e-02, -1.69487894e-02, -4.91806939e-02],
          [-2.76589766e-02, -3.85147594e-02,  5.25150448e-03, ...,
           -4.32522260e-02,  3.45486030e-02, -7.82202184e-02],
          [-3.61794643e-02,  8.16093907e-02, -4.46629636e-02, ...,
           -3.10603827e-02,  4.71143648e-02, -8.64786208e-02]],

         [[-9.49222967e-02, -6.33231923e-02, -6.63010180e-02, ...,
           -1.64666176e-02, -6.37993962e-02,  9.40887257e-02],
          [ 2.15366706e-02,  7.70619288e-02,  8.70120451e-02, ...,
            4.27475795e-02, -1.26400590e-02, -3.20491269e-02],
          [-4.28963304e-02, -2.99580470e-02, -1.96083635e-02, ...,
            1.02547258e-02, -8.48108158e-02, -1.07489601e-02],
          ...,
          [ 4.92602065e-02, -2.16412917e-02, -3.69835757e-02, ...,
            1.57397985e-02,  7.96745792e-02,  7.04980716e-02],
          [-6.35390058e-02, -3.80192846e-02,  2.00096667e-02, ...,
           -6.22087903e-02, -5.90325892e-03, -7.73927122e-02],
          [ 6.44874945e-02,  7.48585090e-02,  5.90547249e-02, ...,
            2.39581838e-02,  3.34278867e-02, -6.71311691e-02]]],


        [[[-2.21659690e-02,  1.92209929e-02, -8.45057815e-02, ...,
           -3.40315811e-02, -6.65202513e-02, -4.70128059e-02],
          [-7.36526176e-02,  1.51164010e-02,  6.06640950e-02, ...,
           -4.67160307e-02,  1.16539747e-02,  1.29407570e-02],
          [-8.39332640e-02, -3.76478322e-02,  4.89882156e-02, ...,
           -5.94789200e-02, -1.47644952e-02, -5.04660122e-02],
          ...,
          [-3.47696878e-02,  7.11579695e-02,  5.52168563e-02, ...,
            7.31574818e-02, -3.54521386e-02, -8.30361024e-02],
          [-1.40402243e-02, -5.80947921e-02, -2.35972852e-02, ...,
            8.04178044e-02,  3.28396261e-03, -2.84625888e-02],
          [-1.48766488e-03, -4.50663045e-02, -6.17678016e-02, ...,
           -3.69683169e-02, -2.20825300e-02, -9.54719782e-02]],

         [[ 7.95700476e-02,  1.62982270e-02,  6.87095895e-02, ...,
            4.31585833e-02, -4.45919372e-02,  6.47608861e-02],
          [ 5.44257686e-02, -6.95795938e-02, -1.77972466e-02, ...,
            7.34325573e-02,  3.24163660e-02, -6.20026588e-02],
          [ 2.05606222e-04, -1.35773718e-02,  4.41941246e-02, ...,
            8.64923671e-02,  3.21659669e-02,  3.49453762e-02],
          ...,
          [ 2.37626955e-02, -4.42435406e-02, -2.25156918e-02, ...,
           -8.47418085e-02,  9.40401852e-03, -1.32458583e-02],
          [ 1.13377422e-02, -8.62945616e-03,  4.75332811e-02, ...,
           -8.69897604e-02, -1.42533779e-02,  4.68008742e-02],
          [-8.88645723e-02, -3.32723558e-03,  9.61424336e-02, ...,
           -5.29501773e-02,  4.03000638e-02, -2.06223950e-02]],

         [[-8.29494074e-02, -2.02361271e-02, -2.95869857e-02, ...,
            6.81249127e-02, -8.39445516e-02,  3.62547413e-02],
          [ 4.38837633e-02, -2.61543170e-02,  2.88559720e-02, ...,
            4.02156636e-02, -8.26558620e-02, -8.64674002e-02],
          [-5.53399809e-02,  5.43987677e-02, -8.57763886e-02, ...,
           -4.71011549e-02, -8.92922506e-02, -4.23376039e-02],
          ...,
          [ 3.52932438e-02,  7.61121511e-04,  4.31400537e-03, ...,
           -3.99758555e-02, -3.00671607e-02,  2.57752836e-04],
          [ 3.14041153e-02, -3.99737917e-02,  4.63737324e-02, ...,
            6.20030537e-02,  1.48421302e-02, -5.28016500e-02],
          [-9.24561620e-02, -5.98895997e-02, -7.94376507e-02, ...,
            7.15912655e-02,  4.83358428e-02,  3.32888216e-03]]],


        [[[-3.30699235e-02, -5.47456294e-02,  4.59131524e-02, ...,
           -5.11061400e-03,  1.55915320e-03, -2.47093663e-02],
          [ 2.13629156e-02,  3.02094743e-02, -4.00396585e-02, ...,
           -7.06149638e-03, -2.41510570e-02, -5.72600551e-02],
          [ 8.36553425e-03,  2.73858085e-02,  4.58735898e-02, ...,
           -5.63813336e-02,  9.11391601e-02, -8.51265639e-02],
          ...,
          [ 4.88105342e-02, -4.33419980e-02,  7.22540393e-02, ...,
           -3.46501358e-02,  1.34387538e-02, -1.06718540e-02],
          [ 7.26284757e-02, -4.77410927e-02,  8.83462206e-02, ...,
           -1.01933107e-02,  6.28231540e-02,  3.31906229e-03],
          [-8.75032470e-02,  6.02214038e-03, -5.19327968e-02, ...,
           -6.82230145e-02, -3.80961373e-02,  6.58560619e-02]],

         [[ 7.82990977e-02, -1.24669597e-02, -1.34444684e-02, ...,
            8.90235379e-02, -3.13516483e-02,  3.57803926e-02],
          [-1.14069358e-02,  5.51175103e-02, -2.93993726e-02, ...,
            3.20254490e-02, -4.93298173e-02, -1.85996294e-03],
          [ 4.57474515e-02, -1.06419399e-02,  7.49074146e-02, ...,
           -6.90414682e-02,  2.66881064e-02, -7.00300038e-02],
          ...,
          [ 7.12578967e-02, -2.39196196e-02,  5.34919277e-02, ...,
            5.51406667e-02, -7.22458959e-03,  4.48797122e-02],
          [-7.60497376e-02, -1.43332556e-02, -4.93776053e-02, ...,
           -8.67087021e-02,  3.05590034e-03, -2.25774571e-02],
          [ 7.97077194e-02,  8.37420672e-03, -6.09844327e-02, ...,
            1.17528513e-02, -3.07849795e-03,  3.61071005e-02]],

         [[ 4.40578088e-02,  5.02318144e-03,  4.49951217e-02, ...,
            2.50876099e-02, -8.47164094e-02, -7.15197325e-02],
          [-6.78633377e-02, -8.18095654e-02,  5.66993654e-03, ...,
           -5.79200909e-02,  1.28315091e-02, -4.64474745e-02],
          [ 6.42325357e-02, -3.67640220e-02,  6.42734393e-02, ...,
            3.14394012e-02,  5.58819622e-03, -7.80680776e-03],
          ...,
          [-4.44543548e-02, -4.96654101e-02,  8.78247544e-02, ...,
           -3.51891778e-02, -1.94536671e-02,  5.18273339e-02],
          [-4.65025119e-02,  1.33334324e-02, -3.11187431e-02, ...,
            3.80892977e-02,  9.08547565e-02, -7.25082085e-02],
          [ 1.58674717e-02, -6.31270409e-02,  6.12270907e-02, ...,
            2.55771726e-03,  5.80825582e-02, -6.56253844e-02]]]]],
      dtype=float32)>
}). Make sure the slot variables are created under the same strategy scope. This may happen if you're restoring from a checkpoint outside the scope
`

**Comment by kate-sann5100** [comment]
A bug happens if I try to train the demo with 1 gpu using `deepreg_train --gpu "" --config_path config/unpaired_labeled_ddf.yaml --log_dir test` and restore the training with 1 gpu using ` deepreg_train --gpu "" --config_path config/unpaired_labeled_ddf.yaml --log_dir test --ckpt_path logs/test/save/weights-epoch2.ckpt`

**Comment by kate-sann5100** [comment]
[train for an epoch resolves optimiser weights not loaded warning](https://github.com/tensorflow/tensorflow/issues/33150#issuecomment-574517363)
