### ISSUE TITLE
Installation instructions

### ISSUE THREAD

**Issue by YipengHu** [DeepRegNet/DeepReg#471]
## Subject of the documentation

What are you trying to do and which part of the code is hard to understand or incorrect
or missing? Please provide a link to the readthedocs page and code if available.

The installation page now contains information difficult to structure. Relationship between dovker, conda and pip are not obvious to many.

If the documentation request is approved, would you be willing to submit a PR? _(Help
can be provided if you need assistance submitting a PR)_

Yes / No

**Comment by YipengHu** [comment]
@mathpluscode let's discuss and I can help re-write this.

**Comment by YipengHu** [comment]
@mathpluscode I assign this to you and please ask me to review it when done. Thanks!

**Comment by mathpluscode** [comment]
I gonna update the documentation regarding three issues together. #450 #471 #416
There will be no py code change, only markdown files.

**Comment by YipengHu** [comment]
@mathpluscode following the instruction page: https://deepreg.readthedocs.io/en/latest/getting_started/install.html
will produce error: EnvironmentFileNotFound: '/home/yipenghu/enviroment_cpu.yml' file not found

**Comment by YipengHu** [comment]
@mathpluscode The Doker option is not particularly straightforward or simple to do, and should be left the last optional one?

**Comment by YipengHu** [comment]
@mathpluscode i'm still having doubt with the environment.yml file, you need to change the name/file to create another one? can i overwrite some deepreg?

**Comment by mathpluscode** [comment]
> @mathpluscode following the instruction page: https://deepreg.readthedocs.io/en/latest/getting_started/install.html
> 
> will produce error: EnvironmentFileNotFound: '/home/yipenghu/enviroment_cpu.yml' file not found

@YipengHu you need to be inside DeepReg folder? I will check if it's clearly define.

I'm fine to put docker the list option :)

**Comment by mathpluscode** [comment]
> @mathpluscode i'm still having doubt with the environment.yml file, you need to change the name/file to create another one? can i overwrite some deepreg?

What do you mean? What do you want to overwrite? 🤔 @YipengHu

**Comment by YipengHu** [comment]
> > @mathpluscode following the instruction page: https://deepreg.readthedocs.io/en/latest/getting_started/install.html
> > will produce error: EnvironmentFileNotFound: '/home/yipenghu/enviroment_cpu.yml' file not found
> 
> @YipengHu you need to be inside DeepReg folder? I will check if it's clearly define.
> 
> I'm fine to put docker the list option :)

This is the first thing on the page - you do not have any deepreg yet.

**Comment by YipengHu** [comment]
> > @mathpluscode i'm still having doubt with the environment.yml file, you need to change the name/file to create another one? can i overwrite some deepreg?
> 
> What do you mean? What do you want to overwrite? 🤔 @YipengHu

how do you install it if you have one already installed? how do you install multiple envs?

**Comment by mathpluscode** [comment]
> > > @mathpluscode i'm still having doubt with the environment.yml file, you need to change the name/file to create another one? can i overwrite some deepreg?
> 
> > 
> 
> > What do you mean? What do you want to overwrite? 🤔 @YipengHu
> 
> 
> 
> how do you install it if you have one already installed? how do you install multiple envs?

If installed, use the update commands.

Multiple envs? Why we need multiple DeepReg Env, if you want change the name inside environment.yml :)
So we need some FAQ then.
