### ISSUE TITLE
Adding Point-Set registration method(s)

### ISSUE THREAD

**Issue by zacbaum** [DeepRegNet/DeepReg#475]
## Subject of the feature

It could be beneficial to DeepReg packages to include some form of point-set registration (either classical [ICP, CPD] or new learning-based methods).

This will also likely require useful methods for quick extraction of point-sets from image labels/masks.

**Comment by NMontanaBrown** [comment]
Do we have to re-implem this or just point to existing packages/integrate with packages?

I'm aware of CPD at: 
- https://github.com/siavashk/pycpd
but @YipengHu mentioned to me a while back that this might be buggy (?)

And I think the sksurgery libraries have ICP? @MattClarkson

**Comment by YipengHu** [comment]
> Do we have to re-implem this or just point to existing packages/integrate with packages?
> 
> I'm aware of CPD at:
> 
> * https://github.com/siavashk/pycpd
>   but @YipengHu mentioned to me a while back that this might be buggy (?)
> 
> And I think the sksurgery libraries have ICP? @MattClarkson
> 
> I opened a separate issue for FPT #511.

the said implementation is not "buggy" but having only partial implementation... i'm more interested in adding Zac's learning-based stuff.

**Comment by NMontanaBrown** [comment]
The ticket does say "either classical [ICP, CPD] or new learning-based methods" so I was trying to be thorough 😄

**Comment by mathpluscode** [comment]
@NMontanaBrown is this ticket duplicated with #511 or #511 is a small part of this?

**Comment by NMontanaBrown** [comment]
> @NMontanaBrown is this ticket duplicated with #511 or #511 is a small part of this?

Hmm, there is some overlap, but I had thought it might be worth separating into two, since #511 is specifically a new architecture and this refers to classical point set registration in addition. Let's modularise our tickets as it will be easier to review, if FPT is not dependent on ICP or CPD implems? @zacbaum

**Comment by zacbaum** [comment]
Probably no use in reimplementing CPD or ICP as there are existing versions out there (was just a thought when I typed this out during the meeting a few weeks ago). I'd say we can close one of them, just a matter of which...

**Comment by NMontanaBrown** [comment]
> Probably no use in reimplementing CPD or ICP as there are existing versions out there (was just a thought when I typed this out during the meeting a few weeks ago). I'd say we can close one of them, just a matter of which...

I can close #511, but I'm wondering if there is any use integrating the classical point set packages via a demo for ease of use with DeepReg? This is a completely different ticket, but thoughts?

**Comment by zacbaum** [comment]
> > Probably no use in reimplementing CPD or ICP as there are existing versions out there (was just a thought when I typed this out during the meeting a few weeks ago). I'd say we can close one of them, just a matter of which...
> 
> I can close #511, but I'm wondering if there is any use integrating the classical point set packages via a demo for ease of use with DeepReg? This is a completely different ticket, but thoughts?

Could be of use in the future, but let's get Point Set registration in first, then worry about how to showcase it in a demo 😄
