### ISSUE TITLE
[JOSS Review] Code Review Summary

### ISSUE THREAD

**Issue by zhangfanmark** [DeepRegNet/DeepReg#479]
Hi,

I'm reviewing the DeepReg paper on JOSS (openjournals/joss-reviews/issues/2705). 

I am able to install the software and successfully run through the code, including model training and testing, while there are some small bugs as pointed out in the other issue. 

I looked through the code and find the code well-organized, well-commented, and well-documented. 

I also read through the demo the authors present at MICAAI educational challenge, which gives a clear and successful demonstration of the code.

**Comment by mathpluscode** [comment]
Hi, @zhangfanmark thanks a lot for your review and comments. Please let us know if you experienced any bugs and issues (We are currently working on the demo issues you mentioned in #478 and will fix the demos and add a test soon, as mentioned in #344).

**Comment by mathpluscode** [comment]
Hi @zhangfanmark  thank you again for your review. I'm closing this as we are preparing for the acceptance and the release of `v0.1.0`.
