### ISSUE TITLE
[JOSS Review] Paper Review Summary 

### ISSUE THREAD

**Issue by zhangfanmark** [DeepRegNet/DeepReg#480]
I'm reviewing the DeepReg paper on JOSS (openjournals/joss-reviews/issues/2705).

The paper gives a clear high-level description of DeepReg and it is well written.

If space allowed, I would suggest briefly introducing the underlying algorithms (e.g., some of the text in your MIICCAI challenge demo). Also, "Statement of need" can improved by a more clear comparison to "the existing open-sourced registration projects".

**Comment by mathpluscode** [comment]
Hi, @zhangfanmark thanks for your comments.

Regarding the introduction of the algorithms, we had them in the paper originally however it needs more than 200 words while we already have ~800 words currently. As a result, we could not include them in the JOSS paper.

Regarding the existing open-sourced registration projects, we've mentioned
1. Deep learning based project like VoxelMorph. So far we are not aware of other related projects. Please feel free to suggest more.
2. Classical projects like NiftiReg, SimpleElastix and AirLab.

Your suggestion is about adding more projects or adding more details about these projects?

For classical projects, there is limited information to add as we are focusing on different methods. For VoxelMorph, we can update the text to point out some other problems like lack of tests.

**Comment by mathpluscode** [comment]
@zhangfanmark Hi, we've updated the paper regarding your comments, ref https://github.com/DeepRegNet/DeepReg/commit/38caa466fee6b149c36353953e5ee262f03e576b. Please feel free to reopen this issue in case of further comments/reviews.
