### ISSUE TITLE
[JOSS Review] Classical registration demos 

### ISSUE THREAD

**Issue by lbrea** [DeepRegNet/DeepReg#483]
Hi, I'm reviewing the JOSS submission (https://github.com/openjournals/joss-reviews/issues/2705)

I've successfully run all the demos, but on the two examples of classical registration, 

`python3 demos/classical_mr_prostate_nonrigid/demo_register.py`

and 

`python3 demos/classical_ct_headneck_affine/demo_register.py`

the execution finishes with the following error:

`Traceback (most recent call last):`
`  File "demos/classical_mr_prostate_nonrigid/demo_register.py", line 126, in <module>`
`    save_dir=SAVE_PATH, arr=arr, name=arr_name, normalize=True, save_png=False`
`TypeError: save_array() got an unexpected keyword argument 'normalize'`

**Comment by YipengHu** [comment]
@mathpluscode is this being dealt with at #344 ?

**Comment by mathpluscode** [comment]
> @mathpluscode is this being dealt with at #344 ?

Yes, all demos should work directly after resolving #344, as tests will be included.

**Comment by mathpluscode** [comment]
Hi @lbrea, the mentioned demo has been fixed in #470. Now all demos have been tested. Please feel free to try again and let us know in case of any problems?

**Comment by mathpluscode** [comment]
Hi @lbrea thank you again for your review. I'm closing this as we are preparing for the acceptance and the release of `v0.1.0`.
