### ISSUE TITLE
migrate travis ci from org to com

### ISSUE THREAD

**Issue by mathpluscode** [DeepRegNet/DeepReg#491]
## Subject of the code / test

As mentioned in
- https://twitter.com/travisci/status/1322118491927957505?s=20
- https://docs.travis-ci.com/user/migrate/open-source-repository-migration

Travis is moving open-sourced project from .org to .com.
Therefore, we need to do the migration as documented ;)

The reason to ask is now the travis-ci.org is becoming slower due to this migration :(
So it'd be nice to migrate it asap.
![image](https://user-images.githubusercontent.com/4066929/97764229-d824aa00-1b05-11eb-983a-c7015f395ee9.png)

@NMontanaBrown @YipengHu @zacbaum are you ok? It should be just some clicks.

Actions will be
1. Click migration
2. Change PR requirements acc to https://docs.travis-ci.com/user/migrate/open-source-repository-migration#do-i-need-to-make-any-other-changes
3. Replace links inside repo from travis-ci.org to travis-ci.com

**Comment by YipengHu** [comment]
agreed

**Comment by NMontanaBrown** [comment]
Can, will do. @YipengHu @mathpluscode
