### ISSUE TITLE
Minor Typos mainly

### ISSUE THREAD

**Issue by MattClarkson** [DeepRegNet/DeepReg#496]
## Subject of the documentation
Minor typos as I read through some docs.

What are you trying to do and which part of the code is hard to understand or incorrect
or missing? Please provide a link to the readthedocs page and code if available.

I'm just pretending Im a complete beginner.

If the documentation request is approved, would you be willing to submit a PR? _(Help
can be provided if you need assistance submitting a PR)_

Sure.

# Suggestions:

* "Intensity based loss is modality-independent" sounds wrong or needs further clarification, as for example, SSD won't work on MR-CT registration. So, choice of loss function is dependent on modality.
* "measures the deformation to regularize the transformation." sounds wierd. I'd say "measures the amount of deformation, such that too severe a deformation can be penalised', as beginners may not understand that much about regularization.
* If I was a newcomer, I'd probably be lazy, and not read learn2reg. Then, by the time I had finished the first Tutorial section, I am still wondering ... "well, what sort of network is DeepReg implementing?". I'm just reading straight through the docs, and haven't seen a description of the main network.
* For adding custom loss functions, it seems odd to modify core functionality in ```dissimilarity_fn```. This is the sort of thing that should be solved with dependency injection, using a Strategy pattern, rather then editing an elif.
* Looking at ```build_backbone```, again, we are having to edit core DeepReg code. This could be improved by using an Factory pattern. 
* Both these suggestions of a StrategyPattern or Factory pattern are optional. Its more relevant for compiled code which needs to be extensible. Might be overkill for a Python/Research project. 
* The demo page for "Paired CT Lung registration", doesn't give any examples or pictures. So, its not really saying any more than the instructions on how to run the command line apps. While there is a link to source code, there is no explanation of it. 
* Same comment for several demos. Needs pictures.

**Comment by YipengHu** [comment]
- Good point on the network. We should at least add a pointer to the API ref where the different architectures, Local/Global U-Nets are described with references.
- Strategy/factory patterns worth separate tickets? @mathpluscode what do you think?
- The pictorial addition to the demos have also been mentioned by @ebonmati - do we have a ticket for this? Just have not got around to add them.

**Comment by mathpluscode** [comment]
For the strategy/factory pattern, @MattClarkson could you provide some link to some examples?

I agree that adding if/else is not a good option, this can be handled with some registration method, like you register your custom loss/model, like https://github.com/ray-project/ray/blob/master/rllib/examples/custom_keras_model.py#L100.

**Comment by NMontanaBrown** [comment]
> * Good point on the network. We should at least add a pointer to the API ref where the different architectures, Local/Global U-Nets are described with references.
> * Strategy/factory patterns worth separate tickets? @mathpluscode what do you think?
> * The pictorial addition to the demos have also been mentioned by @ebonmati - do we have a ticket for this? Just have not got around to add them.

@YipengHu jumping on this at the mention of missing tickets, did we open all the tickets from prior DeepReg meeting? If not, shall I open tickets from our previous "deepreg dev ideas" ticket?

**Comment by YipengHu** [comment]
> > * Good point on the network. We should at least add a pointer to the API ref where the different architectures, Local/Global U-Nets are described with references.
> > * Strategy/factory patterns worth separate tickets? @mathpluscode what do you think?
> > * The pictorial addition to the demos have also been mentioned by @ebonmati - do we have a ticket for this? Just have not got around to add them.
> 
> @YipengHu jumping on this at the mention of missing tickets, did we open all the tickets from prior DeepReg meeting? If not, shall I open tickets from our previous "deepreg dev ideas" ticket?

tbh, i lost track on this. I believe it is time for specific idea ticket now? feel free to open new ones, i will check again this week.

**Comment by NMontanaBrown** [comment]
> > > * Good point on the network. We should at least add a pointer to the API ref where the different architectures, Local/Global U-Nets are described with references.
> > > * Strategy/factory patterns worth separate tickets? @mathpluscode what do you think?
> > > * The pictorial addition to the demos have also been mentioned by @ebonmati - do we have a ticket for this? Just have not got around to add them.
> > 
> > 
> > @YipengHu jumping on this at the mention of missing tickets, did we open all the tickets from prior DeepReg meeting? If not, shall I open tickets from our previous "deepreg dev ideas" ticket?
> 
> tbh, i lost track on this. I believe it is time for specific idea ticket now? feel free to open new ones, i will check again this week.

Done.

**Comment by mathpluscode** [comment]
So here we have mainly three type of issues

1. typos
2. registering custom functionalities, a dedicated issue has been created #517 
3. demos need more visualization of results #474 

So I suggest to leave this issue open only for the mentioned typos, if it hasn't been taken care of in https://github.com/DeepRegNet/DeepReg/pull/516. Actually, @agrimwood would you mind correcting a few more typos ^^

**Comment by agrimwood** [comment]
I'll take a look. Is there anyway we can maintain this issue as a place for people to record typos etc? there are bound to be more mistakes in future...

**Comment by mathpluscode** [comment]
> I'll take a look. Is there anyway we can maintain this issue as a place for people to record typos etc? there are bound to be more mistakes in future...

it's fine... I added the tag `typo` so we can just keep creating issues with this tag?
