### ISSUE TITLE
post release v0.1.0

### ISSUE THREAD

**Issue by mathpluscode** [DeepRegNet/DeepReg#502]
## Subject of the issue

- Update logo to remove beta
- Update readme regarding citation

**Comment by zacbaum** [comment]
> * [ ]  Release to PyPI automatically

Is already covered in #408? I will use this ticket to PR changes to README.md re: citation, logo updates and other misc changes. Landing page changes will be done once approved here (for consistency).

Zenodo config may be better as its own ticket? Quite a separate issue...?

**Comment by mathpluscode** [comment]
> > * [ ]  Release to PyPI automatically
> 
> 
> 
> Is already covered in #408? I will use this ticket to PR changes to README.md re: citation, logo updates and other misc changes. Landing page changes will be done once approved here (for consistency).
> 
> 
> 
> Zenodo config may be better as its own ticket? Quite a separate issue...?

Yeah I will use this issue for Zenodo then ;)

**Comment by zacbaum** [comment]
> > > * [ ]   Release to PyPI automatically
> > 
> > 
> > Is already covered in #408? I will use this ticket to PR changes to README.md re: citation, logo updates and other misc changes. Landing page changes will be done once approved here (for consistency).
> > Zenodo config may be better as its own ticket? Quite a separate issue...?
> 
> Yeah I will use this issue for Zenodo then ;)

Had already created a PR for readme updates which referred to this... as mentioned above: "I will use this ticket to PR changes to README.md re: citation, logo updates and other misc changes."

@mathpluscode, could you create a new ticket for the zenodo config and revert the text in the ticket name and description?

**Comment by mathpluscode** [comment]
> > > > * [ ]    Release to PyPI automatically
> > > 
> > > 
> > > Is already covered in #408? I will use this ticket to PR changes to README.md re: citation, logo updates and other misc changes. Landing page changes will be done once approved here (for consistency).
> > > Zenodo config may be better as its own ticket? Quite a separate issue...?
> > 
> > 
> > Yeah I will use this issue for Zenodo then ;)
> 
> Had already created a PR for readme updates which referred to this... as mentioned above: "I will use this ticket to PR changes to README.md re: citation, logo updates and other misc changes."
> 
> @mathpluscode, could you create a new ticket for the zenodo config and revert the text in the ticket name and description?

ah sorry lol.... emm let me try ;)
