### ISSUE TITLE
Add CMIC seminar to docs

### ISSUE THREAD

**Issue by NMontanaBrown** [DeepRegNet/DeepReg#508]
## Subject of the documentation

What are you trying to do and which part of the code is hard to understand or incorrect
or missing?

We gave a CMIC seminar introducing DeepReg, and there should be a recording online. Get in touch with Marco Palombo for a link and add this to the landing page and repo README.

If the documentation request is approved, would you be willing to submit a PR?

Yes

**Comment by mathpluscode** [comment]
This is also mentioned in #502 ;)

**Comment by NMontanaBrown** [comment]
> This is also mentioned in #502 ;)

Keep it separate - think it's not directly linked to release itself?

**Comment by mathpluscode** [comment]
> > This is also mentioned in #502 ;)
> 
> 
> 
> Keep it separate - think it's not directly linked to release itself?

Sure will remove that then.

**Comment by NMontanaBrown** [comment]
Can someone check that this [link](https://eu.bbcollab.com/collab/ui/session/playback/load/941325351b64410eb886bbaf9aa64fb9?authToken=eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJiYkNvbGxhYkFwaSIsInJlY29yZGluZ1VpZCI6Ijk0MTMyNTM1MWI2NDQxMGViODg2YmJhZjlhYTY0ZmI5IiwiaXNzIjoiYmJDb2xsYWJBcGkiLCJ0eXBlIjoxLCJleHAiOjE2MDYyMjc4NTIsImlhdCI6MTYwNjIyNDI1MiwiY29uc3VtZXIiOiI4NmU2YWQ3YzVlZDU0NzhlOGViMTQyODUyYWNiYzA5ZiJ9.VZIJqu3q4dVSkEy7X6sysvxWK5d_Xj9cvOSmG9sdZ_U&name=CMIC%252FWEISS%20joint%20seminar%20series%20-%20Wedn.%204th%20November%20-%20recording_1) works? @mathpluscode @YipengHu @zacbaum

**Comment by zacbaum** [comment]
> Can someone check that this [link](https://eu.bbcollab.com/collab/ui/session/playback/load/941325351b64410eb886bbaf9aa64fb9?authToken=eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJiYkNvbGxhYkFwaSIsInJlY29yZGluZ1VpZCI6Ijk0MTMyNTM1MWI2NDQxMGViODg2YmJhZjlhYTY0ZmI5IiwiaXNzIjoiYmJDb2xsYWJBcGkiLCJ0eXBlIjoxLCJleHAiOjE2MDYyMjc4NTIsImlhdCI6MTYwNjIyNDI1MiwiY29uc3VtZXIiOiI4NmU2YWQ3YzVlZDU0NzhlOGViMTQyODUyYWNiYzA5ZiJ9.VZIJqu3q4dVSkEy7X6sysvxWK5d_Xj9cvOSmG9sdZ_U&name=CMIC%252FWEISS%20joint%20seminar%20series%20-%20Wedn.%204th%20November%20-%20recording_1) works? @mathpluscode @YipengHu @zacbaum

Works for me in an incognito chrome tab - so should be good for public use.
