### ISSUE TITLE
Add image dissimilarity losses: global NCC, L1, TukeyBiweight

### ISSUE THREAD

**Issue by NMontanaBrown** [DeepRegNet/DeepReg#512]
## Subject of the feature

What are you trying to do and how would you want to do it differently?
From issue #424 
@acasamitjana  suggested adding new losses to the project.
"Mutual information (specially to compare with other intermodal registrations methods), Tukey Biweight (a more robust SSIM metric)"

Is it something you currently you cannot do?
Yes

Is this related to an issue/problem?
No.

Has the feature been requested before? If yes, please provide a link to the issue.
No.

If the feature request is approved, would you be willing to submit a PR? 

M.

**Comment by mathpluscode** [comment]
Hi @acasamitjana could you add a bit more details on these two losses, like paper/example code/reference? So that if anyone else is interested in this ticket, they can do it as well ;)

**Comment by acasamitjana** [comment]
Hi @mathpluscode I have updated the title. I have them implemented in pytorch in a personal repo so I just have to copy-paste (almost).

For anyone trying to follow the ticket:
- L1 and Tukey Biweight are metrics at the pixel level more robust than the already implemented SSD. Concretely, Tukey biweight has the shape of L2 but clipped at a certain value. It may be useful in some applications such as intermodal registration where a certain structure is shown in one modality but not in the other.
- Global NCC may be beneficial for some applications and it's faster than LNCC.

**Comment by mathpluscode** [comment]
> Hi @mathpluscode I have updated the title. I have them implemented in pytorch in a personal repo so I just have to copy-paste (almost).
> 
> 
> 
> For anyone trying to follow the ticket:
> 
> - L1 and Tukey Biweight are metrics at the pixel level more robust than the already implemented SSD. Concretely, Tukey biweight has the shape of L2 but clipped at a certain value. It may be useful in some applications such as intermodal registration where a certain structure is shown in one modality but not in the other.
> 
> - Global NCC may be beneficial for some applications and it's faster than LNCC.
> 
> 

@acasamitjana sure! Then feel free to do it anytime. I will update you if the way of adding losses got changed.

**Comment by mathpluscode** [comment]
@acasamitjana where are we on this? ^^ with new registry, this should be super easy to do now!
