### ISSUE TITLE
Apply DDF transformation as data augmentation

### ISSUE THREAD

**Issue by NMontanaBrown** [DeepRegNet/DeepReg#513]
## Subject of the feature

What are you trying to do and how would you want to do it differently?
From issue #424 and @acasamitjana 
"Data augmentation: apart from the existing AffineTF, we can include DDF transformations as well"

Is it something you currently you cannot do?
Unsure.

Is this related to an issue/problem?
No.

Has the feature been requested before? If yes, please provide a link to the issue.
No.

If the feature request is approved, would you be willing to submit a PR?

M.

**Comment by acasamitjana** [comment]
I'm not entirely sure how to proceed with that. As per my understanding of the code, one option is:
- Define a DDFTransformation3D class in dataset/preprocess.py that generates a smooth DDF and applies it to the input images.
- Specify the options in the config file under the preprocess field that is passed to get_dataset_and_preprocess():
   (1) DDF_DA=[True, False]
   (2) Field strength
   (3) Low-resolution size of the field to induce more realistic smooth deformation fields.

@mathpluscode do you any insights on how to implement it?

**Comment by mathpluscode** [comment]
@acasamitjana it sounds good, I'm thinking about refactoring this mechanism related to the registration of custom methods, similar to the transforms in pytorch. Make it easy and optional to apply augmentations. So at this stage your plan looks nice and feel free to go ahead and I will come back with more details later.

**Comment by YipengHu** [comment]
> I'm not entirely sure how to proceed with that. As per my understanding of the code, one option is:
> 
> * Define a DDFTransformation3D class in dataset/preprocess.py that generates a smooth DDF and applies it to the input images.
> * Specify the options in the config file under the preprocess field that is passed to get_dataset_and_preprocess():
>   (1) DDF_DA=[True, False]
>   (2) Field strength
>   (3) Low-resolution size of the field to induce more realistic smooth deformation fields.
> 
> @mathpluscode do you any insights on how to implement it?

This has been used for others but mainly in an ad hoc fashion. What is your field strength here?

**Comment by acasamitjana** [comment]
>  What is your field strength here?

It refers to the variance of the random field. E.g: low_res_field = field_strength*np.random.randn(field_shape)
You can even play with different field strenghts by choosing it randomly (uniform): field_strengh = (upper_bound-lower_bound) * np.random.rand(1) + lower_bound

**Comment by YipengHu** [comment]
> > What is your field strength here?
> 
> It refers to the variance of the random field. E.g: low_res_field = field_strength*np.random.randn(field_shape)
> You can even play with different field strenghts by choosing it randomly (uniform): field_strengh = (upper_bound-lower_bound) * np.random.rand(1) + lower_bound

sounds good - some what to normalise it to [0,1] would be nice - by the CP spacing maybe?

**Comment by acasamitjana** [comment]
I have added a preliminary version. @mathpluscode @YipengHu  can you take a look?
You'll find that:
- I have adopted a similar approach to AffineTransformation3D
- Configuration files include more options under 'preprocess'. Changes are not backward compatible as I add a new mandatory key under 'preprocess' ('da_method'). You could see an examples on the unpaired_mr_brain demo.

Please, take a look before I start writing the tests. Many thanks!

**Comment by YipengHu** [comment]
> I have added a preliminary version. @mathpluscode @YipengHu or anyone else, can you take a look?
> You'll find that:
> 
> * I have adopted a similar approach to AffineTransformation3D
> * Configuration files include more options under 'preprocess'. Changes are not backward compatible as I add a new mandatory key under 'preprocess' ('da_method'). You could see an examples on the unpaired_mr_brain demo.
> 
> Please, take a look before I start writing the tests. Many thanks!

How about change this to a WIP PR - easier to see the changes?

**Comment by mathpluscode** [comment]
@acasamitjana can you create a PR for your branch? If I do that I won't be able to review lol.
