### ISSUE TITLE
Resampler with flexible shape for DDF

### ISSUE THREAD

**Issue by NMontanaBrown** [DeepRegNet/DeepReg#514]
## Subject of the feature

What are you trying to do and how would you want to do it differently?
Raised by @acasamitjana in issue #424 
Incorporate the option to resize deformation fields? The motivation behind is: (a) the associated notion of "control points" (e.g. if resize=4, we'll have control points every 4 pixels with linear interpolation to full size) (b) produces smooth DDF (c) DVF integration is faster.

Is it something you currently you cannot do?
Yes.

Is this related to an issue/problem?
No.

Has the feature been requested before? If yes, please provide a link to the issue.
No.

If the feature request is approved, would you be willing to submit a PR?

M.

**Comment by mathpluscode** [comment]
My current understanding is that, we would like to have a resampler that accepts DDF which has a different shape from the image? @acasamitjana

**Comment by acasamitjana** [comment]
That's right. The idea is to have a low resolution deformation field (i.e. control points). Then the resampler would interpolate the field between control points using the interpolation method of choice (e.g., linear, or bsplines #372 )

The original title (resizing) was more about the implementation:

- One option is to make the decoder path of the UNet flexible enough to choose to output feature maps at lower resolution. However, I believe this is constrained to low-res sizes of 2^n_steps.

- The other option is to leave the UNet as it is and use a Resizing layer that downsamples the full image to the desired size. To downsample we could use any of the pooling operations, strided convolutions with pre-computed kernels (e.g. mean kernel) or more generally, the resize functionality in _layer_utils_.  I believe this approach is more flexible and you can specify any size for the low-res DDF (e.g., specifying the distance between control points).

**Comment by mathpluscode** [comment]
> That's right. The idea is to have a low resolution deformation field (i.e. control points). Then the resampler would interpolate the field between control points using the interpolation method of choice (e.g., linear, or bsplines #372 )
> 
> 
> 
> The original title (resizing) was more about the implementation:
> 
> 
> 
> - One option is to make the decoder path of the UNet flexible enough to choose to output feature maps at lower resolution. However, I believe this is constrained to low-res sizes of 2^n_steps.
> 
> 
> 
> - The other option is to leave the UNet as it is and use a Resizing layer that downsamples the full image to the desired size. To downsample we could use any of the pooling operations, strided convolutions with pre-computed kernels (e.g. mean kernel) or more generally, the resize functionality in _layer_utils_.  I believe this approach is more flexible and you can specify any size for the low-res DDF (e.g., specifying the distance between control points).

@acasamitjana we can split it in some steps:

1. Extend sampler to accept different shapes. Add tests etc.
2. Extend the Local Net / U-Net, but I was planning to refactor the networks anyway... need to think a bit more in this to ensure demos will be still working.

**Comment by acasamitjana** [comment]
>     2. Extend the Local Net / U-Net, but I was planning to refactor the networks anyway... need to think a bit more in this to ensure demos will be still working.

I think that an easy way is not refactoring the networks nor the resampler but extending the method ['ddf', 'dvf'] to include the option of control points and interpolation method ['linear', 'bsplines']. This could be easily specified in the config file. Then, the data flow would be: inputs --> backbone network --> resize to control points (if applies) --> method --> resampler --> loss

Let me know what you think is best! This will influence also Issue #372, so I pause both until we decide.

**Comment by mathpluscode** [comment]
@acasamitjana oh I see, you saying the network outputs a smaller size of DDF then we add an layer which upsamples this DDF? This sounds easy and promising.

The way I was thinking was to save compute but it can be tricky.
