### ISSUE TITLE
Fix dead link for visualize tool

### ISSUE THREAD

**Issue by mathpluscode** [DeepRegNet/DeepReg#515]
## Subject of the documentation

What are you trying to do and which part of the code is hard to understand or incorrect
or missing? Please provide a link to the readthedocs page and code if available.

https://deepreg.readthedocs.io/en/latest/docs/cli.html#visualise

Click the link in `See more details in its usage documentation.` and it goes 404.

Oh the doc is here https://github.com/DeepRegNet/DeepReg/blob/main/docs/source/docs/visualisation_tool.md.

The relative place doesnt work the sameway as in markdown.

Also, change visualise to visualize ^^ in favor of us english.

**Comment by mathpluscode** [comment]
Btw we need more detailed docs for this tool?
I have the png outputs and I literally just want to assemble them into one gif inside the folder :(

**Comment by NMontanaBrown** [comment]
Visualise to visualize? You heathen! @mathpluscode

**Comment by mathpluscode** [comment]
Besides this, I'm wondering what is the functionalities this CLI tool is offering against https://ffmpeg.org tool? @YipengHu

**Comment by NMontanaBrown** [comment]
> Besides this, I'm wondering what is the functionalities this CLI tool is offering against https://ffmpeg.org tool? @YipengHu

Better to work on the docs then?

**Comment by YipengHu** [comment]
> > Besides this, I'm wondering what is the functionalities this CLI tool is offering against https://ffmpeg.org tool? @YipengHu
> 
> Better to work on the docs then?

automation?

**Comment by mathpluscode** [comment]
Fixed in #638.
