### ISSUE TITLE
Current Build On Main Failing

### ISSUE THREAD

**Issue by NMontanaBrown** [DeepRegNet/DeepReg#528]
## Subject of the issue

Current build is failing. 

"The command "pytest test/demo/ -k test_single_config_demo[unpaired_mr_brain]" exited with 1."

It seems to be a demo test? See [Travis.](https://travis-ci.com/github/DeepRegNet/DeepReg/jobs/431630539)

If the bug is confirmed, would you be willing to submit a PR? _(Help can be provided if
you need assistance submitting a PR)_

Yes

## Your environment

N/A, this is from the CI.

**Comment by mathpluscode** [comment]
It seems to be a problem linked to the data downloading

> E               RuntimeError: Command python demos/unpaired_mr_brain/demo_data.py return with err 1 b'Downloading data from https://cmiclab.cs.ucl.ac.uk/acasamitjana/learn2reg_t4/-/raw/master/L2R_Task4_HippocampusMRI.tar\n'

@acasamitjana Do you think we can move the data to github?
