### ISSUE TITLE
Bug: Clash Between Functions For Generating Indices

### ISSUE THREAD

**Issue by NMontanaBrown** [DeepRegNet/DeepReg#531]
## Subject of the issue

Whilst working on #525 #54 I was going through the DataLoaders. The base clase, DataLoader takes specific arguments such as "all", "sample" or None as args, but doesn't take "first":

[base DataLoader class that doesn't take "first" as one of the arguments](https://github.com/DeepRegNet/DeepReg/blob/7e5faf194b6917b3d6b3f1e967d02cb1c19443e3/deepreg/dataset/loader/interface.py#L39)

which is one of the args that is passed to the util:

[which generates the indices](https://github.com/DeepRegNet/DeepReg/blob/db76a33cb3e41a96594626ccf6e3900d3cfa720d/deepreg/dataset/util.py#L62(

**Comment by NMontanaBrown** [comment]
(Not covered in the DataLoader test)[https://github.com/DeepRegNet/DeepReg/blob/6fed617c5f9fb08b1a401e333489e996fbdc9033/test/unit/test_interface.py#L30]

**Comment by NMontanaBrown** [comment]
- [Not covered in unpaired loader](https://github.com/DeepRegNet/DeepReg/blob/main/test/unit/test_unpaired_loader.py) via a ctrl-f of "first"
- [Not covered in paired loader](https://github.com/DeepRegNet/DeepReg/blob/main/test/unit/test_paired_loader.py) via a ctrl-f of "first"
- [Not covered in nifti loader](https://github.com/DeepRegNet/DeepReg/blob/main/test/unit/test_nifti_loader.py) cia a ctrl0f of "sample_label"
- [Not covered in h5 loader](https://github.com/DeepRegNet/DeepReg/blob/main/test/unit/test_h5_loader.py)
- [Not covered in grouped loader](https://github.com/DeepRegNet/DeepReg/blob/main/test/unit/test_grouped_loader.py)
- [Not covered in dataset load test](https://github.com/DeepRegNet/DeepReg/blob/main/test/unit/test_dataset_load.py)

**Comment by NMontanaBrown** [comment]
Pytest fails any tests where "first" are passed to sample_label.

E       AssertionError: sample_label must be sample or all or None, got first

**Comment by mathpluscode** [comment]
@NMontanaBrown let's remove `first`? it's an old option linked back to some strange dataset. It was back then I want to only evaluate on the first label. But now we always evaluate on all labels and the results per label will be summarized.

**Comment by NMontanaBrown** [comment]
Ok, undoing.

**Comment by mathpluscode** [comment]
> Ok, undoing.

Still worth a PR to remove `first` from all existing place ^^. thx to spot this out!
