### ISSUE TITLE
Wrong bias initialization in GlobalNet

### ISSUE THREAD

**Issue by mathpluscode** [DeepRegNet/DeepReg#533]
## Subject of the issue

In `GlobalNet`, the bias of the dense layer to output `theta` is wrong. 

```python
>>> x=tf.constant([1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0])
>>> tf.reshape(x,(4,3))
<tf.Tensor: shape=(4, 3), dtype=float32, numpy=
array([[1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 0.],
       [0., 1., 0.]], dtype=float32)>
```

It should be the flatten `eye(4,3)` as follows:

```python
>>> tf.reshape(tf.eye(4,3),shape=(-1))
<tf.Tensor: shape=(12,), dtype=float32, numpy=array([1., 0., 0., 0., 1., 0., 0., 0., 1., 0., 0., 0.], dtype=float32)>
```

The reason of such initialization is too ensure the initial transformation is close to identical transformation.

To be sure, we can add one more test for `warp_grid` with identical theta https://github.com/DeepRegNet/DeepReg/blob/main/deepreg/model/layer_util.py#L433.

@YipengHu @RemiDelaunay Please confirm if you agree ;)

Great thanks to @jvhoutte for the bug report.

**Comment by YipengHu** [comment]
I can confirm this initilisation is incorrectly configured, when converted from label-reg which uses a 3-by-4 format. I will have another look see if any other potential implications if we keep the current `warp_grid`. Will report back.
