### ISSUE TITLE
more dice score definition

### ISSUE THREAD

**Issue by mathpluscode** [DeepRegNet/DeepReg#535]
## Subject of the feature

For the dice, the current definition is https://github.com/DeepRegNet/DeepReg/blob/main/deepreg/model/loss/label.py#L149.
It corresponds to the definition in https://arxiv.org/abs/1707.03237. But in https://arxiv.org/abs/1606.04797, the terms in the denominator are squared.

Two forms are identical in the binary case as the square of 1 is 1.
But when `y_true` and `y_pred` are probabilities. As far as I know, there's no closed-form. Both formulations are an approximation.

In https://en.wikipedia.org/wiki/Sørensen–Dice_coefficient, dice score is defined as `2TP/(2TP+FP+FN)`. If we consider N i.i.d. voxel with `y_true=p`, which means with 100*p%, the voxel is foreground. Similarly, let `y_pred=q`. Then we expect `TP=pq*N, FP=(1-p)q*N, FN=p(1-q)*N`. This gives the non-squared version.

Therefore it could be nice to provide the square option in case anyone wants it. No need to change the default definition.

**Comment by mathpluscode** [comment]
I did a small simulation, assuming all voxels i.i.d., and we sample their labels and predictions randomly. It seems that the non-squared version is closer to the estimation.

```python
import numpy as np

n = 10000000
p = 0.2  # true
q = 0.3  # pred

t1 = 2*p*q/(p+q)
t2 = 2*p*q/(p*p+q*q)

y_true = (np.random.uniform(0, 1, n) <= p) * 1
y_pred = (np.random.uniform(0, 1, n) <= q) * 1

x = 2*np.sum(y_true*y_pred) / np.sum(y_true+y_pred)

print(t1, t2, x)
```

which prints

```
0.24 0.923076923076923 0.24016857302351768
```

**Comment by mathpluscode** [comment]
@QianyeYang check this :D

**Comment by tvercaut** [comment]
There is no bullet-proof answer to the question of how to implement the soft Dice for deep learning purposes. Different justification lead to different choices (square, non-square, what epsilons and where, foreground only or average between foreground and background dice, how to handle multi-classes, batch version, etc.). Many of the issues arise when you have ground truth with 0 foreground voxels. At least in our experience, the batch version of the soft Dice really helps the training.

If you are interested in that rabbit hole, here are some pointers:
https://github.com/Project-MONAI/MONAI/issues/807
https://arxiv.org/abs/1707.00478
Section 3.6.1 in https://mediatum.ub.tum.de/doc/1395260/1395260.pdf

**Comment by mathpluscode** [comment]
> Project-MONAI/MONAI#807

Hi @tvercaut, thanks so much for the pointers! The discussions are quite detailed!

If my understanding is correct, the batched version is to sum over only spatial axes for the numerator and denominator. Then we have dice score for each channel and each sample in the batch.

Regarding the smooth, it seems like in MONAI you've put it on both numerator and denominator despite some discussion of smooth1 and smooth2. I guess this doesn't really make a big difference in terms of the training stability.

By chance, our current setting is the same as MONAI default one (except our smooth is 1e-7).

**Comment by mathpluscode** [comment]
I'm closing this issue as I believe there's no need to change for now :)

**Comment by YipengHu** [comment]
I re-open this as a top experiment suggested:
- with eps on nominator having 0 (or very small one like a landmark) foreground reference standards, the loss is insensitive to the size of the predicted labels, as (N+eps)/(N+eps) = 1.
-  i suggest to implement a batch-wise Dice as Tom suggested, which should mitigate this issue to a degree

**Comment by YipengHu** [comment]
EDIT: a new ticket may be better - sorry
