### ISSUE TITLE
New demo for globalnet

### ISSUE THREAD

**Issue by YipengHu** [DeepRegNet/DeepReg#536]
## Subject of the feature

@jvhoutte suggested to add a demo using the global net predicting affine transformation. The alterntive may be to add an option and trained network in one of the existing demos.

What are you trying to do and how would you want to do it differently?

Still open to suggestions, but simply adding an trained affine network option.

Is this related to an issue/problem?
To a bug report #533 

Has the feature been requested before? If yes, please provide a link to the issue.
no

If the feature request is approved, would you be willing to submit a PR? _(Help can be
provided if you need assistance submitting a PR)_

yes

**Comment by mathpluscode** [comment]
Which dataset are we considering here? @jvhoutte @YipengHu

**Comment by YipengHu** [comment]
Suggest:
- a new set of results for the paired lung ct demo: 
code: https://github.com/DeepRegNet/DeepReg/tree/main/demos/paired_ct_lung
doc: https://github.com/DeepRegNet/DeepReg/blob/main/docs/source/demo/paired_ct_lung.rst

Not sure it needs to edit any functions at this stage, but the related functions may be here: https://github.com/DeepRegNet/DeepReg/blob/main/deepreg/model/backbone/global_net.py

**Comment by YipengHu** [comment]
@acasamitjana As a student is interested in looking at #703, are you interested in looking at this ticket instead?

**Comment by acasamitjana** [comment]
Okey. In your previous comment, are you suggesting to update the paired_ct_lung demo or to create a new one using the same dataset?

**Comment by YipengHu** [comment]
> Okey. In your previous comment, are you suggesting to update the paired_ct_lung demo or to create a new one using the same dataset?

either is fine, maybe start with changing the paired ct? if we identify anything better, we can always update

**Comment by acasamitjana** [comment]
`extract_levels` parameter is deprecated. How should we deal with that? Maybe opening an issue targeting some RC milestone? I believe that applies to GlobalNet as well as UNet, right?

**Comment by YipengHu** [comment]
> `extract_levels` parameter is deprecated. How should we deal with that? Maybe opening an issue targeting some RC milestone? I believe that applies to GlobalNet as well as UNet, right?

GlobalNet should have never used `extract_levels`. You can safely ignore this for GlobalNet.
