### ISSUE TITLE
Add 2D-3D Registration Functionality

### ISSUE THREAD

**Issue by agrimwood** [DeepRegNet/DeepReg#542]
## Subject of the feature
DeepReg feature request to be able to register 2D images to 3D volumes.
Currently unavailable feature, low priority for now.

Has the feature been requested before? If yes, please provide a link to the issue.

If the feature request is approved, would you be willing to submit a PR? _(Help can be
provided if you need assistance submitting a PR)_

Yes

**Comment by YipengHu** [comment]
@mathpluscode @agrimwood what is the plan for this ticket? i'm a bit lost of track with this...

**Comment by mathpluscode** [comment]
> @mathpluscode @agrimwood what is the plan for this ticket? i'm a bit lost of track with this...

I'd say, this will be after release 1.0.

**Comment by mathpluscode** [comment]
So, we are closing this issue unless this feature is required by users.
For now, in case we have 2D images, we can always treat it as 3D by adding an axis.
