### ISSUE TITLE
Optimise demo

### ISSUE THREAD

**Issue by agrimwood** [DeepRegNet/DeepReg#543]
## Subject of the issue
Adapt/modify/improve the demos, so that they perform well when applied to specific applications.  
  
Modifications could include:
-- hyperparameter tuning
-- dataset expansion
-- output validation/benchmarking

**Comment by mathpluscode** [comment]
The following demos are using `num_channel_initial: 4`
- paired_mrus_brain
- paired_ct_lung
- unpaired_ct_lung

So for these demos, we definitely need to update the pretrained models

**Comment by agrimwood** [comment]
Thanks for pointing this out @mathpluscode.
@YipengHu has also suggested lookig at the abdominal demo. I'll take a serious look at this before next week's meeting.

**Comment by YipengHu** [comment]
@agrimwood - let me know when you have the data ready. and i've changed this ticket for the abdomen one.

**Comment by YipengHu** [comment]
i'm closing this as specific demo ones will be generated.
