### ISSUE TITLE
Move CI to GitHub actions

### ISSUE THREAD

**Issue by mathpluscode** [DeepRegNet/DeepReg#544]
## Subject of the issue

- https://blog.travis-ci.com/2020-11-02-travis-ci-new-billing
- https://ropensci.org/technotes/2020/11/19/moving-away-travis/

As explained in the links above, Travis CI is changing their pricing plan, we need to check in more details
- whether it will impact us considering our current CI activities
- does GitHub action can do the same job and is it easy to move? If yes, maybe better to move earlier than later

**Comment by NMontanaBrown** [comment]
I think it's rather sad that Travis is moving away from free CI/CD for OS projects... So would support move to GHA.

**Comment by mathpluscode** [comment]
> Builds have been temporarily disabled for public repositories due to a negative credit balance. Please go to the Plan page to replenish your credit balance or alter your Consume paid credits for OSS setting.

OK.... We need to move.
