### ISSUE TITLE
save_png needs improved explanation in CLI docs

### ISSUE THREAD

**Issue by agrimwood** [DeepRegNet/DeepReg#550]
## Command Line Tools

> [## Predict](https://deepreg.readthedocs.io/en/latest/docs/cli.html#predict)
>> Optional Arguments:   

`--save_png` example usage seems contradictory, readthedocs states:

`--save_png,` for saving the outputs in png format.

`--save_png,` for not saving the outputs in png format. 

If the documentation request is approved, would you be willing to submit a PR? _(Help
can be provided if you need assistance submitting a PR)_

Yes

**Comment by mathpluscode** [comment]
ooops it should be --no-save_png :(

**Comment by mathpluscode** [comment]
I handled it in PR #568

**Comment by mathpluscode** [comment]
fixed in https://github.com/DeepRegNet/DeepReg/pull/568

see https://deepreg.readthedocs.io/en/latest/docs/cli.html#predict
