### ISSUE TITLE
Add demo showing an example of transfer learning / fine-tuning

### ISSUE THREAD

**Issue by ebonmati** [DeepRegNet/DeepReg#551]
## Subject of the feature

What are you trying to do and how would you want to do it differently?

It would be useful to have a simple example showing how to load a model and perform transfer learning or fine-tuning. 

Is it something you currently you cannot do?

It is rather a suggestion

Is this related to an issue/problem?

#507 

Has the feature been requested before? If yes, please provide a link to the issue.

If the feature request is approved, would you be willing to submit a PR? _(Help can be
provided if you need assistance submitting a PR)_

Yes

**Comment by YipengHu** [comment]
@ebonmati can you help to find someone working on this, or you would like to take this yourself?

**Comment by YipengHu** [comment]
i'm closing this in favour of https://github.com/DeepRegNet/DeepReg/discussions/731
