### ISSUE TITLE
Demo optimise - unpaired abdo CT

### ISSUE THREAD

**Issue by agrimwood** [DeepRegNet/DeepReg#552]
## Improve training/performance of unpaired abdo CT model

**This issue is an extension of [543](https://github.com/DeepRegNet/DeepReg/issues/543)**

Can we improve the demo so that the final trained model has practical utility for users' research?
tagging @YipengHu @ebonmati for now, feel free to assign yourself and others (can't find SB!)  
  
The easiest recommendation I can think of is to add more CT data, as previously discussed.  
If there are any more suggestions regarding hyperparameter tuning and/or model modifications please feel free to make recommendations.  
To begin, I will try to implement a simple improvement(s) before end of Jan.  
From February onwards, happy to introduce more complex improvements and even work towards transfer learning ticket.

**Comment by YipengHu** [comment]
@agrimwood - @ me know when you had a chance to have the data looked/ready.

**Comment by YipengHu** [comment]
> @agrimwood - @ me know when you had a chance to have the data looked/ready.

@agrimwood I am going to start to look at the data now, but do let me know if any progress from your side when you see this.

**Comment by agrimwood** [comment]
Hi, I had a look at the following at the start of December:
- Synapse data (requires signing up to d/l): 30 abdo CTs with 13 anatomical labels per volume.  
- Medical Decathlon: various image volumes organised by anatomical site, but can't find any labels.  
- Cancer Imaging Archive: 82 patient CTs with pancreas segmentations (contrast enhanced, non-pathalogical volunteers).

**Comment by mathpluscode** [comment]
Hi, @agrimwood  please let me know before you start training any models? Please be aware that PR #602 will change network structures and it's better to do any big training after the merge.

**Comment by agrimwood** [comment]
> Hi, @agrimwood please let me know before you start training any models? Please be aware that PR #602 will change network structures and it's better to do any big training after the merge.

Will do!
