### ISSUE TITLE
Refactoring models

### ISSUE THREAD

**Issue by mathpluscode** [DeepRegNet/DeepReg#557]
## Subject of the issue

We are now building models via functions. I'd like to refactor it into classes so that we can use the inheritance between classes to simplify part of the code. I personally find the current code quite confusing.

This is also a preparation for supporting more loss possibilities. However, there might be a risk that some demo will no longer work.

**Comment by YipengHu** [comment]
the classical registration ones will almost definitely break - maybe we should "officially" support these algorithms....?

**Comment by mathpluscode** [comment]
> the classical registration ones will almost definitely break - maybe we should "officially" support these algorithms....?

We will see when I do the change. The idea would be not breaking demos at least
