### ISSUE TITLE
GItHub's new feature discussion

### ISSUE THREAD

**Issue by mathpluscode** [DeepRegNet/DeepReg#572]
## Subject of the issue

GitHub has this new feature!

https://github.com/DeepRegNet/DeepReg/discussions

Any idea if we want to use it / how to use it :)?

I think the idea is to replace slack for some other OS projects.

@YipengHu @zacbaum @NMontanaBrown @acasamitjana @s-sd @ebonmati  (feel free to tag more lol)

**Comment by YipengHu** [comment]
I'm all up for new things ;)

**Comment by zacbaum** [comment]
We (as of now) tend to just use tickets/PRs for most of what is there.

Is there any benefit to moving some of those discussions elsewhere? To me, it feels like just another place to need to keep up-to-date with and check on regularly (a.k.a. more work 😉)

**Comment by mathpluscode** [comment]
> We (as of now) tend to just use tickets/PRs for most of what is there.
> 
> Is there any benefit to moving some of those discussions elsewhere? To me, it feels like just another place to need to keep up-to-date with and check on regularly (a.k.a. more work 😉)

Yup. Was thinking that discussion meant for more casual talks etc, as those issue template might be intimidating. But when checking another OS project, https://github.com/ray-project/ray/discussions/12424, seems like they didnt like this github feature. Wondering why.

Currently, my main questions are
- are their people using this package? if yes, what are their purpose (educationaly, research, industry, etc.)
- what do they feel about this? I guess it might not be super easy to use, so I'd like to know where we can improve. For instance, I believe the introduction of the registry is to make customized experiments easier, but would be better to get feedback :)

So I wonder if discussion pannel can encourage people to talk lol.

**Comment by zacbaum** [comment]
> > We (as of now) tend to just use tickets/PRs for most of what is there.
> > Is there any benefit to moving some of those discussions elsewhere? To me, it feels like just another place to need to keep up-to-date with and check on regularly (a.k.a. more work 😉)
> 
> Yup. Was thinking that discussion meant for more casual talks etc, as those issue template might be intimidating. But when checking another OS project, [ray-project/ray#12424](https://github.com/ray-project/ray/discussions/12424), seems like they didnt like this github feature. Wondering why.
> 
> Currently, my main questions are
> 
> * are their people using this package? if yes, what are their purpose (educationaly, research, industry, etc.)
> * what do they feel about this? I guess it might not be super easy to use, so I'd like to know where we can improve. For instance, I believe the introduction of the registry is to make customized experiments easier, but would be better to get feedback :)
> 
> So I wonder if discussion pannel can encourage people to talk lol.

In which case... May be worth setting something up, and putting a link on the readme, and RTD?

**Comment by mathpluscode** [comment]
@zacbaum A google form as questionnaire?

**Comment by mathpluscode** [comment]
Apparently @YipengHu has been using it already. Will close this issue. Please open new ones if we want to do questionnaires.
