### ISSUE TITLE
Demo optimise - paired lung ct

### ISSUE THREAD

**Issue by YipengHu** [DeepRegNet/DeepReg#575]
## Subject of the issue
Reduce the input data size
loss weights, init. no. channels
train longer

**Comment by YipengHu** [comment]
![2020-12-30 (2)](https://user-images.githubusercontent.com/2588157/103382568-796cb400-4ae7-11eb-80ff-f1c11642cfbb.png)

@mathpluscode @NMontanaBrown @s-sd Since you have/had worked on stuff related to the vessels/airways. This is a typical example that registration works as expected overall. But the smoothness is just not physically plausible! See the where vessels/airways have been "scrambled" to match the fixed image. It would be nice to have a different constraints between vessel structures and others. I am trying a couple things with DeepReg, any ideas?

**Comment by mathpluscode** [comment]
> ![2020-12-30 (2)](https://user-images.githubusercontent.com/2588157/103382568-796cb400-4ae7-11eb-80ff-f1c11642cfbb.png)
> 
> @mathpluscode @NMontanaBrown @s-sd Since you have/had worked on stuff related to the vessels/airways. This is a typical example that registration works as expected overall. But the smoothness is just not physically plausible! See the where vessels/airways have been "scrambled" to match the fixed image. It would be nice to have a different constraints between vessel structures and others. I am trying a couple things with DeepReg, any ideas?

Are you using losses on image? I guess an image-based loss can prevent this behavior.
Moreover, we can minimize the following distance,

Given a forground voxel in predicted image, so it's predicted to be foreground. Then it's shortest distance to the ground truth foreground should be minimized. Similar to haursdorf distance.

If we only have labels for organs, we can define foreground based on intensity.

**Comment by YipengHu** [comment]
> ground truth foreground

yes - it is using the image loss. what is "ground truth foreground"? it has labels for lungs, it is a large area.

**Comment by mathpluscode** [comment]
> > ground truth foreground
> 
> yes - it is using the image loss. what is "ground truth foreground"? it has labels for lungs, it is a large area.

If we have vessel, then it would be nice. If not, we can just do a threshold to guess the vessel?
But I guess a large SSD loss can be helpful, maybe a weighted SSD loss where small areas have higher weights.

**Comment by NMontanaBrown** [comment]
Hi @YipengHu, just recalling work from last year. Do you know of any literature on hessian vessel filtering losses? Considering we are using 3D volumes, this could potentially be used/developed in the case of airways and tubular structures/vessels?

Also, can you update the issue to use the issue template? :)

**Comment by YipengHu** [comment]
> Hi @YipengHu, just recalling work from last year. Do you know of any literature on hessian vessel filtering losses? Considering we are using 3D volumes, this could potentially be used/developed in the case of airways and tubular structures/vessels?
> 
> Also, can you update the issue to use the issue template? :) 

I'm using the "other" option in the template, as none of the others looked suitable... interesting point on the filter - maybe filtering within ROI before registering?

**Comment by NMontanaBrown** [comment]
> > Hi @YipengHu, just recalling work from last year. Do you know of any literature on hessian vessel filtering losses? Considering we are using 3D volumes, this could potentially be used/developed in the case of airways and tubular structures/vessels?
> > Also, can you update the issue to use the issue template? :)
> 
> I'm using the "other" option in the template, as none of the others looked suitable... interesting point on the filter - maybe filtering within ROI before registering?

I thought that would be an interesting way to introduce the "vesselness" prior - as you say it can be an additional loss that weakly constrains like the label based losses... Filtering before registering (so effectively adding/creating a label) or filtering after registering (more an image based loss)? Let me do a quick lit search if this has been done before.

[Implem for scikit, can port to tf](https://scikit-image.org/docs/0.13.x/api/skimage.filters.html#skimage.filters.frangi)
