### ISSUE TITLE
Demo optimise - paired mrus brain

### ISSUE THREAD

**Issue by s-sd** [DeepRegNet/DeepReg#577]
## Subject of the issue

Improve the results from the `paired_mrus_brain` demo.

**Comment by YipengHu** [comment]
we can leave this ticket open, but i would not spend too much time on this one now.

**Comment by mathpluscode** [comment]
Hi, please do not continue this issue before the merge of #602

**Comment by YipengHu** [comment]
i'm closing this in favour of a new ticket with better-defined objective, given a updated demo already in place.
