### ISSUE TITLE
DDF all zero in predict

### ISSUE THREAD

**Issue by mathpluscode** [DeepRegNet/DeepReg#578]
## Subject of the issue

In the latest main branch, when using demos/paired_mrus_prostate/demo_predict.py. The generated DDF are all zero.

The issue comes from ba27961deb0a3d1721747e03ae5a25ef49d988ea, #556.

## Steps to reproduce

- Train 1 epoch
- Copy the checkpoint under dataset/pretrained
- Run predict
- Check saved DDF png files

## Expected behaviour

Non-uniform DDF.

## Actual behaviour

All zero DDF.

## TODO

- Fix the problem by using the same loading mechanism as train. But be careful, as we changed the save/load system, the saved ckpts in demos were old versions.
- Add a test, verifying the DDF will not be all zero.
- Test in this demo manually.

**Comment by YipengHu** [comment]
@sbb-gh just let you know the bug which may affect your demo optimise and even visualise if you run predict before plotting
