### ISSUE TITLE
Use pydocstyle and pylint to check docstring

### ISSUE THREAD

**Issue by mathpluscode** [DeepRegNet/DeepReg#587]
## Subject of the feature

http://www.pydocstyle.org/en/stable/usage.html#command-line-interface

It is common to forget updating docstrings, so an automated tool can be helpful.

The docstring should also pass pylint docstring check.

## Pylint Steps

I've updated the pylint config in the branch,
1. Identify an error code, e.g. `W9012`
2. Fix all related errors, then check with `pylint --disable=all --enable=W9012 *`

**Comment by NMontanaBrown** [comment]
I like this ticket, let me know if you need a hand.

**Comment by mathpluscode** [comment]
> I like this ticket, let me know if you need a hand.

XD yes, I'm doing some examples... it's relaxing.

**Comment by mathpluscode** [comment]
Emmm but this tool does not support sphinx type docstring. http://www.pydocstyle.org/en/stable/error_codes.html#default-conventions

Maybe a transition to google style can be considered.

**Comment by mathpluscode** [comment]
It can be easily done with https://github.com/dadadel/pyment.

**Comment by mathpluscode** [comment]
It turns out that, google or reST, it doesn't really matter, this `pydocstyle` can only do limited linting. It cannot detect missing docstring or wrong docstring for arguments.

BUT PYLINT can lol

**Comment by NMontanaBrown** [comment]
That's why I was arguing for pylint all the way back then!
