### ISSUE TITLE
Question on triangular kernel for LNCC

### ISSUE THREAD

**Issue by mathpluscode** [DeepRegNet/DeepReg#588]
## Subject of the issue

https://github.com/DeepRegNet/DeepReg/blob/main/deepreg/model/loss/image.py#L88

The triangular `filters` are of shape `(kernel_size-1, kernel_size-1, kernel_size-1, ch, 1)` unlike the other two cases.
My question is simply, is this intended or not :) @acasamitjana

**Comment by acasamitjana** [comment]
Hey, I'm back on track now, sorry for the delay.
It was not intended, we should increase padding +1 on the right of each dimension.

**Comment by mathpluscode** [comment]
sure, once after #568 we can fix it
