### ISSUE TITLE
Affine registration and GlobalNet

### ISSUE THREAD

**Issue by YipengHu** [DeepRegNet/DeepReg#59]
#### Issue description
Current globalnet with affine transformation has a format not consistent with other ddf or dvf pr conditional_registration.

## Type of issue
Please delete options that are not relevant.

- [x] New feature request
- [ ] Documentation update
- [x] Test request

#### What's the expected result?
- New network build, train, predict functionalities as with others 
- Be consistent with dvf, outputing the transformation parameters
- GlobalNet should return the same as other backbone networks 

#### What's the actual result?
refactored code

#### Additional details / screenshot

-
-

**Comment by mathpluscode** [comment]
It seems that the global net option has been added into the code, but tests is needed to cover it

**Comment by RemiDelaunay** [comment]
Hi,

I just created a new branch with new network build. Affine transform can now be accessed while globalnet still outputs a ddf like localnet.

What do you need in terms of testing ? Should I just provide a yaml config file to use with `train_and_predict_with_config` just like in [https://github.com/ucl-candi/DeepReg/blob/master/test/output/test_config.py](url)

Also I noticed the `labeled` argument was needed for `build_model()` in train.py, but is missing in  `build_dvf_model` and `build_cond_model`. Should I create an issue and sort it out  ?

**Comment by YipengHu** [comment]
I think adding docstring to all the functions you added or related to you for one.
@NMontanaBrown can you point out where to find more information on testing to Remi?
@mathpluscode can you have a look at the potential bug mentioned?

**Comment by mathpluscode** [comment]
@RemiDelaunay all the data loaders only support ddf models,
i didn't have the chance to adapt dvf and conf models
