### ISSUE TITLE
Clarify log_root and log_dir for train/predict

### ISSUE THREAD

**Issue by mathpluscode** [DeepRegNet/DeepReg#590]
## Subject of the issue

It is quite confusing which is which and what's their purpose.

**Comment by YipengHu** [comment]
agree, together with "ckpt_path"

**Comment by mathpluscode** [comment]
> agree, together with "ckpt_path" - i don't see why they can not be just one log_dir

Well, it's the option between automated timestamp based name and where we store the log exactly.
I might still keep two args, but one is `output_path` or `log_path`, another one being `experiment_name` or `run_name`

**Comment by YipengHu** [comment]
#630 can be addressed here

**Comment by mathpluscode** [comment]
maybe better to solve this first, then #630, better to be separated ^^

**Comment by YipengHu** [comment]
> > agree, together with "ckpt_path" - i don't see why they can not be just one log_dir
> 
> Well, it's the option between automated timestamp based name and where we store the log exactly.
> I might still keep two args, but one is `output_path` or `log_path`, another one being `experiment_name` or `run_name`

fine - a good error message needs to be added when one of these was not supplied

**Comment by YipengHu** [comment]
I'm assigning this to you @mathpluscode but also thinking this ticket might benefit from a fresh pair of eyes to make a clear change/update to this. @zacbaum @kate-sann5100 , either of you would be interested (at least to advise), as you both had experience in the pain ;) ?
