### ISSUE TITLE
Question on num bins for GlobalMutualInformation

### ISSUE THREAD

**Issue by mathpluscode** [DeepRegNet/DeepReg#591]
## Subject of the issue

In https://github.com/DeepRegNet/DeepReg/blob/567-define-loss-as-classes-instead-of-functions/deepreg/model/loss/image.py#L49,
the `num_bins` are 23 by default, is there any specific reason for this?

@acasamitjana

**Comment by acasamitjana** [comment]
Not really, it's the value I was using and giving reasonable results in previous experiments. I'm sure any value around 20-25 would be good.

**Comment by mathpluscode** [comment]
In the doc string, I've mentioned that it's a empirical number. So I'm closing this issue.
