### ISSUE TITLE
Deadlink on the cluster page

### ISSUE THREAD

**Issue by YipengHu** [DeepRegNet/DeepReg#601]
## Subject of the documentation

- The link to the description of "install the enviriment in the cluster as described [here]" is not working
- UCL HPC site needs login - better to add "login required".

**Comment by YipengHu** [comment]
@sbb-gh can you have a look at this?

**Comment by sbb-gh** [comment]
- "The link to the description of "install the enviriment in the cluster as described [here]" is not working"
When I click on that link it sends me to the README page, does that not work for you?

- UCL HPC site needs login - better to add "login required".
Will do this.  I don't think I can put the password on the site.

**Comment by YipengHu** [comment]
> * "The link to the description of "install the enviriment in the cluster as described [here]" is not working"
> 
> The link was designed for the github page to point to: https://github.com/DeepRegNet/DeepReg/blob/main/README.md
> For the docs page it should point to https://deepreg.readthedocs.io/en/latest/getting_started/install.html
> 
> Not sure what to do here.
> 
> * UCL HPC site needs login - better to add "login required".
>   Will do this.  I don't think I can put the password on the docs.

The URL now is https://deepreg.readthedocs.io/README.md
and should be something like: https://deepreg.readthedocs.io/en/latest/getting_started/install.html

**Comment by mathpluscode** [comment]
https://deepreg.readthedocs.io/en/latest/tutorial/run_cluster.html It's working now.
