### ISSUE TITLE
Release to docker hub

### ISSUE THREAD

**Issue by mathpluscode** [DeepRegNet/DeepReg#608]
## Subject of the feature

We have a preliminary docker file already. As some users might be interested in using deepreg directly inside the docker, to skip all the complicated setup, it's worth considering releasing the docker image to docker hub as well.

This is doable via GitHub Action, but some checks should be enabled in CI first.

**Comment by mathpluscode** [comment]
Regarding the docker, I still wonder whether we should have conda inside docker or not.

**Comment by YipengHu** [comment]
> Regarding the docker, I still wonder whether we should have conda inside docker or not.
> 
> * If using nvidia docker images, this should not be required.
> * If using tf docker images, this is probably needed to handle the cuda dependency.

what is the downside of nvidia docker?

**Comment by mathpluscode** [comment]
> > Regarding the docker, I still wonder whether we should have conda inside docker or not.
> > 
> > * If using nvidia docker images, this should not be required.
> > * If using tf docker images, this is probably needed to handle the cuda dependency.
> 
> what is the downside of nvidia docker?

Probably no downside, but if you do not have GPU, then I'm not sure if you can use a nvidia docker, will dig.

**Comment by mianasbat** [comment]
Taking liberty to comment, hope you guys do not mind it. 
I am working on Docker to create CPU and GPU examples [here](https://scikit-surgerydocker.readthedocs.io/en/latest/). I noticed that there is no problem to specify nvidia docker for CPU program and therefore I am using it for both examples. It works fine even if GPU is not present on docker host.
The minor drawback is that nvidia docker is much larger in size than simple ubuntu which will making sharing a bit difficult.
