### ISSUE TITLE
Complete pylint linting

### ISSUE THREAD

**Issue by mathpluscode** [DeepRegNet/DeepReg#610]
## Subject of the code / test

After https://github.com/DeepRegNet/DeepReg/pull/589, we have activated some extra linting rules. However, there are still more rules not respected in the current code base.

As we can see in https://github.com/DeepRegNet/DeepReg/runs/1665498705?check_suite_focus=true,
there are still many errors triggered.

Thus it would be nice to split the job and solve the issues one by one.
We can either create multiple issues, or use this same issue while maintaining a TODO list.

**Comment by YipengHu** [comment]
@NMontanaBrown do you think you can handle this?

**Comment by NMontanaBrown** [comment]
I don't think it's a good use of my time to pylint all the codebase @YipengHu . Rather, I would suggest an auto pylint hook, or ask that people pylint as they go. And then towards the end if we have to, do a quick pylint run with many people.
