### ISSUE TITLE
Global_net train without regulariser raised error

### ISSUE THREAD

**Issue by YipengHu** [DeepRegNet/DeepReg#613]
## Subject of the issue

Train with global net, without providing regulariser in config file, generates error in config_sanity_check(config)

Yes

## Your environment

- DeepReg version (commit hash)

https://github.com/DeepRegNet/DeepReg/commit/fda64211b59859ef8821ac61a56f7e0aa750017b

- OS (e.g. Ubuntu 20.04, MacOS 10.15, etc.)

  Ubuntu 16.04

- Python Version (3.7, 3.8, etc.)

  3.7

- TensorFlow

  - TensorFlow 2.3
  - CUDA Version 10.1
  - cuDNN Version

## Steps to reproduce

python demos/paired_ct_lung/demo_train_global.py

*edits*: the same for field "'extract_levels'"

**Comment by mathpluscode** [comment]
global net is essentially a ddf model, so you should have regularize and extract levels?

**Comment by YipengHu** [comment]
> global net is essentially a ddf model, so you should have regularize and extract levels?

It is a bit complicated than it should be. 
- global = affine, here anyway
- first, bending energy is invariant to affine transformation
- although gradient norm is not, adding regulariser will penalise the affine, e.g. scaling
- but traditionally, affine registration means optimising affine parameters "freely" - these parameters generate ddf for resampling reasons to warp the moving images, not for regularisation;
- so i think we should do:
1. allow using global without regulariser
2. when with bending !=0, warning or even error
3. when with gradient norms, warning

**Comment by mathpluscode** [comment]
ok, in #557 I'm not rewriting all these models, and I actually merged affine model into ddf model.

I will solve this issue in the PR or afterwards.

**Comment by YipengHu** [comment]
> ok, in #557 I'm now rewriting all these models, and I actually merged affine model into ddf model.
> 
> I will solve this issue in the PR or afterwards.

good - i also would like to add another rigid transform with 6 and 7 degrees of freedom - only the warped_grid function needs an extra option when using the same global_net - we can discuss how to best design the classes/register?

**Comment by mathpluscode** [comment]
> > ok, in #557 I'm now rewriting all these models, and I actually merged affine model into ddf model.
> > I will solve this issue in the PR or afterwards.
> 
> good - i also would like to add another rigid transform with 6 and 7 degrees of freedom - only the warped_grid function needs an extra option when using the same global_net - we can discuss how to best design the classes/register?

sure, once #602 is almost ready, will let you know

**Comment by mathpluscode** [comment]
@YipengHu can you confirm if you stiff have this error?

if yes, plz provide the error log

**Comment by YipengHu** [comment]
> @YipengHu can you confirm if you stiff have this error?
> 
> if yes, plz provide the error log

(deepreg) yipenghu@precision7750-yhu:~/git/DeepReg$ python demos/paired_ct_lung/demo_train.py --no-test
2021-01-24 16:30:15.086598: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'libcudart.so.10.1'; dlerror: libcudart.so.10.1: cannot open shared object file: No such file or directory
2021-01-24 16:30:15.086633: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.





=======================================================
The training can also be launched using the following command.
deepreg_train --gpu '0' --config_path demos/paired_ct_lung/paired_ct_lung.yaml --log_root demos/paired_ct_lung --log_dir logs_train
=======================================================






Traceback (most recent call last):
  File "demos/paired_ct_lung/demo_train.py", line 52, in <module>
    log_dir=log_dir,
  File "/home/yipenghu/git/DeepReg/deepreg/train.py", line 93, in train
    max_epochs=max_epochs,
  File "/home/yipenghu/git/DeepReg/deepreg/train.py", line 44, in build_config
    config = config_parser.load_configs(config_path)
  File "/home/yipenghu/git/DeepReg/deepreg/config/parser.py", line 43, in load_configs
    loaded_config = config_sanity_check(config)
  File "/home/yipenghu/git/DeepReg/deepreg/config/parser.py", line 112, in config_sanity_check
    loss_weight = config["train"]["loss"][name]["weight"]
KeyError: 'regularization'

**Comment by YipengHu** [comment]
this error can be re-produced by setting config in the demo as follows:
dataset:
  dir:
    train: "demos/paired_ct_lung/dataset/train"
    valid: "demos/paired_ct_lung/dataset/valid"
    test: "demos/paired_ct_lung/dataset/test"
  format: "nifti"
  type: "paired" # paired / unpaired / grouped
  labeled: true
  moving_image_shape: [96, 96, 104]
  fixed_image_shape: [96, 96, 104]
train:
  method: "ddf" # the registration method, value should be ddf / dvf / conditional
  backbone:
    name: "global" # value should be local / global / unet
    num_channel_initial: 32 # number of initial channel in local net, controls the size of the network
    extract_levels: [0, 1, 2]
  loss:
    image:
      name: "ssd"
      weight: 10.0
    label:
      weight: 1.0
      name: "dice"
      scales: [0, 1, 2, 4, 8, 16]
  preprocess:
    data_augmentation:
      name: "affine"
    batch_size: 4
    shuffle_buffer_num_batch: 1
  optimizer:
    name: "adam"
    adam:
      learning_rate: 1.0e-5
  epochs: 8000
  save_period: 1000

**Comment by mathpluscode** [comment]
ok, will fix it later.
