### ISSUE TITLE
Suppress TensorFlow warnings

### ISSUE THREAD

**Issue by mathpluscode** [DeepRegNet/DeepReg#614]
## Subject of the feature

TensorFlow is not printing many warnings in the bash. We need to check if any one of them should be fixed, like #428.
Then we should remove warning by default.

UPDATE: the better option is to use verbosity

**Comment by mathpluscode** [comment]
defining `TF_CPP_MIN_LOG_LEVEL=3` before launching the code seems to work, but it is unclear yet how to do it inside python.

for deprecated warnings, need to do
https://www.codespeedy.com/suppression-of-deprecation-warnings-in-tensorflow-python/

**Comment by zacbaum** [comment]
As mentioned in #656; would be good to adjust verbosity of logging here as well (for model.summary and model.fit as examples)

**Comment by mathpluscode** [comment]
Closing this issue in favor of https://github.com/DeepRegNet/DeepReg/issues/745
