### ISSUE TITLE
Refactoring of data augmentation

### ISSUE THREAD

**Issue by mathpluscode** [DeepRegNet/DeepReg#617]
### Naming

- `lowres_size`, maybe to `low_res_size` or `res_size` as we do not have `high_res_size` here? https://github.com/DeepRegNet/DeepReg/blob/main/deepreg/dataset/preprocess.py#L175

### Refactoring

- Why we need `__call__` here? https://github.com/DeepRegNet/DeepReg/blob/main/deepreg/dataset/preprocess.py#L30 (this is a question)
- for https://github.com/DeepRegNet/DeepReg/blob/main/deepreg/dataset/preprocess.py#L40 we can use abstract decorator and do not write function body, as `NotImplementedError` need to be tested.
- for https://github.com/DeepRegNet/DeepReg/blob/main/deepreg/dataset/preprocess.py#L107 and https://github.com/DeepRegNet/DeepReg/blob/main/deepreg/dataset/preprocess.py#L241 they are highly similar, so we can share them by letting `_transform` return a pair for moving and fixed images.

**Comment by mathpluscode** [comment]
Actually, the refactoring is fast, I will quickly do a PR @acasamitjana

**Comment by acasamitjana** [comment]
Hi,
>     * `lowres_size`, maybe to `low_res_size` or `res_size` as we do not have `high_res_size` here? https://github.com/DeepRegNet/DeepReg/blob/main/deepreg/dataset/preprocess.py#L175
I think naming should be clear to the user, as this parameter is a kwarg from the config file. I wanted to emphasize it's a lower resolution field, but maybe `field_size' works better
> 

>     * Why we need `__call__` here? https://github.com/DeepRegNet/DeepReg/blob/main/deepreg/dataset/preprocess.py#L30 (this is a question)
In interface.py, I'm appending all data augmentation in a list (thinking that maybe, in the future, we wanted to add other data augmentation e.g., intensity-based transformations). Then this list is applied to input dictionary in https://github.com/DeepRegNet/DeepReg/blob/02810b23d6f137312181057740e03f37d635d136/deepreg/dataset/loader/interface.py#L147.
Here, I'm assuming we can use any `callable object'  for flexibility (e.g., use external library functions). Hence, the ones we are implementing need to be `callable'. I'm not sure if this will be any useful in the future, but I thought it was nice to have it like this. 

>     * for https://github.com/DeepRegNet/DeepReg/blob/main/deepreg/dataset/preprocess.py#L40 we can use abstract decorator and do not write function body, as `NotImplementedError` need to be tested.
Ok, nice.

>     * for https://github.com/DeepRegNet/DeepReg/blob/main/deepreg/dataset/preprocess.py#L107 and https://github.com/DeepRegNet/DeepReg/blob/main/deepreg/dataset/preprocess.py#L241 they are highly similar, so we can share them by letting `_transform` return a pair for moving and fixed images.
Definitely, we can implement a `transform' in the Abstract class and then each dedicated class has its own `_transform'
