### ISSUE TITLE
Demo optimise paired mr us prostate

### ISSUE THREAD

**Issue by mathpluscode** [DeepRegNet/DeepReg#621]
## Subject of the issue

![image](https://user-images.githubusercontent.com/4066929/104234946-1fa3ac80-544c-11eb-9492-c715852f0daf.png)

Demo paired_mr_us_prostate results are not good enough, as the predicted fixed image (ultrasound) does not even have the shape of the ultrasound.

**Comment by YipengHu** [comment]
#624 there is a possibility there has not been anything moved...?

**Comment by mathpluscode** [comment]
> #624 there is a possibility there has not been anything moved...?

Fortunately, as my branch fixed the problem without knowing it, the bad quality is not due to the typo bug ^^

**Comment by YipengHu** [comment]
> > #624 there is a possibility there has not been anything moved...?
> 
> Fortunately, as my branch fixed the problem without knowing it, the bad quality is not due to the typo bug ^^

good to plot the warped masks in test to demonstrate the efficacy for this demo, as the images are "fake"

**Comment by mathpluscode** [comment]
> > > #624 there is a possibility there has not been anything moved...?
> > 
> > 
> > Fortunately, as my branch fixed the problem without knowing it, the bad quality is not due to the typo bug ^^
> 
> good to plot the warped masks in test to demonstrate the efficacy for this demo, as the images are "fake"

are you suggesting to visualize labels whenever possible in @s-sd's script?

**Comment by YipengHu** [comment]
> > > > #624 there is a possibility there has not been anything moved...?
> > > 
> > > 
> > > Fortunately, as my branch fixed the problem without knowing it, the bad quality is not due to the typo bug ^^
> > 
> > 
> > good to plot the warped masks in test to demonstrate the efficacy for this demo, as the images are "fake"
> 
> are you suggesting to visualize labels whenever possible in @s-sd's script?

if possible, that's be a good idea.
