### ISSUE TITLE
Label loss is not being used

### ISSUE THREAD

**Issue by YipengHu** [DeepRegNet/DeepReg#624]
Subject of the issue
Train with label+regularisor losses, the label loss is not in print and overall loss remains zeros

Yes

Your environment
DeepReg version (commit hash)
#456731e51b69548b7f529c24b4de6d96c406ed60

OS (e.g. Ubuntu 20.04, MacOS 10.15, etc.)

Ubuntu 16.04

Python Version (3.7, 3.8, etc.)

3.7

TensorFlow

TensorFlow 2.3
CUDA Version 10.1
cuDNN Version
Steps to reproduce

-python demos/paired_mrus_prostate/demo_train.py
-different private datasets have been tested with the same results
-i believe it is a problem by setting image loss weight to zero, i.e. for weakly supervision, for all other applications/demos too

**Comment by YipengHu** [comment]
@mathpluscode could you please have a look at this?

**Comment by mathpluscode** [comment]
OK, i confirmed it is a bug, due to a typo:

![image](https://user-images.githubusercontent.com/4066929/104819804-dd051a00-5827-11eb-83b0-db152a06d1e5.png)
