### ISSUE TITLE
Plots for visualisation lead to 404 in demo READMEs

### ISSUE THREAD

**Issue by NMontanaBrown** [DeepRegNet/DeepReg#626]
## Subject of the issue

When I visit the demo pages, there is a broken link to the visualisation. Clicking on the small icon leads to a 404. I assume there needs to be a plot here where there is a 404.

If the bug is confirmed, would you be willing to submit a PR? _(Help can be provided if
you need assistance submitting a PR)_

Yes

## Steps to reproduce

Visit the demos in the codebase, the README has a broken link named "plot" under each one.

## Expected behaviour

There is a plot visualisation in the demo pages.

## Actual behaviour

There is no plot, and clicking on the icon leads to a 404.

**Comment by mathpluscode** [comment]
@NMontanaBrown is there a link of the 404? thx!

**Comment by NMontanaBrown** [comment]
EG: https://github.com/DeepRegNet/DeepReg/blob/main/demos/assets/classical_ct_headneck_affine.png

**Comment by mathpluscode** [comment]
Oh, it is normal ^^ We are using RTD, therefore the images are relative to 
https://github.com/DeepRegNet/DeepReg/tree/main/docs/source/demo


Check https://deepreg.readthedocs.io/en/latest/demo/classical_ct_headneck_affine.html, you can see the images :)

**Comment by NMontanaBrown** [comment]
Even if it is normal, it is still buggy. Does RTD pull from the .md files? Can we add the source files to the appropriate links so we can see them in the .md files? It is unexpected behaviour.

**Comment by mathpluscode** [comment]
> Even if it is normal, it is still buggy. Does RTD pull from the .md files? Can we add the source files to the appropriate links so we can see them in the .md files? It is unexpected behaviour.

It is expected. RTD pull from rst files, and rst file import from md files. So there's no way to make both works, sorry. I really tried in the very beginning.

**Comment by mathpluscode** [comment]
@NMontanaBrown As this is expected behavior, if you are ok, I will close this issue?
