### ISSUE TITLE
Config files in demos potentially incorrect for the new registry

### ISSUE THREAD

**Issue by NMontanaBrown** [DeepRegNet/DeepReg#627]
## Subject of the issue

We are in the process of updating the config files for the back compatibility change for 1.0.0 given the change to registry method.

[As raised in this discussion](https://github.com/DeepRegNet/DeepReg/pull/559#discussion_r545334767) we are moving away from the old config file style, into the new config file style.

Looking for examples to update the docs, I noted that the demos may be broken because the config files no longer follow the correct order: "name" then arguments versus "backbone" then arguments.

Files with incorrect configs:
- [Grouped heart MR](https://github.com/DeepRegNet/DeepReg/blob/456731e51b69548b7f529c24b4de6d96c406ed60/demos/grouped_mr_heart/grouped_mr_heart.yaml#L14
- [Prostate longitudinal](https://github.com/DeepRegNet/DeepReg/blob/456731e51b69548b7f529c24b4de6d96c406ed60/demos/grouped_mask_prostate_longitudinal/grouped_mask_prostate_longitudinal.yaml#L17)
- [Paired CT Lung](https://github.com/DeepRegNet/DeepReg/blob/456731e51b69548b7f529c24b4de6d96c406ed60/demos/paired_ct_lung/paired_ct_lung.yaml#L13)
- [Paired Brain MRUS](https://github.com/DeepRegNet/DeepReg/blob/456731e51b69548b7f529c24b4de6d96c406ed60/demos/paired_mrus_brain/paired_mrus_brain.yaml#L13)
-  [Paired Prostate MRUS](https://github.com/DeepRegNet/DeepReg/blob/456731e51b69548b7f529c24b4de6d96c406ed60/demos/paired_mrus_prostate/paired_mrus_prostate.yaml#L25)
- [Abdo CT](https://github.com/DeepRegNet/DeepReg/blob/456731e51b69548b7f529c24b4de6d96c406ed60/demos/unpaired_ct_abdomen/unpaired_ct_abdomen_comb.yaml#L13)
- [Unpaired Lung CT](https://github.com/DeepRegNet/DeepReg/blob/456731e51b69548b7f529c24b4de6d96c406ed60/demos/unpaired_ct_lung/unpaired_ct_lung.yaml#L12)
- [Unpaired Brain MR](https://github.com/DeepRegNet/DeepReg/blob/456731e51b69548b7f529c24b4de6d96c406ed60/demos/unpaired_mr_brain/unpaired_mr_brain.yaml#L14)
- [Unpaired Prostate CV](https://github.com/DeepRegNet/DeepReg/blob/456731e51b69548b7f529c24b4de6d96c406ed60/demos/unpaired_us_prostate_cv/unpaired_us_prostate_cv.yaml#L21)

**Comment by mathpluscode** [comment]
Sorry, @NMontanaBrown @YipengHu the demo tests are passed, what is the problem here :) ?

**Comment by YipengHu** [comment]
> Sorry, @NMontanaBrown @YipengHu the demo tests are passed, what is the problem here :) ?

I'm not 100% sure as have not looked in details myself. Suggest to look at #624 first as an example for this "potential" issue.

**Comment by mathpluscode** [comment]
So I guess we can close this issue?

**Comment by NMontanaBrown** [comment]
Yes, thanks @mathpluscode closing now.
