### ISSUE TITLE
Allow shorthand "~/" in config path

### ISSUE THREAD

**Issue by YipengHu** [DeepRegNet/DeepReg#630]
## Subject of the feature

Allow shorthand "~/" in specifying data path. This is useful to improve the config portability with little confusion.

If the feature request is approved, would you be willing to submit a PR? _(Help can be
provided if you need assistance submitting a PR)_

Yes

**Comment by NMontanaBrown** [comment]
Hotfix: can modify the utils to read config to do "abspath" from module os.? @YipengHu

**Comment by YipengHu** [comment]
> Hotfix: can modify the utils to read config to do "abspath" from module os.? @YipengHu

this can be os-sensitive, better to be explicit and use os.path.expanduser()

**Comment by mathpluscode** [comment]
there are also people arguing https://docs.python.org/3/library/pathlib.html is better than `os.path`

**Comment by NMontanaBrown** [comment]
> > Hotfix: can modify the utils to read config to do "abspath" from module os.? @YipengHu
> 
> this can be os-sensitive, better to be explicit and use os.path.expanduser()

But we only support Mac and Linux (bash based), right? I have a Windows machine now so can also test there, once you decide what to do

**Comment by YipengHu** [comment]
> > > Hotfix: can modify the utils to read config to do "abspath" from module os.? @YipengHu
> > 
> > 
> > this can be os-sensitive, better to be explicit and use os.path.expanduser()
> 
> But we only support Mac and Linux (bash based), right? I have a Windows machine now so can also test there, once you decide what to do

believe it or not, it is not supported on linux, windows is fine

**Comment by YipengHu** [comment]
> there are also people arguing https://docs.python.org/3/library/pathlib.html is better than `os.path`

not another lib for one function?

**Comment by NMontanaBrown** [comment]
> https://docs.python.org/3/library/pathlib.html

This is in the standard python lib so we are not adding another package. Just `import pathlib` without pip installing or changing requirements.

**Comment by mathpluscode** [comment]
> > there are also people arguing https://docs.python.org/3/library/pathlib.html is better than `os.path`
> 
> not another lib for one function?

well it's more than one function, anyway, I will have a further look when we fix this issue.

**Comment by NMontanaBrown** [comment]
Also what abou "./" shorthand? Or is that what you meant @YipengHu ?

**Comment by YipengHu** [comment]
> Also what abou "./" shorthand? Or is that what you meant @YipengHu ?

i meant the home directory "~/"

**Comment by mathpluscode** [comment]
> Also what abou "./" shorthand? Or is that what you meant @YipengHu ?

@NMontanaBrown ./ will be relative to the current folder.

~ is equivalent to $HOME
