### ISSUE TITLE
Add a config change comparison

### ISSUE THREAD

**Issue by mathpluscode** [DeepRegNet/DeepReg#631]
## Subject of the documentation

As we are modifying the config files a lot recently, we need to maintain a doc page for users to show:
- what has been changed in the config
- how to adapt the previous config files to new ones

We can maintain the changes between any two released version and the last released -> latest main.

**Comment by NMontanaBrown** [comment]
I can work on this one, since I last worked on docs for config.

**Comment by mathpluscode** [comment]
@NMontanaBrown with the current backward compatibility, I consider this issue as non-necessary.

Currently, if the config was not up-to-date, we will save a copy with the latest format without errors.

**Comment by mathpluscode** [comment]
Closing this, as it is not important thx to back-compatibility.
