### ISSUE TITLE
Refactor config sanity check and corresponding tests

### ISSUE THREAD

**Issue by mathpluscode** [DeepRegNet/DeepReg#637]
## Subject of the code / test

The existing checks are quite useless and not well organized https://github.com/DeepRegNet/DeepReg/blob/main/deepreg/parser.py#L58.

- If possible, we should let the registry to handle the unsupported keys.
- Verifying data paths should be also data loader's responsibilities.
- For loss weights, it should be network's `build_loss` to raise warning or errors.
- For conditional model, it's ok to leave it here.

In general, these checks can be simplified and the related tests should be refactored.

**Comment by NMontanaBrown** [comment]
When you say "verify data paths being data loader responsibilities", what do you mean exactly? 

Shouldn't we do value error testing at the earliest moment possible? EG if we have the chance to raise errors on paths before data loader, shouldn't we?

**Comment by mathpluscode** [comment]
This is actually being handled in https://github.com/DeepRegNet/DeepReg/pull/746
