### ISSUE TITLE
new naming scheme for the saved trained models: prediction script needs to be modified accordingly

### ISSUE THREAD

**Issue by ciphercharly** [DeepRegNet/DeepReg#641]
the prediction scripts that were expecting something like (this from the paired brain demo)
```
ckpt_path = f"{log_root}/dataset/pretrained/learn2reg_t1_paired_train_logs/save/weights-epoch800.ckpt"
```
need to be updated now to the new naming scheme

the saved checkpoints are now like
```
save/ckpt-****.data-00000-of-00001
save/ckpt-****.index
```

so /save/ckpt-***** would be the new name in the prediction script

**Comment by ciphercharly** [comment]
(lol, sorry for this useless issue, but I was getting an error in prediction and I figured out it was the new naming scheme when I had already opened the issue)

**Comment by mathpluscode** [comment]
Yes, we changed the ckpt system to enable restoring from a stopped run. 😬

**Comment by ciphercharly** [comment]
that's great, very useful

**Comment by mathpluscode** [comment]
> that's great, very useful

Please let us know if it works as expected 😸 it should.
