### ISSUE TITLE
Seminar video link broken

### ISSUE THREAD

**Issue by YipengHu** [DeepRegNet/DeepReg#658]
## Subject of the issue

The link to the seminar video introducing DeepReg is not accessible to public with the error message:
"The session owner has disabled public access or the link has expired. Try launching the recording again or contact the session owner."

If the bug is confirmed, would you be willing to submit a PR? _(Help can be provided if
you need assistance submitting a PR)_

Yes

## Expected behaviour

Consider to obtain consensus from all the speakers and maybe publish it in the WEISS YouTube channel. Ask Amy <a.warnock@ucl.ac.uk> for access.

@NMontanaBrown can you help with this?

**Comment by NMontanaBrown** [comment]
Pinged about it, waiting on a response now @YipengHu

**Comment by NMontanaBrown** [comment]
Fixing now.
