### ISSUE TITLE
Question about IntDVF

### ISSUE THREAD

**Issue by kate-sann5100** [DeepRegNet/DeepReg#665]
Is IntDVF converting DDF to DVF or DVF to DDF. Because base on the DVF network implementation, it seems like IntDVF is converting DVF to DDF while the docstring in Int DVF states otherwise. 
https://github.com/DeepRegNet/DeepReg/blob/80854094feafec998fa6237199066556c73f31f9/deepreg/model/layer.py#L508-L535

**Comment by YipengHu** [comment]
@kate-sann5100 well-spotted. it is a typo i believe.

**Comment by mathpluscode** [comment]
Yup, it's a typo. Will correct it.

**Comment by mathpluscode** [comment]
Actually, I've fixed it in my PR #656.

**Comment by mathpluscode** [comment]
With the merge of #656, this issue is now fixed https://github.com/DeepRegNet/DeepReg/blob/80854094feafec998fa6237199066556c73f31f9/deepreg/model/layer.py#L511
