### ISSUE TITLE
Accessing linked talk in Readme

### ISSUE THREAD

**Issue by RGologorsky** [DeepRegNet/DeepReg#674]
##  "The Road to DeepReg" talk access

I'm interested in the talk linked in the Readme -- "Members of the DeepReg dev team presented "The Road to DeepReg" at the Centre for Medical Imaging Computing (CMIC) seminar series at University College London on the 4th of November 2020. You can access the talk here."

However I wasn't able to access it -- got the following error message:
"This recording isn't available to view.
The session owner has disabled public access or the link has expired. Try launching the recording again or contact the session owner."

Please let me know how to access the talk, if possible.
Thank you!

**Comment by mathpluscode** [comment]
Hi @RGologorsky, as mentioned in https://github.com/DeepRegNet/DeepReg/issues/658, we are aware of this issue.

@NMontanaBrown @YipengHu do we have any updates?

**Comment by YipengHu** [comment]
The link is behind the wall. We will fix the link. For now, @RGologorsky you can access a copy here: https://liveuclac-my.sharepoint.com/:v:/g/personal/rmapyhu_ucl_ac_uk/EbB8nkeoP19InRkrlCBzIA4BCMXBbHF_3wzugYC5myCXAw?e=t8kqOo

Thanks for the ticket!

**Comment by mathpluscode** [comment]
> The link is behind the wall. We will fix the link. For now, @RGologorsky you can access a copy here: https://liveuclac-my.sharepoint.com/:v:/g/personal/rmapyhu_ucl_ac_uk/EbB8nkeoP19InRkrlCBzIA4BCMXBbHF_3wzugYC5myCXAw?e=t8kqOo
> 
> Thanks for the ticket!

@YipengHu can we update the link to this one for now?

**Comment by YipengHu** [comment]
> > The link is behind the wall. We will fix the link. For now, @RGologorsky you can access a copy here: [https://liveuclac-my.sharepoint.com/✌️/g/personal/rmapyhu_ucl_ac_uk/EbB8nkeoP19InRkrlCBzIA4BCMXBbHF_3wzugYC5myCXAw?e=t8kqOo](https://liveuclac-my.sharepoint.com/:v:/g/personal/rmapyhu_ucl_ac_uk/EbB8nkeoP19InRkrlCBzIA4BCMXBbHF_3wzugYC5myCXAw?e=t8kqOo)
> > Thanks for the ticket!
> 
> @YipengHu can we update the link to this one for now?

nan.. this is a temp one to my personal drive. Amy will upload to the official youtube channel, we can use that one then.

**Comment by NMontanaBrown** [comment]
Hi @RGologorsky , the link has been updated in the README, you should now be able to access the talk!
