### ISSUE TITLE
Use automated docs for argparse

### ISSUE THREAD

**Issue by mathpluscode** [DeepRegNet/DeepReg#700]
## Subject of the documentation

As shown here, https://sphinx-argparse.readthedocs.io/en/stable/sample.html#example-documentation-structure

we can create doc page from the docstring directly, so that we do not have to maintain docs in two separate places.

@NMontanaBrown the efforts you've made will be moved into one place ^^ if you are ok

**Comment by NMontanaBrown** [comment]
@mathpluscode can you elaborate on "the efforts I've made will be moved into one place if I am ok"? Don't understand what this is referring to.

**Comment by mathpluscode** [comment]
> @mathpluscode can you elaborate on "the efforts I've made will be moved into one place if I am ok"? Don't understand what this is referring to.

On I mean I will not simply delete the existing page and entirely use the autodoc, I will try to keep the existing docs as much as possible.
