### ISSUE TITLE
Demo for velocity-predicting option

### ISSUE THREAD

**Issue by YipengHu** [DeepRegNet/DeepReg#703]
## Subject of the feature

The DVF has been implemented without a demo demonstrating its applicability. 

If the feature request is approved, would you be willing to submit a PR? _(Help can be
provided if you need assistance submitting a PR)_

Yes / No

**Comment by YipengHu** [comment]
Suggest:

It'd be interesting to look at the mask demo:
edit code: https://github.com/DeepRegNet/DeepReg/tree/main/demos/grouped_mask_prostate_longitudinal
update doc: https://github.com/DeepRegNet/DeepReg/blob/main/docs/source/demo/grouped_mask_prostate_longitudinal.rst
According to the config here: https://deepreg.readthedocs.io/en/latest/docs/configuration.html#localnet - change the method to `dvf`
Not sure it needs to edit any functions at this stage, but the related functions may be here: class DVFModel(DDFModel): in https://github.com/DeepRegNet/DeepReg/blob/main/deepreg/model/network.py

**Comment by YipengHu** [comment]
efficient-net is another option.

**Comment by acasamitjana** [comment]
If no one else is interested, I will do this one after the Easter break

**Comment by YipengHu** [comment]
> If no one else is interested, I will do this one after the Easter break

@acasamitjana thanks! I am asking a student looking at this as well, can i get back to you around easter to see if he is still going to pick this up?

**Comment by acasamitjana** [comment]
yes, sure, let me know!

**Comment by Zhiyuan-w** [comment]
How to assign this ticket?

**Comment by YipengHu** [comment]
> How to assign this ticket?

there is an icon on the top-right - i've done it.

**Comment by Zhiyuan-w** [comment]
(deepreg) E:\DeepReg>deepreg_train --gpu '0' --config_path demos/grouped_mask_prostate_longitudinal/grouped_mask_prostate_longitudinal.yaml --log_dir demos/grouped_mask_prostate_longitudinal --exp_name logs_train
2021-05-21 17:55:49.859241: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library cudart64_101.dll
usage: deepreg_train [-h] --gpu GPU [--gpu_allow_growth GPU_ALLOW_GROWTH]
                     [--ckpt_path CKPT_PATH] [--log_root LOG_ROOT]
                     [--log_dir LOG_DIR] --config_path CONFIG_PATH
                     [CONFIG_PATH ...] [--max_epochs MAX_EPOCHS]
Error message:
**deepreg_train: error: unrecognized arguments: --exp_name logs_train**
