### ISSUE TITLE
Add support for neptune

### ISSUE THREAD

**Issue by mathpluscode** [DeepRegNet/DeepReg#710]
## Subject of the feature

It can be very helpful to allow users to upload their training results to neptune https://neptune.ai/ in addition to tensorboard.

This feature should be activated using either config / env variable.

**Comment by NMontanaBrown** [comment]
What is the point of supporting both neptune and w&B when they both sort of do the same thing? @YipengHu  @mathpluscode

**Comment by mathpluscode** [comment]
> What is the point of supporting both neptune and w&B when they both sort of do the same thing? @YipengHu  @mathpluscode 

It's like why not all using PyTorch? I think it's more user friendly if user has a choice specially some may have subscriptions. But we can do define this ticket as low priority. @NMontanaBrown

**Comment by NMontanaBrown** [comment]
@mathpluscode more curious as to who could pick it up? Because I personally have not used neptune so...?

**Comment by mathpluscode** [comment]
> @mathpluscode more curious as to who could pick it up? Because I personally have not used neptune so...?

:) if someone interested he/she will pick up. Otherwise we may close it in few months.
