### ISSUE TITLE
upgrade to tf2.4

### ISSUE THREAD

**Issue by mathpluscode** [DeepRegNet/DeepReg#721]
## Subject of the feature

tf2.4 has been out for a while, and we may want to upgrade to it. But there might be some problems

- https://github.com/tensorflow/tensorflow/issues/42146
- numpy version need to be updated

FYI @YipengHu @zacbaum if you have any other concerns ^^

**Comment by YipengHu** [comment]
> ## Subject of the feature
> tf2.4 has been out for a while, and we may want to upgrade to it. But there might be some problems
> 
> * [tensorflow/tensorflow#42146](https://github.com/tensorflow/tensorflow/issues/42146)
> * numpy version need to be updated
> 
> FYI @YipengHu @zacbaum if you have any other concerns ^^

nothing from me - go for it. it might solve some ram problems for @agrimwood

**Comment by NMontanaBrown** [comment]
I might  suggest against this: I've had struggles getting cuda and cudnn installed properly. Easier to use conda to install tensorflow, but I think on linux it's only supported to 2.3 at the moment? @mathpluscode @YipengHu @zacbaum
