### ISSUE TITLE
Use separable kernels for ResizeCPTransform

### ISSUE THREAD

**Issue by mathpluscode** [DeepRegNet/DeepReg#722]
## Subject of the feature

Currently, in `ResizeCPTransform` we are using 3D Gaussain kernel https://github.com/DeepRegNet/DeepReg/blob/main/deepreg/model/layer.py#L435

I think the 1D separable kernel is equivalent to this and it's more efficient? As in LNCC https://github.com/DeepRegNet/DeepReg/blob/main/deepreg/loss/image.py#L182

So I suggest to uniform this bit, what do you think @acasamitjana

**Comment by acasamitjana** [comment]
Hey, I'm looking at that. Just one comment: I'm using functions from loss.kernel.py file. Should we move this outside of the loss directory?

**Comment by mathpluscode** [comment]
> Hey, I'm looking at that. Just one comment: I'm using functions from loss.kernel.py file. Should we move this outside of the loss directory?

@acasamitjana entirely up to you! 😃I'm fine with both.

**Comment by acasamitjana** [comment]
Ok, let's leave as is, then.
