### ISSUE TITLE
Fix Dice Score

### ISSUE THREAD

**Issue by mathpluscode** [DeepRegNet/DeepReg#734]
## Subject of the issue

@YipengHu obeserved dice score > 1, which is clearly a bug.

It might be caused by https://github.com/DeepRegNet/DeepReg/commit/3a457eef313f4bee61d16e899d15a87e6c831e91.
where we somehow changed reduce_sum to mean, but as we are adding EPS to the numerator/denominator, the reduce mean may lead to values << 1 and therefore the result is no longer accurate.

**Comment by YipengHu** [comment]
changing to sum still has dice score greater than 1 (see below the BinaryDiceScore on val)
![2021-04-02 (2)](https://user-images.githubusercontent.com/2588157/113409147-9778d780-93a8-11eb-8620-28cbbc4d97d8.png)
