### ISSUE TITLE
Support iterative registration

### ISSUE THREAD

**Issue by mathpluscode** [DeepRegNet/DeepReg#744]
## Subject of the feature

What are you trying to do and how would you want to do it differently?

Given a pair of moving/fixed images, we want to perform multiple times of registration to enable larger displacements.
In other words, once registered, we can register the warped image to the fixed image again.

This is a common setting in inference. @YipengHu what do you think?

**Comment by YipengHu** [comment]
I would not consider this is common and the benefit isn't clear or convincing to me. What's stopping user to do this with existing code by running twice?

**Comment by mathpluscode** [comment]
> I would not consider this is common and the benefit isn't clear or convincing to me. What's stopping user to do this with existing code by running twice?

Well, you still need to reorganize the input/output files.

The change should be minimal as you only need to call the following again by redefining the inputs

```python
outputs = model.predict(x=inputs, batch_size=batch_size)
```
