### ISSUE TITLE
Train with nifti

### ISSUE THREAD

**Issue by AmericaBG** [DeepRegNet/DeepReg#753]
Hi!
First of all, thank you very much for sharing your code. it's a great job, congratulations!

I would like to train my own model with MR Images in .nii format. The shape is 256x256xN slices.
Is it posible with your code? Could you give me some advice about how I can do it or/and what I need to modify?

Thank you very much in advance!

**Comment by YipengHu** [comment]
> Hi!
> First of all, thank you very much for sharing your code. it's a great job, congratulations!
> 
> I would like to train my own model with MR Images in .nii format. The shape is 256x256xN slices.
> Is it posible with your code? Could you give me some advice about how I can do it or/and what I need to modify?
> 
> Thank you very much in advance!

Is it a case that you have variable number of slices in z direction? yes, most current algorithms requires the same input size, you can either a) pre-process your images by re-sampling/cropping - i guess this would be application-specific; or b) configure a fixed `image_shape` so it uses a built-in re-sampling function to pre-re-sample all iamges to the same shape (https://deepreg.readthedocs.io/en/latest/docs/configuration.html#unpaired). does it answer your question?
