### ISSUE TITLE
2D images

### ISSUE THREAD

**Issue by ku294714** [DeepRegNet/DeepReg#767]
Hello all,

I have 2D ultra sound images,  does this coed work to register 2D images, or just for 3D images?

**Comment by YipengHu** [comment]
unfortunately. 2D is not currently supported with DeepReg. You can have look at the relevant MONAI component to see if it is what you need: https://monai.medium.com/monai-starts-to-explore-learning-based-medical-image-registration-ab6b143840b7

**Comment by ku294714** [comment]
Hello Dear @YipengHu , Thank you for the reply, I will check MONAI. Meanwhile for DeepReg - CUDA support, does it not work with CUDA 11.2 version and only with 10.1 version?

**Comment by mathpluscode** [comment]
> Hello Dear @YipengHu , Thank you for the reply, I will check MONAI. Meanwhile for DeepReg - CUDA support, does it not work with CUDA 11.2 version and only with 10.1 version?

Hi @ku294714, using conda environment, it should be possible to use cuda 10.1 with drivers supporting 11. The main reason of the limit on cuda version was due to the tensorflow version.
