### ISSUE TITLE
Making docker image of deepreg

### ISSUE THREAD

**Issue by mianasbat** [DeepRegNet/DeepReg#777]
Hi, 
I noted that you provide the user with Dockerfile to build the image and then use it using docker. It would be nice if you make a docker image and keep it on dockerhub for each release of deepreg. This will be useful in at least two ways.

First is users do not have to build it on their machine and saving them one step.
Second and more important is that maintaining the image. E.g. if a person is building the docker image of deepreg and at that time a specific package is not available on conda then it cant be build. Similarly if a package support is finished and its no more maintained then dockerfile will be outdated. However keeping an image on dockerhub will have a snapshot of working deepreg and all users will have to do is `docker run deepreg:version_no`.

**Comment by mathpluscode** [comment]
Hi @mianasbat thx for the advice, yes, we've been considering this, https://github.com/DeepRegNet/DeepReg/issues/608. Just recently I got occupied by other things.

**Comment by Zhiyuan-w** [comment]
=> [internal] load metadata for docker.io/tensorflow/tensorflow:2.3.1-gpu                                                                                                                                             12.4s
 => [auth] tensorflow/tensorflow:pull token for registry-1.docker.io                                                                                                                                                    0.0s
 => [ 1/10] FROM docker.io/tensorflow/tensorflow:2.3.1-gpu@sha256:1d0736e46ae9a961c2111394a43e0bfd266e6151a90d613b6f86229cf01e40e5                                                                                      0.0s
 => CACHED [ 2/10] RUN apt-get update                                                                                                                                                                                   0.0s
 => CACHED [ 3/10] RUN apt-get install -y wget git && rm -rf /var/lib/apt/lists/*                                                                                                                                       0.0s
 => CACHED [ 4/10] RUN wget     https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh     && mkdir /root/.conda     && bash Miniconda3-latest-Linux-x86_64.sh -b     && rm -f Miniconda3-latest-Linux-  0.0s
 => CACHED [ 5/10] WORKDIR /app                                                                                                                                                                                         0.0s
 => CACHED [ 6/10] RUN git clone https://github.com/DeepRegNet/DeepReg.git                                                                                                                                              0.0s
 => CACHED [ 7/10] WORKDIR DeepReg                                                                                                                                                                                      0.0s
 => CACHED [ 8/10] RUN git pull                                                                                                                                                                                         0.0s
 => CACHED [ 9/10] RUN conda env create -f environment.yml     && conda init bash     && echo "conda activate deepreg" >> /root/.bashrc                                                                                 0.0s
 => CACHED [10/10] RUN /root/miniconda3/envs/deepreg/bin/pip install -e .                                                                                                                                               0.0s
 => exporting to image                                                                                                                                                                                                  0.1s
 => => exporting layers   

It works today... I changed nothing. I met the issue, as loading metadata for docker.io/tensorflow/tensorflow:2.3.1-gpu. It gives the error that TensorFlow is not able to be loaded.
