### ISSUE TITLE
Fix Running DeepReg Remotely (on the Cluster) page

### ISSUE THREAD

**Issue by Zhiyuan-w** [DeepRegNet/DeepReg#788]
The section of Installing the Environment in the document is out of date, which needs to be rewritten. 

If the documentation request is approved, would you be willing to submit a PR? _(Help
can be provided if you need assistance submitting a PR)_

Yes

**Comment by NMontanaBrown** [comment]
@alkististav has similar issues. Why are there two open issues with the same/related work? Best to fix all on the same branch

**Comment by Zhiyuan-w** [comment]
> @alkististav has similar issues. Why are there two open issues with the same/related work? Best to fix all on the same branch
> 
> EDIT: Ok so I understood this is about the docs?

Yerh.
