### ISSUE TITLE
The ddf in demo_predict seems to be all 0s

### ISSUE THREAD

**Issue by ebonmati** [DeepRegNet/DeepReg#802]
## Subject of the issue

When running the unpaired abdomen CT registration, with the provided pre-trained models (unsup, weakly or comb) the return ddfs seem to be all 0s, and no registration is applied to the images when displaying the images.

If the bug is confirmed, would you be willing to submit a PR? _(Help can be provided if
you need assistance submitting a PR)_

Yes 

## Your environment

- DeepReg version (commit hash)

4830c793d68bfca1d68ea512c52c9159caac75aa

- OS (e.g. Ubuntu 20.04, MacOS 10.15, etc.)

Ubuntu 20.04.1 

- Python Version (3.7, 3.8, etc.)

3.7.10

- TensorFlow

  - TensorFlow Version: 2.3.1
  - CUDA Version (10.1, etc.) if available.
  - cuDNN Version

  We support only TensorFlow 2.3 officially.

  If using GPU, please check https://www.tensorflow.org/install/source#gpu to verify the
  GPU support.

## Steps to reproduce

python demos/unpaired_ct_abdomen/demo_data.py
python demos/unpaired_ct_abdomen/demo_predict.py --method weakly

## Expected behaviour

We would expect a ddf in logs_train with some values. We would not expect a good registration, but at least some small deformation should be returned.

## Actual behaviour

The ddf seems to be all 0s, so no registration is applied to the images when I visualise them.

**Comment by YipengHu** [comment]
Thanks @ebonmati 's new update: training model again the DDFs seems normal. It is likely caused by the old pre-trained model format. Re-training model for this demo...
