### ISSUE TITLE
Train with Big CT file

### ISSUE THREAD

**Issue by JiYuanFeng** [DeepRegNet/DeepReg#814]
Hi! Thank you for your nice work.
I would like to train the model with my own dataset. The dataset consists of big CT data (around 370*512*512).
It's ok to train the model by sliding window mechanisms? for example, crop a subcube of 128*128*128 to train the model.
Or it will be better to resize the original data into a smaller one to train the model, and resize the generated transform to warp the original data finally? Could you give me some advice about how I can do it or/and what I need to modify?
Thank you for your advice

**Comment by YipengHu** [comment]
Hi @JiYuanFeng 
Thanks for the message. I'm afraid DeepReg is not supporting patch-based registration yet - i guess this is what you meant by sliding window mechanisms? So you are only left with resizing for now, which obviously is a highly application-dependent pre-processing step. Happy to discuss further if you share more details with the data, application etc.

**Comment by JiYuanFeng** [comment]
Hi,Thank you for your useful reply!!! It help me a lot.
