### ISSUE TITLE
Paired Lung CT Tutorial Error

### ISSUE THREAD

**Issue by codeenthusiast** [DeepRegNet/DeepReg#819]
## Paired Lung CT Tutorial Error

I have trying to run this tutorial on the terminal but unfortunately getting an error as below when launching demo training via running "python demos/paired_ct_lung/demo_train.py". I have installed DeepReg and set the directory to DeepReg.

My other question is whether I have to run this in my terminal or whether I can run it on Jupyter in Anaconda. Thank you for your help.

<img width="456" alt="Screen Shot 2021-10-29 at 5 43 37 PM" src="https://user-images.githubusercontent.com/6239462/139504931-92fbf9cd-d78d-49d3-b0bf-db3577cbf374.png">

## Your environment

- Mac OS 11.5.1

**Comment by YipengHu** [comment]
please install deepreg first following the documentation: https://deepreg.readthedocs.io/en/latest/getting_started/install.html

**Comment by codeenthusiast** [comment]
Thank you, I have followed all the instructions and installed DeepReg which I can see under my username directory. When I again try to run the above command line, I now get "zsh: illegal hardware instruction". However, my TensorFlow is up to date as well.

**Comment by mathpluscode** [comment]
> zsh: illegal hardware instruction

Hi, the idea development environment should be Linux (not including MacOS) with intel chips. The error you got is similar to https://stackoverflow.com/questions/65383338/zsh-illegal-hardware-instruction-python-when-installing-tensorflow-on-macbook and I'm not sure if it is linked to DeepReg.
