### ISSUE TITLE
Sharing DeepReg models through Hugging Face Hub

### ISSUE THREAD

**Issue by omarespejel** [DeepRegNet/DeepReg#823]
Hi DeepReg team!

> This issue was [originally posted](https://github.com/DeepRegNet/deepreg-model-zoo/issues/1) in the model zoo.

Your pre-trained models seem amazing! I see you host and share the DeepReg demo models on your own repo. **Would you be interested in sharing your models in the [Hugging Face Hub](http://hf.co/models)?**

This integration would allow you to freely download/upload models, and make your work more accessible and visible to the rest of the ML community. We can help you set up a DeepReg organization (examples, [Facebook AI](https://huggingface.co/facebook) y [Stanford NLP](https://huggingface.co/stanfordnlp)).

Creating the repos and adding new models should be a relatively straightforward process. This is a [step-by-step guide](https://huggingface.co/docs/hub/adding-a-model) explaining the process in case you're interested. Please let us know if you would be interested and if you have any questions.

Some of the **benefits** of sharing your models through the Hub would be:

**-   Presence in the HF Hub might lower the entry of barrier to DeepReg models as well as increase its visibility.**
-   Repos provide useful metadata about their tasks, languages, metrics, etc that make them discoverable.
-   Versioning, commit history, and diffs.
-   Multiple features from TensorBoard visualizations, PapersWithCode integration, and more.

Additionally, **we have a library to programmatically access repositories** (both downloading pretrained models and pushing, with a lot of nice things such as filtering, caching, etc). If we want to try out this integration, I would suggest **you add one or two models manually and then use the `huggingface_hub` library to implement downloading those models programmatically from the DeepReg demo models.** You might want to check [our documentation](https://huggingface.co/docs/hub/adding-a-library) to read more about it.

Relevant references:

-   [Adding a model to the Hub.](https://huggingface.co/docs/hub/adding-a-model)
-   [Integrate your library with the Hub.](https://huggingface.co/docs/hub/adding-a-library)

Happy to hear your thoughts,

Omar and the Hugging Face team

cc @osanseviero @abidlabs (@NMontanaBrown thanks for the reference!)

**Comment by NMontanaBrown** [comment]
Hi @omarespejel  - this looks really cool. I might be able to work on this after March due to several internal PhD deadlines. I'll set a reminder to potentially ping you if any questions then 😄

**Comment by omarespejel** [comment]
No worries! And yes, please let me know how I might be helpful 😃.

In Hugging Face we are really motivated to collaborate with and support the deep learning for healthcare initiative, and these models could be key 🤗. We would love to give them even more visibility.

**Comment by osanseviero** [comment]
Reopening this if that's ok :smile:

**Comment by mathpluscode** [comment]
> Should this be reopened? 😄

Hi @osanseviero, thanks for your consistent interest. Apologize for the late reply. Unfortunately, we currently do not have the bandwidth to maintain or integrate these models from DeepReg.

Meanwhile, if you are interested, the [PyTorch-based code base and models](https://github.com/kate-sann5100/CrossInstitutionFewShotSegmentation) of our recent work ([paper 1](https://arxiv.org/abs/2201.06358), [preprint 2](https://arxiv.org/abs/2209.05160)) on medical imaging are available and still under active maintenance by @kate-sann5100. Please feel free to open an issue there 😄
