### ISSUE TITLE
Most suitable algorithms for 2D histology images?

### ISSUE THREAD

**Issue by jbmcs** [DeepRegNet/DeepReg#824]
Hi! I'm looking at AI-driven image registration and this looks like a fantastic resource you've put together :) the data domain I'm working in is histopathology, and I'm trying to register 2 images of the same tissue from multiple modalities. I've noticed that the examples in this repo are mainly for 3D and/or moving data, whereas mine is static, 2D, images. So I was just wondering what your thoughts were on which algorithms (if any) from this repo would be the best for me to experiment with to start with. Thanks!

**Comment by Borda** [comment]
Hello, I would be curious how this package performs on the ANHIR challenge :rabbit: https://anhir.grand-challenge.org
Also would be interesting to include it in the BIRL SOTA docker image: https://github.com/Borda/BIRL
