### ISSUE TITLE
Test + docs: dataset/tfrecord

### ISSUE THREAD

**Issue by NMontanaBrown** [DeepRegNet/DeepReg#99]
# Issue description

Unit testing, docs and lint for deepreg/dataset/tfrecord. Missing docstrings.

- _bytes_features
- _float_feature
- _int64_feaure
- serializer: 
- decode_array
- parser
- write_tfrecords
- get_tfrecords_filenames
- load_tfrecords

## Type of Issue

Please delete options that are not relevant.

- [x] Documentation update
- [x] Test request
- [x] Linting request

#### What's the expected result?
Unit tests for types, returns and an improvement in the documentation of the functions.

**Comment by mathpluscode** [comment]
the tfrecord functionality is not tested yet, i will inform you once i confirmed it,
optionally, we can skip this for the release

**Comment by mathpluscode** [comment]
@NMontanaBrown @YipengHu I suggest to remove tfrecord related codes, (save it in another branch), and add this feature after r1 ;)

**Comment by YipengHu** [comment]
> @NMontanaBrown @YipengHu I suggest to remove tfrecord related codes, (save it in another branch), and add this feature after r1 ;)

I'm fine with it - not a huge impact on the usability.

**Comment by NMontanaBrown** [comment]
@mathpluscode I think I can work on some bits and bobs of tests for this part of the package, alternatively we should migrate somewhere for post R1?

**Comment by mathpluscode** [comment]
@NMontanaBrown I would say let's remove it ftm, after r1, we can add it back. So that we can concentrate on more important issues. Also it can largely improve the test coverage ;) If you are ok, I can add a PR to remove the code.

**Comment by YipengHu** [comment]
> @NMontanaBrown I would say let's remove it ftm, after r1, we can add it back. So that we can concentrate on more important issues. Also it can largely improve the test coverage ;) If you are ok, I can add a PR to remove the code.

either is fine with me.

**Comment by YipengHu** [comment]
@NMontanaBrown can you review this and close the ticket if the tasks are specified in others?

**Comment by NMontanaBrown** [comment]
@YipengHu  @mathpluscode  are we adding the tf record functionality or not? It's stowed away in a branch at the moment, we haven't really discussed bringing it back or not...? so nothing to unit test if no tf record function.

**Comment by mathpluscode** [comment]
> @YipengHu @mathpluscode are we adding the tf record functionality or not? It's stowed away in a branch at the moment, we haven't really discussed bringing it back or not...? so nothing to unit test if no tf record function.

Yeah. We need to add it.
According to some experience somewhere else, the current data loading mechanism is probably not optimum.

If anyone would like to implement this feature, I can help with it. Otherwise, it will be on my to-to list ;)

**Comment by mathpluscode** [comment]
I will close this issue for now. The way of using generator is not optimal for me for now. Therefore more changes should come to data loader.

The idea implementation should be
- build a dataset of paths
- use dataset.map to apply transformations
so that no need of using generator, i hope this can make data loading faster and easier to understand, though not sure how much we gain.

tfrecord will be delayed until requested.
